// LXS (back slot) — algorithm case data for @moishy/algsets.
//
// LXS solved from the BR/back side (the backSlotEoLxs extra); its own dedicated set.
// From the lxsBackSlot Google Sheet
// (https://docs.google.com/spreadsheets/d/1Xa6251D9G00g-jMQy0KzUg7xx39rsSjkJLMzsxinC7Q).
// subset = the sheet's slot-orientation tab (UBR/RBU/BUR/DBR/RBD/BDR); id = case number.
//
// Authored per packages/algsets/AUTHORING.md — algs only; recognition/AUF/cost are derived.

import { type AlgSet, defineAlgSet } from "../define.ts";

export const lxsBackSlot: AlgSet = defineAlgSet({
  id: "lxsBackSlot",
  name: "LXS (back slot)",
  cases: [
    {
      id: "1",
      name: "UR/UF",
      subset: "UBR",
      algs: ["R U R2 U' R' U R' U2 R", "U2 R' U2 R2 U R U' R' U R' U2 R", "R U R2 U' R' U2 R' U R"],
    },
    {
      id: "2",
      name: "UF/UR",
      subset: "UBR",
      algs: ["U R' U2 R2 U R U' R' U R' U' R", "U R U2 R U' R2 U' R2 U' R"],
    },
    {
      id: "3",
      name: "UF/UL",
      subset: "UBR",
      algs: [
        "U2 R' U' R U2 R' U2 R S' U2 S",
        "U2 R' U' R U2 R U2 R U' R U' R'",
        "U2 R' U' R U' R' U' R U2 R U R U' R'",
      ],
    },
    {
      id: "4",
      name: "UL/UF",
      subset: "UBR",
      algs: ["U2 R' U' R S' U2 S R' U2 R", "U' R' U' R U' R U R U' R' U R' U' R"],
    },
    {
      id: "5",
      name: "UL/UB",
      subset: "UBR",
      algs: ["R U R' U R' U2 R'", "R U R' U R2 U' R U' R'"],
    },
    { id: "6", name: "UB/UL", subset: "UBR", algs: ["U2 R' U' R2 U R U' R'"] },
    { id: "7", name: "UB/UR", subset: "UBR", algs: ["U R U R2 U' R2 U' R"] },
    { id: "8", name: "UR/UB", subset: "UBR", algs: ["R' U' R U' R U R' U' R2 U' R"] },
    {
      id: "9",
      name: "UL/UR",
      subset: "UBR",
      algs: ["U2 R' U' R U R' U' R U' R U R U' R'", "R' U2 R U R' U' R U S' U2 S"],
    },
    {
      id: "10",
      name: "UR/UL",
      subset: "UBR",
      algs: ["U2 R' U' R U' R U R2 U' R'", "R' U R S' U2 S R' U' R"],
    },
    {
      id: "11",
      name: "UF/UB",
      subset: "UBR",
      algs: ["U S' U2 S R U2 R' U2 R'", "U R U R' U R U' R2 U' R'"],
    },
    { id: "12", name: "UB/UF", subset: "UBR", algs: ["U' R' U2 R2 U R U' R'"] },
    {
      id: "13",
      name: "UF/DR",
      subset: "UBR",
      algs: ["U' R U2 R U' R' U R2 U2 R'", "U' R U2 R U' R U' R2 U2 R"],
    },
    {
      id: "14",
      name: "DR/UF",
      subset: "UBR",
      algs: ["U' R' U2 R U2 R' U2 R", "U' R' U2 R U' R' U R"],
    },
    {
      id: "15",
      name: "UF/BR",
      subset: "UBR",
      algs: ["U' R' U2 R S' U2 S R' U2 R", "U2 R U R' U' R2 U' R U' R' U R"],
    },
    { id: "16", name: "BR/UF", subset: "UBR", algs: ["U2 R U R U' R2 U' R U2 R' U2 R"] },
    {
      id: "17",
      name: "UL/DR",
      subset: "UBR",
      algs: ["R' U2 R U2 R' U' R2 U R' U' R'", "U2 S' U2 S R' U2 R U R' U' R"],
    },
    {
      id: "18",
      name: "DR/UL",
      subset: "UBR",
      algs: ["U2 R' U' R U2 R' U2 R", "U2 R' U' R U' R' U R", "R' U R U2 R' U' R"],
    },
    {
      id: "19",
      name: "UL/BR",
      subset: "UBR",
      algs: ["R' U' R U2 R U R' U' R2 U' R", "R2 U R2 U2 R2 U' R2"],
    },
    { id: "20", name: "BR/UL", subset: "UBR", algs: ["U R U R U' R' U R' U' R"] },
    { id: "21", name: "UB/DR", subset: "UBR", algs: ["U' R U2 R' U2 R'"] },
    { id: "22", name: "DR/UB", subset: "UBR", algs: ["R' U' R U2 R' U' R U R' U' R"] },
    {
      id: "23",
      name: "UB/BR",
      subset: "UBR",
      algs: ["U R' U' R U R' U' R2 U R U' R'", "U2 R2 U R2 U' R2 U' R2"],
    },
    { id: "24", name: "BR/UB", subset: "UBR", algs: ["U R U R U' R2 U' R U2 R' U' R"] },
    { id: "25", name: "UR/DR", subset: "UBR", algs: ["R' U R U' R U R' U' R'"] },
    { id: "26", name: "DR/UR", subset: "UBR", algs: ["R' U2 R U R' U' R"] },
    { id: "27", name: "UR/BR", subset: "UBR", algs: ["U R' U' R2 U R U' R' U R' U' R"] },
    { id: "28", name: "BR/UR", subset: "UBR", algs: ["U R U2 R' U' R2 U' R2 U' R"] },
    {
      id: "29",
      name: "DR/BR",
      subset: "UBR",
      algs: ["R' U' R U R' U' R U R' U' R", "R2 U' R2 U' R2 U2 R2"],
    },
    {
      id: "30",
      name: "BR/DR",
      subset: "UBR",
      algs: ["U' R U2 R' U' R2 U' R2 U R", "U' R U2 R U2 R2 U2 R"],
    },
    {
      id: "31",
      name: "UR/UF",
      subset: "RBU",
      algs: ["R' U' R S' U2 S", "R' U' R2 U R2 U' R2 U R", "U2 R U2 R' U2 R2 U R"],
    },
    {
      id: "32",
      name: "UF/UR",
      subset: "RBU",
      algs: ["U2 R U' R' U R2 U2 R' U' R2", "U R' U2 R U2 R U R U' R2 U' R"],
    },
    {
      id: "33",
      name: "UF/UL",
      subset: "RBU",
      algs: ["U R' U' R U' R' U' R S' U2 S", "U2 R U R' U' R' U2 R' U' R"],
    },
    {
      id: "34",
      name: "UL/UF",
      subset: "RBU",
      algs: ["R' U' R U' S' U2 S", "R' U2 R U R U R U' R'", "U' R' U' R U R U R U' R2 U' R"],
    },
    {
      id: "35",
      name: "UL/UB",
      subset: "RBU",
      algs: ["U R U2 R2 U' R' U' R'", "U R U R' S' U2 S U R'", "U R U2 R2 U' R2 U R U2 R'"],
    },
    {
      id: "36",
      name: "UB/UL",
      subset: "RBU",
      algs: ["U S' R' U' R U' R' U' R S", "U' R U R' U R U' R2 U' R2 U' R"],
    },
    { id: "37", name: "UB/UR", subset: "RBU", algs: ["U R U2 R2 U2 R2 U R U' R' U' R"] },
    { id: "38", name: "UR/UB", subset: "RBU", algs: ["R U2 R2 U2 R2 U R"] },
    {
      id: "39",
      name: "UL/UR",
      subset: "RBU",
      algs: [
        "R U2 R' U2 R U' R U' R' U2 R2",
        "U R' U' R U R' U R2 U R U' R2 U' R",
        "U R' U R U R U2 R' U' R2 U' R'",
      ],
    },
    {
      id: "40",
      name: "UR/UL",
      subset: "RBU",
      algs: [
        "U R' U' R U R U2 R' U' R2 U' R'",
        "U' R U R U' R2 U' R S' U2 S",
        "U2 R U R' U R' U2 R2 U R",
      ],
    },
    {
      id: "41",
      name: "UF/UB",
      subset: "RBU",
      algs: [
        "U' S' U2 S U' R' U' R",
        "U R U2 R' U2 R' U' R' U' R",
        "R' U' R2 U R U' R' U' R' U' R",
      ],
    },
    {
      id: "42",
      name: "UB/UF",
      subset: "RBU",
      algs: ["R' U' R U2 S' U2 S", "R' U R U2 R U R U' R'"],
    },
    {
      id: "43",
      name: "UF/DR",
      subset: "RBU",
      algs: ["U' R' U' R U' R U R' U' R'", "U R' U R2 U R' U' R'"],
    },
    { id: "44", name: "DR/UF", subset: "RBU", algs: ["R' U' R"] },
    {
      id: "45",
      name: "UF/BR",
      subset: "RBU",
      algs: [
        "U2 R' U R2 U R U' R2 U' R",
        "U' R' U' R S' U2 S R' U' R",
        "U2 R U R U' R' U' R U R' U' R'",
      ],
    },
    {
      id: "46",
      name: "BR/UF",
      subset: "RBU",
      algs: ["R' U' R U S' U2 S", "U2 R U2 R' U' R2 U' R'"],
    },
    { id: "47", name: "UL/DR", subset: "RBU", algs: ["U R U R' U' R'"] },
    {
      id: "48",
      name: "DR/UL",
      subset: "RBU",
      algs: ["U R' U' R U' R' U' R", "U2 R' U R U R' U' R"],
    },
    { id: "49", name: "UL/BR", subset: "RBU", algs: ["U R U2 R U' R' U' R'"] },
    { id: "50", name: "BR/UL", subset: "RBU", algs: ["U' R U R U' R2 U' R"] },
    {
      id: "51",
      name: "UB/DR",
      subset: "RBU",
      algs: ["U S' U2 S U R' U' R", "U R U R U' R' U R U R U' R'"],
    },
    {
      id: "52",
      name: "DR/UB",
      subset: "RBU",
      algs: ["R U2 R2 U' R2 U' R'", "U2 R' U2 R U R' U' R U R' U' R"],
    },
    {
      id: "53",
      name: "UB/BR",
      subset: "RBU",
      algs: ["U R U2 R U' R U' R2 U R", "R U R' U' R' U R' U' R", "U' R U R U' R' U R U R' U' R'"],
    },
    {
      id: "54",
      name: "BR/UB",
      subset: "RBU",
      algs: ["U2 R U2 R U2 R2 U' R", "R U R U' R2 U' R U R' U' R"],
    },
    {
      id: "55",
      name: "UR/DR",
      subset: "RBU",
      algs: ["U R' U2 R2 U R' U' R'", "U R' U' R2 U R U' R2 U R"],
    },
    { id: "56", name: "DR/UR", subset: "RBU", algs: ["U R' U R U' R' U' R"] },
    {
      id: "57",
      name: "UR/BR",
      subset: "RBU",
      algs: ["U R' U' R U2 R U R U' R2 U' R", "U' R' U' R U2 R' U' R S' U2 S"],
    },
    {
      id: "58",
      name: "BR/UR",
      subset: "RBU",
      algs: [
        "U2 R U' R' U R U' R' U' R2 U R'",
        "U R' U' R2 U2 R U' R' U' R'",
        "U2 R' U' R U' R' U2 R2 U R U' R'",
      ],
    },
    {
      id: "59",
      name: "DR/BR",
      subset: "RBU",
      algs: ["U' R' U' R U2 R' U' R", "U R' U2 R U' R' U' R"],
    },
    {
      id: "60",
      name: "BR/DR",
      subset: "RBU",
      algs: ["U R' U' R2 U R' U' R'", "U R U R U' R2 U R", "U2 R U R U' R' U2 R' U' R"],
    },
    { id: "61", name: "UR/UF", subset: "BUR", algs: ["U R' U' R U' R U R U' R'"] },
    { id: "62", name: "UF/UR", subset: "BUR", algs: ["U' R U R2 U' R'"] },
    {
      id: "63",
      name: "UF/UL",
      subset: "BUR",
      algs: ["U R' U2 R U' R U R U' R'", "U' R U2 R2 U2 R2 U' R"],
    },
    { id: "64", name: "UL/UF", subset: "BUR", algs: ["U R' U' R U2 R U R2 U' R'"] },
    { id: "65", name: "UL/UB", subset: "BUR", algs: ["R' U' R U2 R' U R2 U R U' R'"] },
    {
      id: "66",
      name: "UB/UL",
      subset: "BUR",
      algs: ["U R' U2 R S' U2 S R' U R", "U R' U2 R U' R U R' U' R2 U R"],
    },
    { id: "67", name: "UB/UR", subset: "BUR", algs: ["R U R' U' R2 U R"] },
    {
      id: "68",
      name: "UR/UB",
      subset: "BUR",
      algs: [
        "R U R2 U' R2 U2 R U' R' U' R",
        "U' R U R' U' R' U' R' U' R",
        "U' R U' R' U S' U2 S R' U' R U' R",
      ],
    },
    {
      id: "69",
      name: "UL/UR",
      subset: "BUR",
      algs: ["U2 R U2 R2 U2 R'", "U2 R' U2 R S' U2 S", "U2 R U2 R U' R U' R'"],
    },
    {
      id: "70",
      name: "UR/UL",
      subset: "BUR",
      algs: ["S' U2 S R' U2 R", "R' U' R U' R' U R2 U R U' R'", "U' R U2 R' U' R' U' R2 U' R"],
    },
    {
      id: "71",
      name: "UF/UB",
      subset: "BUR",
      algs: ["U' R U R' U R' U' R2 U R U2 R'", "R' U' R U' R U R U' R' U R' U2 R"],
    },
    { id: "72", name: "UB/UF", subset: "BUR", algs: ["U2 R' U' R U' R U R U' R2 U' R"] },
    {
      id: "73",
      name: "UF/DR",
      subset: "BUR",
      algs: ["U2 R' U' R U R U R' U' R'", "U' R U R' U R U' R' U' R'"],
    },
    {
      id: "74",
      name: "DR/UF",
      subset: "BUR",
      algs: ["U R' U' R U R' U2 R", "U R' U' R U2 R' U R"],
    },
    { id: "75", name: "UF/BR", subset: "BUR", algs: ["U R U R U R' U2 R'"] },
    {
      id: "76",
      name: "BR/UF",
      subset: "BUR",
      algs: [
        "U R' U' R U R' U2 R S' U2 S",
        "R U R' U R2 U2 R2 U' R",
        "R' U R U' R U R2 U' R2 U' R",
      ],
    },
    {
      id: "77",
      name: "UL/DR",
      subset: "BUR",
      algs: ["U2 R' U' R U R' U2 R2 U R' U' R'", "U2 R2 S R2 S' R' U2 R"],
    },
    { id: "78", name: "DR/UL", subset: "BUR", algs: ["U R' U2 R U R' U2 R"] },
    { id: "79", name: "UL/BR", subset: "BUR", algs: ["U R' U R U' R U R U' R'"] },
    {
      id: "80",
      name: "BR/UL",
      subset: "BUR",
      algs: [
        "U R' U2 R U2 R U R2 U' R'",
        "U' R U R U' R' U R' U' R U R' U2 R",
        "R' U R U R' U2 R2 U R U' R'",
      ],
    },
    { id: "81", name: "UB/DR", subset: "BUR", algs: ["U2 R' U' R U R' U' R2 U R' U' R'"] },
    { id: "82", name: "DR/UB", subset: "BUR", algs: ["U2 R' U' R U' R' U' R U2 R' U' R"] },
    {
      id: "83",
      name: "UB/BR",
      subset: "BUR",
      algs: [
        "R' U' R U R' U R2 U R U' R'",
        "U' R' U2 R U' R U R U' R2 U' R",
        "U R' U R S' U2 S R' U R",
      ],
    },
    {
      id: "84",
      name: "BR/UB",
      subset: "BUR",
      algs: ["U' R U2 R' U' R2 U' R' U R' U' R", "U' R U2 R U' R' U R' U' R2 U' R'"],
    },
    {
      id: "85",
      name: "UR/DR",
      subset: "BUR",
      algs: [
        "U2 R' U' R U R' U R2 U R' U' R'",
        "U' R U' R' U R2 U2 R' U' R U' R",
        "U' R' U2 R U R' U R2 U R' U' R'",
      ],
    },
    { id: "86", name: "DR/UR", subset: "BUR", algs: ["U2 R' U2 R", "U' R' U R"] },
    {
      id: "87",
      name: "UR/BR",
      subset: "BUR",
      algs: ["U2 R' U2 R2 U R U' R' U' R' U' R", "U R' U R U2 R U R2 U' R'"],
    },
    { id: "88", name: "BR/UR", subset: "BUR", algs: ["R U R U' R'"] },
    { id: "89", name: "DR/BR", subset: "BUR", algs: ["U R' U R U2 R' U R", "U R' U R U R' U2 R"] },
    {
      id: "90",
      name: "BR/DR",
      subset: "BUR",
      algs: [
        "U' R' U2 R U R U R' U' R'",
        "R' D R' U' R U R' U' R D' R",
        "R U' R U R' D R' U' R D'",
      ],
    },
    { id: "91", name: "UR/UF", subset: "DBR", algs: ["R' U' R2 U R' U R2 U' R' U' R'"] },
    { id: "92", name: "UF/UR", subset: "DBR", algs: ["U R' U' R U2 R' U R U' R U R U' R'"] },
    { id: "93", name: "UL/UR", subset: "DBR", algs: ["U R' U R U' R U R U' R2 U' R"] },
    { id: "94", name: "UF/DR", subset: "DBR", algs: ["R' U R U R U R' U' R'"] },
    {
      id: "95",
      name: "DR/UF",
      subset: "DBR",
      algs: ["U' R U R U R U' R' U' R'", "R D R' U' R D' R' U R' U' R"],
    },
    {
      id: "96",
      name: "UF/BR",
      subset: "DBR",
      algs: ["U' S' U2 S", "U R' U' R U R U R U' R'", "R U R2 U' R2 U R"],
    },
    { id: "97", name: "BR/UF", subset: "DBR", algs: ["U R U R U' R' U' R' U' R"] },
    {
      id: "98",
      name: "BR/DR",
      subset: "DBR",
      algs: ["R U R U' R2 U' R U' R' U' R", "R U R U' R' U R' U R U R' U' R"],
    },
    { id: "99", name: "UR/UF", subset: "RBD", algs: ["U R' U' R2 U R U' R2 U' R"] },
    {
      id: "100",
      name: "UF/UR",
      subset: "RBD",
      algs: ["U R U2 R' U2 R2 U' R"],
    },
    { id: "101", name: "UL/UR", subset: "RBD", algs: ["U R U R' U' R2 U' R"] },
    {
      id: "102",
      name: "UF/DR",
      subset: "RBD",
      algs: [
        "U R' U' R U2 R U R' U' R'",
        "U' R' U2 R U' R U R' U' R'",
        "U' R U R2 U' R' U R' U' R",
      ],
    },
    {
      id: "103",
      name: "DR/UF",
      subset: "RBD",
      algs: ["U' R' U' R U R' U' R", "R' U2 R U2 R' U' R"],
    },
    {
      id: "104",
      name: "UF/BR",
      subset: "RBD",
      algs: [
        "U R U2 R U' R' U R U' R' U' R'",
        "U R' U R U' R' U2 R2 U R U' R'",
        "R U' R' D' R U R' D R2 U' R2",
      ],
    },
    {
      id: "105",
      name: "BR/UF",
      subset: "RBD",
      algs: ["U2 R U2 R U2 R2 U R", "U' R' U' R U R' U' R S' U2 S", "U2 R U2 R U2 R' U' R' U2 R"],
    },
    { id: "106", name: "DR/BR", subset: "RBD", algs: ["R' U' R U2 R' U R U' R' U' R"] },
    {
      id: "107",
      name: "BR/DR",
      subset: "RBD",
      algs: ["R' U' R U2 R' U2 R2 U R' U' R'", "R U R U' R' U R' U' R U2 R' U2 R"],
    },
    {
      id: "108",
      name: "UR/UF",
      subset: "BDR",
      algs: ["U' R' U R2 U R U' R'", "R U R U' R' U' R U R U' R'"],
    },
    { id: "109", name: "UF/UR", subset: "BDR", algs: ["U2 R' U' R U' R' U' R2 U R U' R'"] },
    {
      id: "110",
      name: "UL/UR",
      subset: "BDR",
      algs: ["R U R2 U R' U2 R'", "U R' U2 R U R' U2 R2 U R U' R'"],
    },
    { id: "111", name: "UF/DR", subset: "BDR", algs: ["U2 R' U' R2 U2 R' U2 R'"] },
    {
      id: "112",
      name: "DR/UF",
      subset: "BDR",
      algs: ["U' R' U R U' R' U R", "U' R' U R U2 R' U2 R"],
    },
    {
      id: "113",
      name: "UF/BR",
      subset: "BDR",
      algs: ["U2 R' U' R U2 R U R2 U' R2 U' R", "U' R' U R U R' U' R U' R U R U' R'"],
    },
    { id: "114", name: "BR/UF", subset: "BDR", algs: ["R U R U' R' U R' U2 R"] },
    { id: "115", name: "DR/BR", subset: "BDR", algs: ["R' U' R U R' U2 R U R' U' R"] },
    {
      id: "116",
      name: "BR/DR",
      subset: "BDR",
      algs: [
        "R U R U' R2 U2 R U R' U2 R",
        "R' U' R U R' U R U' R U R' U' R'",
        "R U' R U' R' U2 R U' R U' R' U R U' R",
      ],
    },
  ],
});
