/**
 * Advanced F2L — algorithm case data for `@moishy/algsets`.
 *
 * F2L cases where a piece of the pair is trapped in another slot: the alg frees it and inserts the pair.
 *
 * Scraped from https://speedcubedb.com/a/3x3/AdvancedF2L (August 2026), which publishes every case for all
 * four slots — the site's Front Right / Front Left / Back Left / Back Right tabs — with
 * slot-specific algorithms rather than mechanical mirrors. All four are kept, as four
 * `AlgSet`s: recognition is derived per case from its primary, and the same case in a
 * different slot is a different state, so it has to be a different set. fr 42, fl 35, bl 28, br 31 cases, 660 algs.
 *
 * **Alg order matters here**, though not because of rotations. Recognition comes from `algs[0]`
 * alone, so each slot's primary must be an alg that solves *this* slot's case: the D-layer cross
 * solved, and exactly the slot itself plus the one holding the trapped piece open. Rotations are a
 * non-issue — `defineAlgSet` derives a case's state as `solved . p . A^-1`, accounting for the
 * frame the alg lands in, so a primary containing a `y` derives exactly the same state as a
 * rotation-free one. Every alg here is the source's, verbatim; none has been rewritten or
 * de-rotated. CFOP uses rotations freely and so does this data.
 *
 * 5 listed algs are not kept. Each needs the cross NOT already solved, or leaves the
 * centres drifted with no later step to restore them, so it cannot be executed in a fixed-frame
 * CFOP solve at all: d' R' u' R' u R, r U' r' U2 r U r' d' R U R', r U' r' U2 r U r' d R U R', d' R' D' F' D R, d L u L u' L'.
 *
 * **The source's case numbering is not 1:1 with cube states here, so this set does not follow
 * it.** SpeedCubeDB groups Advanced cases by the *shape* of the case, and the algs it lists under
 * one heading handle the piece being trapped in DIFFERENT slots — so they solve different states
 * and are not interchangeable variants. Measured: 54 source headings collapse to 42 fr / 35 fl / 28 bl / 31 br distinct
 * states, with source headings splitting across several states and several states claimed by more
 * than one heading. Cases here are therefore one-per-state, grouped by the state each alg
 * actually solves, with the contributing source headings kept in `name`. Storing the site's
 * grouping verbatim would have left most variants unable to solve their own case, and the states
 * they *do* solve unrecognized — a coverage hole of exactly the kind that hid in oll and zbls.
 *
 * Because the four slots' coverage differs in the source, each slot has its own case list rather
 * than a shared one. The trapped piece IS the other slot's cubie, so that slot was never solved
 * to begin with: freeing it costs a method nothing it had already banked.
 *
 * **What a consuming method must recognize on.** The pair's own location and orientation is not a
 * sufficient key: an advanced case whose pair happens to sit in an ordinary position — because
 * what makes it advanced is a *foreign* piece blocking the target slot — has the same pair
 * signature as the plain case for that position, whose alg cannot solve it. Adding whichever
 * cubies currently OCCUPY the slot separates them completely (measured: 5-6 collisions per slot
 * on the pair alone, 0 with the occupant). So key on the pair plus the slot occupants, and then
 * fallThrough(f2l, advancedF2l) is unambiguous; under the pair-only key the plain set silently
 * shadows advanced cases it cannot solve. Pinned by a test in index_test.ts.
 *
 * ```ts
 * import { advancedF2lFr } from "@moishy/algsets/advanced-f2l";
 * advancedF2lFr.cases.length;
 * ```
 *
 * @module
 */

import { type AlgCaseInput, type AlgSet, defineAlgSet } from "../define.ts";

/** The four F2L slots, named by position. */
export type F2lSlot = "fr" | "fl" | "bl" | "br";

// FR slot — 42 distinct states.
const FR_CASES: AlgCaseInput[] = [
  {
    id: "af2l-1",
    name: "AF2L 1 / AF2L 1a / AF2L 2a / AF2L 3a",
    subset: "Trapped Corner",
    algs: ["S R' S'", "F' U' F R' U' R", "F' U' F U' y2 F' U' F", "F' U' F U2 L' U' L"],
  },
  {
    id: "af2l-1-b",
    name:
      "AF2L 1 / AF2L 2 / AF2L 3 / AF2L 8 / AF2L 22 / AF2L 23 / AF2L 24 / AF2L 25 / AF2L 26 / AF2L 28 / AF2L 29 / AF2L 30 / AF2L 31 / AF2L 32 / AF2L 33 / AF2L 37 / AF2L 38 / AF2L 39 / AF2L 40 / AF2L 41 / AF2L 42 / AF2L 4a",
    subset: "Trapped Corner",
    algs: [
      "R U' R' y R U' R'",
      "R U' R' f R' f'",
      "R U' R' U R2 F R F' R",
      "R U' R' L U2 L'",
      "R U' R' U F' r U r'",
      "R U' R' U F' L F L'",
      "R U' F R' U R F' R'",
      "U' R' F R F' U2 L U L'",
      "R U' R' U L U' L' U L U L'",
      "R U' R2 U R",
      "l F' U L' U' M'",
      "R U' R' U2 L' U L",
      "R U' R' U' f R f'",
      "R U' R' U2 L U L'",
      "R U' R2 U' R U' R' U' R",
      "R U' R' y R' U R U R' U' R",
      "R U' R' U' L' U L U L' U' L",
      "R U R' U' R U' R' U R' U' R",
      "R U' R' U R' U' R U' R' U R",
      "R U R' U' R U' R' f' L' f",
      "R U' R' U f' U' L' U L' f",
      "R U' R' y R' U' R U' R' U R",
      "R U' R' U' L' U' L U' L' U L",
      "R U R' U' R U' R' U' L' U' L",
      "R U' R' y R U2 R' U R U' R'",
      "R U' R' U' L U2 L' U L U' L'",
      "R U' R' y' U2 R U2 R' U R U' R'",
      "R U' R2 U2 R U R' U2 R",
      "R U' R2 U2 R U2 R' U R",
      "F' U2 L' U2 L2 U L' F",
      "R U' R' y U' R' U2 R U R' U2 R",
      "R U' R' U2 L' U2 L U2 L' U L",
      "U R U2 R2 U R",
    ],
  },
  {
    id: "af2l-2",
    name: "AF2L 2",
    subset: "Trapped Corner",
    algs: ["L F' U2 F L'", "F' L U2 L' F"],
  },
  {
    id: "af2l-2-b",
    name: "AF2L 2 / AF2L 10 / AF2L 12 / AF2L 7a",
    subset: "Trapped Corner",
    algs: ["L R U' R' U2 L'", "U2 R U R' U2 R' U R", "U2 R U R' L' U L", "U2 R U R' U2 R' U' R"],
  },
  {
    id: "af2l-3",
    name: "AF2L 3 / AF2L 29 / AF2L 41 / AF2L 5a / AF2L 6a",
    subset: "Trapped Corner",
    algs: [
      "y' R' U2 R2 U' R'",
      "F' U L' U L U' L U L' F",
      "R U' R' U y L' U2 L R' U R",
      "y U L' U L R' U2 R",
      "y U L' U L f' L f",
      "R U' R' d R' U2 R L' U L",
    ],
  },
  {
    id: "af2l-4",
    name: "AF2L 4 / AF2L 6 / AF2L 7",
    subset: "Trapped Corner",
    algs: ["F R' F' R U R' U2 R", "F R' F' R L' U L", "F R' F' U R U' R' U' R"],
  },
  {
    id: "af2l-4-b",
    name:
      "AF2L 4 / AF2L 5 / AF2L 6 / AF2L 7 / AF2L 25 / AF2L 26 / AF2L 27 / AF2L 28 / AF2L 30 / AF2L 32 / AF2L 38 / AF2L 39 / AF2L 29",
    subset: "Trapped Corner",
    algs: [
      "R U R' U2 f R f'",
      "R U R' U2 S U' R' U R S'",
      "R U R' U L U L'",
      "R U R' F U F'",
      "R U R' b L b'",
      "R U R' y L U L'",
      "R U' R' U' R U' R' f R f'",
      "R U R' U' B U' B'",
      "R U R' U' L U2 L'",
      "R U R' F' r U r'",
      "R U' R' U' R U' R2 U' R",
      "R U R y2 U2 L U L' U L2",
      "R U' R' U' R U' R' U2 L' U' L",
      "M F M' U L' U L U' L' U L",
      "R U R' F R U R' U' F' L U2 L'",
      "R U R' L U' L' U L U L'",
      "R U R' U' y' R U' R' U R U R'",
      "R U R' L' U L U' L F' L' F L' U L",
      "R U' R' U' R U' R' d' R' U' R",
      "R U R' d' L U' L' U L U L'",
    ],
  },
  {
    id: "af2l-4-c",
    name: "AF2L 4 / AF2L 5 / AF2L 8 / AF2L 9 / AF2L 10 / AF2L 14 / AF2L 18",
    subset: "Trapped Corner",
    algs: [
      "y U2 L' U L U' R U R'",
      "y U2 L' U L U2 f R f'",
      "y' U R' U2 R F U F'",
      "y' U R' U2 R U' R U R'",
      "y U L' U2 L U' L U L'",
      "y U' L F2 L' F2",
      "U' F R' F' R U L U L'",
      "U F' U2 F L' U' L",
    ],
  },
  {
    id: "af2l-5",
    name:
      "AF2L 5 / AF2L 13 / AF2L 15 / AF2L 17 / AF2L 19 / AF2L 20 / AF2L 1a / AF2L 2a / AF2L 3a / AF2L 7a / AF2L 8a / AF2L 9a",
    subset: "Trapped Corner",
    algs: [
      "U' R U2 M' B r'",
      "U' R U2 R' L U L'",
      "U R' F R F' R' U' R",
      "U R' F R2 U' R' U2 F'",
      "U R' F R F' U2 L' U' L",
      "U2 R B' U' B R'",
      "y U2 F R' U' R F'",
      "U2 l U' F' U l'",
      "U' R U2 R' f R f'",
      "U' R U2 R' U' L U L'",
      "U2 R U' R' U' R' U' R",
      "U2 R U' R' U2 B' U' B",
      "U2 R U' R' U L' U' L",
      "U2 R U' R' U2 R' U R",
      "U2 R U' R' U R' U2 R",
      "U2 R U' R' y R' U2 R",
      "U2 R U' R' L' U L",
      "U2 R U' R' d L' U L",
    ],
  },
  {
    id: "af2l-7",
    name: "AF2L 7",
    subset: "Trapped Corner",
    algs: ["U' F' U' f R S'"],
  },
  {
    id: "af2l-7-b",
    name: "AF2L 7 / AF2L 8",
    subset: "Trapped Corner",
    algs: ["y U' L' U' L R U R'", "U' F' U2 L U L' F"],
  },
  {
    id: "af2l-9",
    name: "AF2L 9",
    subset: "Trapped Corner",
    algs: ["U R' F' R F' R' F R"],
  },
  {
    id: "af2l-9-b",
    name: "AF2L 9",
    subset: "Trapped Corner",
    algs: ["U R' F R F' R U' R' U' L' U' L"],
  },
  {
    id: "af2l-10",
    name: "AF2L 10 / AF2L 12 / AF2L 17 / AF2L 1a / AF2L 11a",
    subset: "Trapped Edge",
    algs: [
      "U' R U R2 U' R",
      "U' R U R' U2 L' U' L",
      "F U' F' U2 R U' R' L' U' L",
      "U' R U R' U' f' L' f",
      "U' R U R2 U' R U' R' U R",
      "U' R U R' y' U' L' U' L",
      "U' R U R' U' y2 F' U' F",
      "U' R U R' d' R' U' R",
    ],
  },
  {
    id: "af2l-10-b",
    name: "AF2L 10 / AF2L 18 / AF2L 23 / AF2L 29 / AF2L 33 / AF2L 42",
    subset: "Trapped Edge",
    algs: [
      "y L' U L R U' R' U R U R'",
      "U r' F' D' F D r",
      "L F' U F L'",
      "y' F R' U R F'",
      "F' U F L U L' U L U' L'",
      "y' R' U R2 U R' U R U R'",
      "y' R' U R2 U2 R' U2 R U' R'",
      "y' R' U R2 U2 R' U' R U2 R'",
    ],
  },
  {
    id: "af2l-11",
    name:
      "AF2L 11 / AF2L 16 / AF2L 18 / AF2L 19 / AF2L 22 / AF2L 23 / AF2L 26 / AF2L 27 / AF2L 33 / AF2L 35 / AF2L 37 / AF2L 38 / AF2L 7a / AF2L 8a / AF2L 9a / AF2L 10a / AF2L 12a",
    subset: "Trapped Edge",
    algs: [
      "U' R U' R' L U' L'",
      "U' R U' M' B' r'",
      "U' R U' R' U L U2 L'",
      "U' R U' R' r' U' R U M'",
      "U' R U' R' B' R B R'",
      "U' R U' R' F U2 F'",
      "U' R U' R' U2 F' L F L'",
      "R' F R F' R U2 R2 U R",
      "R U2 R2 U2 R",
      "R U2 R' y' L' U L",
      "R U2 R' U L U' L'",
      "R U2 R' F U' F'",
      "R U' R' F' r' F' r2 U r'",
      "R U2 R' L U2 L' U' L U L'",
      "R U' R' U R U2 R' y R U' R'",
      "R U' R' U R U2 R' L U2 L'",
      "R U' R' U R U2 R' U' L U' L'",
      "R U2 R' U R' U' R",
      "R U2 R' f' L' f",
      "R U2 R' y R' U' R",
      "R U2 R' U' L' U' L",
      "U' R U' R' U f R' f'",
      "U' R U' R' U2 F' r U r'",
      "U' R U' R' y L U2 L'",
      "U' F' U2 L' U' L2 F L'",
      "U' R U' R' y' U' R U' R'",
      "U' R U' R' d L U' L'",
    ],
  },
  {
    id: "af2l-12",
    name: "AF2L 12",
    subset: "Trapped Edge",
    algs: ["U' R U R2 F R U F'"],
  },
  {
    id: "af2l-13",
    name: "AF2L 13",
    subset: "Trapped Edge",
    algs: ["U R U' R' U S R' S'"],
  },
  {
    id: "af2l-13-b",
    name: "AF2L 13 / AF2L 14",
    subset: "Trapped Edge",
    algs: [
      "U R U' R' U R U' R' f R' f'",
      "U R U' R' U R U' R' y' L U' L'",
      "U R U' R' U R U' R' L U2 L'",
    ],
  },
  {
    id: "af2l-14",
    name: "AF2L 14",
    subset: "Trapped Edge",
    algs: ["U2 r2 U B2 U' r2", "U2 L2 u L2 u' L2"],
  },
  {
    id: "af2l-15",
    name: "AF2L 15",
    subset: "Trapped Edge",
    algs: ["R U R' U' R U R' F U F'"],
  },
  {
    id: "af2l-15-b",
    name: "AF2L 15",
    subset: "Trapped Edge",
    algs: ["U R' F R2 U' R' U2 R' F' R"],
  },
  {
    id: "af2l-16",
    name: "AF2L 16",
    subset: "Trapped Edge",
    algs: ["U' F' R' U' R F"],
  },
  {
    id: "af2l-19",
    name: "AF2L 19 / AF2L 20 / AF2L 21 / AF2L 4a / AF2L 5a / AF2L 6a",
    subset: "Trapped Edge",
    algs: [
      "U R U R' U y R U R'",
      "U R U R' U f R f'",
      "U R U R' L U L'",
      "U R U M' B r'",
      "U R U R' U' F U F'",
      "U R U R2 U2 R",
      "U R U R' y R' U R",
      "U R L' U L R'",
      "U R U R' U' L' U L",
      "U M F M'",
    ],
  },
  {
    id: "af2l-21",
    name: "AF2L 21",
    subset: "Trapped Edge",
    algs: ["U R F U F' R'"],
  },
  {
    id: "af2l-21-b",
    name: "AF2L 21",
    subset: "Trapped Edge",
    algs: ["U L u L u' L'", "U L D F D' L'"],
  },
  {
    id: "af2l-22",
    name: "AF2L 22",
    subset: "Trapped Edge",
    algs: ["y M F2 M'", "S R2 S'"],
  },
  {
    id: "af2l-24",
    name: "AF2L 24",
    subset: "Trapped Edge",
    algs: ["M F2 M'", "L' R U2 R' L"],
  },
  {
    id: "af2l-24-b",
    name: "AF2L 24",
    subset: "Trapped Edge",
    algs: ["U F r U2 r' F'"],
  },
  {
    id: "af2l-25",
    name: "AF2L 25",
    subset: "Both Pieces Trapped",
    algs: ["F' U R' U2 R F"],
  },
  {
    id: "af2l-25-b",
    name: "AF2L 25 / AF2L 27 / AF2L 36 / AF2L 1a / AF2L 2a / AF2L 3a",
    subset: "Both Pieces Trapped",
    algs: [
      "R' F R F' U R' U2 R",
      "R' F R2 U R' F'",
      "R' F R2 U' R' U' R U R' U2 F'",
      "R' F R F' U2 L' U L U' L' U' L",
      "R' F R F' y R U' R'",
      "R' F R F' L U2 L'",
      "R' F R F' U' L U' L'",
      "R' F R2 U' R' U F'",
      "R' F R F' d R' F R F'",
    ],
  },
  {
    id: "af2l-26",
    name: "AF2L 26",
    subset: "Both Pieces Trapped",
    algs: ["L R U2 R' L'"],
  },
  {
    id: "af2l-27",
    name: "AF2L 27",
    subset: "Both Pieces Trapped",
    algs: ["R' F R2 U R2 F' R"],
  },
  {
    id: "af2l-34",
    name: "AF2L 34",
    subset: "Both Pieces Trapped",
    algs: ["F' R' U R U' R' U' R F"],
  },
  {
    id: "af2l-34-b",
    name: "AF2L 34 / AF2L 35 / AF2L 36",
    subset: "Both Pieces Trapped",
    algs: [
      "R U' R' U' R U R' U f R' f'",
      "R U' R' U' R U R' r' U' R U M'",
      "R U' R' U' R U R' L U' L'",
      "R U' R' U' R U M' B' r'",
      "R U' R' U' R U R' U' F U' F'",
      "R U' R' U' R U R' F U2 F'",
    ],
  },
  {
    id: "af2l-34-c",
    name: "AF2L 34",
    subset: "Both Pieces Trapped",
    algs: ["R U' R2 f' U' f R"],
  },
  {
    id: "af2l-35",
    name: "AF2L 35 / AF2L 37",
    subset: "Both Pieces Trapped",
    algs: ["R U R' U' R U2 R' U L U L'", "R U R' U2 R U' R' f R f'"],
  },
  {
    id: "af2l-37",
    name: "AF2L 37",
    subset: "Both Pieces Trapped",
    algs: ["F' U' R' U2 R U R' U' R F"],
  },
  {
    id: "af2l-40",
    name: "AF2L 40",
    subset: "Both Pieces Trapped",
    algs: ["F R' F' R U' R U2 R2 U' R"],
  },
  {
    id: "af2l-40-b",
    name: "AF2L 40 / AF2L 42",
    subset: "Both Pieces Trapped",
    algs: ["R' F R F' R U' R' U R U' R' U y R U' R'", "R' F R F' R U' R' U R U' R' d' L U' L'"],
  },
  {
    id: "af2l-4a",
    name: "AF2L 4a",
    subset: "Trapped Corner",
    algs: ["U R U' R' S R2 S'"],
  },
  {
    id: "af2l-5a",
    name: "AF2L 5a",
    subset: "Trapped Corner",
    algs: ["U l U' F2 U l'", "U R B' U2 B R'"],
  },
];

// FL slot — 35 distinct states.
const FL_CASES: AlgCaseInput[] = [
  {
    id: "af2l-1",
    name:
      "AF2L 1 / AF2L 2 / AF2L 3 / AF2L 26 / AF2L 27 / AF2L 31 / AF2L 32 / AF2L 33 / AF2L 34 / AF2L 35 / AF2L 37 / AF2L 39 / AF2L 40 / AF2L 42 / AF2L 1a / AF2L 2a / AF2L 3a / AF2L 36",
    subset: "Trapped Corner",
    algs: [
      "L' U' L U R U' R'",
      "M F' M'",
      "L' R U' R' L",
      "R L' U' L R'",
      "L' U' L y R U' R'",
      "L' U' L f R' f'",
      "L' U' L2 U2 L'",
      "L' U' L U R' U2 R",
      "L' U' L U y' L' U L",
      "L' U' L y R' U2 R",
      "L' U L U L' U L U2 R U R'",
      "L' U L U L' U L U f R f'",
      "L' U L U L' U L2 U L'",
      "L' U' L U y' R' U R U' R' U' R",
      "L' U' L R' U R U' R' U' R",
      "L' U' L y' R' U2 R U R' U' R",
      "L' U' L y L' U2 L U L' U' L",
      "L' U' L y U2 R' U2 R U R' U' R",
      "L' U' L y' U2 L' U2 L U L' U' L",
      "L' U' L R U' R' U R U' R' U2 R U' R'",
      "L' U' L R' U2 R2 U R2 U R",
      "L' U' L F' U' L F' L' F L U L' F",
      "L' U' L y' R' U' R",
      "L' U' L F' U' F",
      "L' U' L U' R' U' R",
      "L' U' L y U2 R' U' R",
      "L' U' L y' U2 L' U' L",
      "L' U' L U2 f' L' f",
      "L' U' L d R' U R U' R' U' R",
      "L' U' L d' R' U R U' R' U' R",
    ],
  },
  {
    id: "af2l-2",
    name: "AF2L 2 / AF2L 9 / AF2L 19 / AF2L 23 / AF2L 25 / AF2L 31",
    subset: "Trapped Corner",
    algs: [
      "y' R U' R' L U2 L'",
      "y' U' R' F R F' U F U F'",
      "U' R U F U' F' R'",
      "R' F U' F' R",
      "R' F R2 U' R2 F' R",
      "F R U' R2 F' R",
      "R' F R U' R' F' R2 U R' U R U R'",
    ],
  },
  {
    id: "af2l-2-b",
    name: "AF2L 2",
    subset: "Trapped Corner",
    algs: ["r' U F2 U' r"],
  },
  {
    id: "af2l-3",
    name:
      "AF2L 3 / AF2L 17 / AF2L 19 / AF2L 20 / AF2L 21 / AF2L 22 / AF2L 38 / AF2L 40 / AF2L 4a / AF2L 5a / AF2L 6a / AF2L 7a / AF2L 8a / AF2L 11a",
    subset: "Trapped Corner",
    algs: [
      "L' U2 L2 U' L'",
      "U2 L F' L' F R' U' R",
      "U F U2 R U R2 F' R",
      "U L' U L F' U2 F",
      "U L' U L R' U R",
      "U L' U L B L' B' L",
      "F2 R' F2 R",
      "L' U2 L R' U2 R U R' U' R",
      "F2 R' F2 D' R U' R' D R",
      "U L' U L y' U2 R' U R",
      "U L' U L y U2 L' U L",
      "U L' U L U' F R' F' R",
      "U L' U L R' U2 R",
      "U L' U L f' L f",
      "U L' U L y R' U R",
      "U2 L F' L' F y' U' R' U' R",
      "U2 L F' L' F U2 R' U' R",
      "U L' U L R B L' B' M' x'",
    ],
  },
  {
    id: "af2l-4",
    name:
      "AF2L 4 / AF2L 6 / AF2L 8 / AF2L 9 / AF2L 10 / AF2L 11 / AF2L 13 / AF2L 15 / AF2L 18 / AF2L 10a / AF2L 12a",
    subset: "Trapped Corner",
    algs: [
      "U2 L' U L U' R U R'",
      "U2 L' U L U L U L'",
      "U L' U2 L f R f'",
      "U L' U2 L U' L U L'",
      "U' L F2 L' F2",
      "U L' U2 L U R' U' R",
      "U' L F' L2 U L U2 F",
      "U' L F' L' F U2 R U R'",
      "U' L F' L' F L U L'",
      "U L' U2 L f' L' f",
      "U L' U2 L y U2 L' U' L",
      "U L' U2 L y' L' U' L",
      "U L' U2 L y R' U' R",
    ],
  },
  {
    id: "af2l-4-b",
    name: "AF2L 4 / AF2L 5 / AF2L 6 / AF2L 37",
    subset: "Trapped Corner",
    algs: [
      "F U F' U2 R U R'",
      "y' R U R' U2 y R U R'",
      "y' R U R' U L U L'",
      "F U F' L U L'",
      "F U2 R U' R' F' U R U R'",
    ],
  },
  {
    id: "af2l-4-c",
    name: "AF2L 4 / AF2L 5 / AF2L 6 / AF2L 7 / AF2L 8 / AF2L 9 / AF2L 25",
    subset: "Trapped Corner",
    algs: [
      "U' F U' R U R2 F' R",
      "r U' r' F R' U2 R",
      "L F' L' F R' U2 R",
      "L F' L' S' L f",
      "U' L' U L R U' R'",
      "U' L' U L y' L U2 L'",
      "U' L' U L U2 L U' L'",
      "U' L' U L U' L U2 L'",
      "L F' L' F R U' R'",
    ],
  },
  {
    id: "af2l-5",
    name: "AF2L 5 / AF2L 17 / AF2L 19 / AF2L 7a / AF2L 8a / AF2L 9a / AF2L 13",
    subset: "Trapped Corner",
    algs: [
      "y' U' R U2 R' L U L'",
      "U2 F R' U' R F'",
      "U2 F U' F' U R' U' R",
      "U' F U2 F' R U R'",
      "y' U2 R U' R' U2 R' U R",
      "y' U2 R U' R' U R' U2 R",
      "y U2 L U' L' y L' U2 L",
      "y U2 L U' L' R' U R",
      "y' U2 R U' R' L' U L",
      "d R' F R F' R' U' R",
    ],
  },
  {
    id: "af2l-6",
    name: "AF2L 6 / AF2L 37 / AF2L 38",
    subset: "Trapped Corner",
    algs: ["L' U L U L' U' L2 U L'", "L' U L U L' U' L y' R' U2 R", "L' U L U L' U' L R' U R"],
  },
  {
    id: "af2l-7",
    name: "AF2L 7 / AF2L 11 / AF2L 12a / AF2L 8 / AF2L 18",
    subset: "Trapped Corner",
    algs: [
      "U' L' U' L R U R'",
      "U' L' U' L R' U' R",
      "U' L' U' L y' U' L' U' L",
      "U' L' U' L d' R U R'",
      "U' L' U' L d' R' U' R",
    ],
  },
  {
    id: "af2l-8",
    name: "AF2L 8 / AF2L 18 / AF2L 32 / AF2L 34 / AF2L 10a",
    subset: "Trapped Corner",
    algs: [
      "F U2 R U R2 U' R F'",
      "U' F U' F' L U2 L'",
      "F U' R U' R' U R' U' R F'",
      "F U' R U' R' F' R U' R' U' R U R'",
      "U' F U' F' U R U' R'",
    ],
  },
  {
    id: "af2l-10",
    name: "AF2L 10 / AF2L 12 / AF2L 11a",
    subset: "Trapped Edge",
    algs: [
      "U' F U F2 U' F",
      "y' U' R U R2 U' R",
      "y U' L U L2 U' L",
      "y' U' R U R2 F R U R' F' R",
      "U' F U F' U' R' U' R",
    ],
  },
  {
    id: "af2l-11",
    name:
      "AF2L 11 / AF2L 22 / AF2L 23 / AF2L 24 / AF2L 27 / AF2L 28 / AF2L 29 / AF2L 30 / AF2L 31 / AF2L 32 / AF2L 33 / AF2L 34 / AF2L 35 / AF2L 36 / AF2L 39 / AF2L 40 / AF2L 41 / AF2L 42",
    subset: "Trapped Edge",
    algs: [
      "U' L' U' R' U' R L",
      "L' U L U2 R U' R'",
      "r' F U' R U M'",
      "L' U L y' U L U' L'",
      "L' U L y U R U' R'",
      "L' U L2 U' L'",
      "L' U L U f' L' f",
      "L' U L U R U R' U R U' R'",
      "F U' R U R' U R U' R' F' R U' R'",
      "L' U L B L' B L B2",
      "L' U L y' L U L' U L U' L'",
      "L' U' L U L' U L f R f'",
      "L' U L y R U R' U R U' R'",
      "L' U L U' L U L' U L U' L'",
      "L' U L U R U' R' U' R U R'",
      "L' U L y' L U' L' U' L U L'",
      "L' U L2 U L' U L U L'",
      "L' U L y' U2 R' U2 R U' R' U R",
      "L' U L U R' U2 R U' R' U R",
      "L' U L y R' U2 R U' R' U R",
      "L' U L y' L' U2 L U' L' U L",
      "L' U L l U' L' U L U l'",
      "L' U L U2 R U2 R' U2 R U' R'",
      "F U2 R U2 R2 U' R F'",
      "L' U L U2 r U2 R2 U' R2 U' r'",
      "L' U L2 U2 L' U2 L U' L'",
      "L' U L2 U2 L' U' L U2 L'",
    ],
  },
  {
    id: "af2l-12",
    name: "AF2L 12",
    subset: "Trapped Edge",
    algs: ["U' L U L2 U' L2 U L'"],
  },
  {
    id: "af2l-12-b",
    name: "AF2L 12",
    subset: "Trapped Edge",
    algs: ["L' U' L U' L' U L U' L U2 L'"],
  },
  {
    id: "af2l-12-c",
    name: "AF2L 12",
    subset: "Trapped Edge",
    algs: ["U' L S U2 S' L'"],
  },
  {
    id: "af2l-14",
    name: "AF2L 14",
    subset: "Trapped Edge",
    algs: ["U2 R2 D' F2 D R2", "U2 R2 u' R2 u R2"],
  },
  {
    id: "af2l-14-b",
    name: "AF2L 14",
    subset: "Trapped Edge",
    algs: ["U' L' U L U' L' U L R' U2 R"],
  },
  {
    id: "af2l-14-c",
    name: "AF2L 14",
    subset: "Trapped Edge",
    algs: ["L' U' L U L' U' L U' R' U' R"],
  },
  {
    id: "af2l-15",
    name: "AF2L 15",
    subset: "Trapped Edge",
    algs: ["U' L' U L U' S' L S"],
  },
  {
    id: "af2l-16",
    name: "AF2L 16",
    subset: "Trapped Edge",
    algs: ["U' R' D' F' D R", "U' R' u' R' u R"],
  },
  {
    id: "af2l-16-b",
    name: "AF2L 16 / AF2L 10a",
    subset: "Trapped Edge",
    algs: ["U' L' F' U' F L", "U' r' D' F' D r", "y' U' F' R' U' R F"],
  },
  {
    id: "af2l-17",
    name: "AF2L 17 / AF2L 8a",
    subset: "Trapped Edge",
    algs: ["U2 F U F' R' U2 R", "U2 F U2 R' U' R F'"],
  },
  {
    id: "af2l-18",
    name: "AF2L 18 / AF2L 27",
    subset: "Trapped Edge",
    algs: ["F U R U' R' U' R U' R' L U2 L' F'", "F U' L U2 L' F'"],
  },
  {
    id: "af2l-21",
    name: "AF2L 21",
    subset: "Trapped Edge",
    algs: ["U F L U L' F'"],
  },
  {
    id: "af2l-22",
    name: "AF2L 22 / AF2L 7a",
    subset: "Trapped Edge",
    algs: ["R L' U2 L R'", "L F L' F L F' L'"],
  },
  {
    id: "af2l-25",
    name: "AF2L 25",
    subset: "Both Pieces Trapped",
    algs: ["R' F R2 U R' F' R U2 R'"],
  },
  {
    id: "af2l-26",
    name: "AF2L 26",
    subset: "Both Pieces Trapped",
    algs: ["L' R' U2 R L"],
  },
  {
    id: "af2l-36",
    name: "AF2L 36",
    subset: "Both Pieces Trapped",
    algs: ["F U L U2 L' U' L U L' F'"],
  },
  {
    id: "af2l-38",
    name: "AF2L 38",
    subset: "Both Pieces Trapped",
    algs: ["F U2 R U' R' f R f' F'"],
  },
  {
    id: "af2l-39",
    name: "AF2L 39",
    subset: "Both Pieces Trapped",
    algs: ["F L U' L' U L U L' F'"],
  },
  {
    id: "af2l-1a",
    name: "AF2L 1a",
    subset: "Trapped Corner",
    algs: ["U L' U' F' U' F L"],
  },
  {
    id: "af2l-1a-b",
    name: "AF2L 1a / AF2L 3a",
    subset: "Trapped Corner",
    algs: ["F' L F L' R U' R'", "F' L F L' U2 L U' L'"],
  },
  {
    id: "af2l-6a",
    name: "AF2L 6a",
    subset: "Trapped Corner",
    algs: ["U S' L S", "y U L R' U R L'"],
  },
  {
    id: "af2l-8a",
    name: "AF2L 8a",
    subset: "Trapped Corner",
    algs: ["U R' D R U' R' U' D' R"],
  },
];

// BL slot — 28 distinct states.
const BL_CASES: AlgCaseInput[] = [
  {
    id: "af2l-1",
    name: "AF2L 1 / AF2L 3 / AF2L 1a / AF2L 2a / AF2L 3a",
    subset: "Trapped Corner",
    algs: [
      "S' L' S",
      "y' L' U' L U R U' R'",
      "y R' U' R U' R U' R'",
      "y R' U' R2 U2 R'",
      "y' L' U' L2 U2 L'",
      "y R' U' R y R' U' R",
      "f' L' f L' U' L",
      "y' L' U' L F' U' F",
      "y' L' U' L y L' U' L",
      "y' L' U' L U' R' U' R",
      "y R' U' R U' L' U' L",
      "f' L' f U2 R' U' R",
      "y R' U' R y' U2 R' U' R",
      "y' L' U' L y U2 R' U' R",
    ],
  },
  {
    id: "af2l-1-b",
    name:
      "AF2L 1 / AF2L 2 / AF2L 3 / AF2L 22 / AF2L 23 / AF2L 24 / AF2L 25 / AF2L 27 / AF2L 28 / AF2L 29 / AF2L 30 / AF2L 31 / AF2L 32 / AF2L 33 / AF2L 36 / AF2L 37 / AF2L 38 / AF2L 39 / AF2L 40 / AF2L 4a",
    subset: "Trapped Corner",
    algs: [
      "L U' L' y L U' L'",
      "L U' L' y' R U' R'",
      "L U' L' U' R U' R'",
      "L U' L' R U2 R'",
      "L U' L' y' U2 L U' L'",
      "L U' L2 U L",
      "F' L U' L' F",
      "L U' L' y' U' R' U R",
      "L U' L' U2 R' U R",
      "L U' L' U' F U F'",
      "L U' L' U f R f'",
      "L U' L2 U' L U' L' U' L",
      "L U' L' y' R' U R U R' U' R",
      "L U' L' y L' U L U L' U' L",
      "L U' L' U' R' U R U R' U' R",
      "L U' L' U L' U' L U' L' U L",
      "L U' L' y L' U' L U' L' U L",
      "L U' L' y' R' U' R U' R' U R",
      "L U L' U' L U' L' b' R' b",
      "L U' L' F' L F' L' F2",
      "L U' L' U' R' U' R U' R' U R",
      "L U' L' R' F R U R' U' F' R",
      "L U' L' y L U2 L' U L U' L'",
      "L U' L' U' R U2 R' U R U' R'",
      "L U' L' y' U2 L U2 L' U L U' L'",
      "L U' L2 U2 L U2 L' U L",
      "L U' L2 U2 L U L' U2 L",
      "U L U2 L2 U L",
      "L U' L' d' L' U L",
      "L U' L' d' L U L'",
    ],
  },
  {
    id: "af2l-2",
    name: "AF2L 2",
    subset: "Trapped Corner",
    algs: ["l U' F2 U l'", "y' r' U F2 U' r"],
  },
  {
    id: "af2l-4",
    name:
      "AF2L 4 / AF2L 5 / AF2L 6 / AF2L 25 / AF2L 26 / AF2L 27 / AF2L 34 / AF2L 35 / AF2L 36 / AF2L 37 / AF2L 38 / AF2L 39 / AF2L 41 / AF2L 42 / AF2L 29",
    subset: "Trapped Corner",
    algs: [
      "L U L' y U2 L U L'",
      "L U L' U2 F U F'",
      "L U L' y' U2 R U R'",
      "L U L' U R U R'",
      "L U L' f R f'",
      "L U L' y' L U L'",
      "L U L' y' U' R U' R'",
      "L U L' F U2 F'",
      "L U L' U' R U2 R'",
      "L U L' U y R U' R'",
      "L U L' B' R B R'",
      "L U L' y U2 L U2 L' U' L U L'",
      "L U L' U R U2 R' U' R U R'",
      "L U L' y' L U2 L' U' L U L'",
      "L U L' y U L U' L' U L U L'",
      "L U L' R U' R' U R U R'",
      "L U L' y' U' L U' L' U L U L'",
      "L U L' R U2 R' y' U R' U' R",
      "L U L' R U2 R' U F' U' F",
      "L U L' R U2 R2 U' R2 U' R'",
      "L U' L' U' L U' L' d' L' U' L",
    ],
  },
  {
    id: "af2l-4-b",
    name: "AF2L 4 / AF2L 6 / AF2L 7 / AF2L 8 / AF2L 9",
    subset: "Trapped Corner",
    algs: [
      "B L' B' L U L' U2 L",
      "B L' B' L R' U R",
      "y' U' L' U L R U' R'",
      "y' U' L' U L y' L U2 L'",
      "y U' R' U R y' R U2 R'",
      "y' U' L' U L U2 L U' L'",
    ],
  },
  {
    id: "af2l-6",
    name: "AF2L 6 / AF2L 13 / AF2L 15",
    subset: "Trapped Corner",
    algs: ["y U2 R' U R U R U R'", "y' U' L F' L' F U2 R U R'", "y' U' L F' L' F L U L'"],
  },
  {
    id: "af2l-7",
    name: "AF2L 7",
    subset: "Trapped Corner",
    algs: ["U' f' r' D r S", "U' f' L' F L S"],
  },
  {
    id: "af2l-8",
    name: "AF2L 8",
    subset: "Trapped Corner",
    algs: ["R D' R' U R U D R'"],
  },
  {
    id: "af2l-8-b",
    name: "AF2L 8",
    subset: "Trapped Corner",
    algs: ["U' f' L' f U' R U R'"],
  },
  {
    id: "af2l-9",
    name: "AF2L 9",
    subset: "Trapped Corner",
    algs: ["U L' B' L B' L' B L"],
  },
  {
    id: "af2l-10",
    name: "AF2L 10 / AF2L 12 / AF2L 11a",
    subset: "Trapped Edge",
    algs: [
      "U' L U L2 U' L",
      "U' L U L' U2 R' U' R",
      "U' L U L' U' F' U' F",
      "U' L U L' y U' L' U' L",
      "U' L U L' y' U' R' U' R",
    ],
  },
  {
    id: "af2l-11",
    name: "AF2L 11 / AF2L 16 / AF2L 18 / AF2L 7a / AF2L 9a / AF2L 12a",
    subset: "Trapped Edge",
    algs: [
      "U' L U' L' R U' R'",
      "U' L U' L' F' L F L'",
      "U' L U' L' R2 F R F' R",
      "U' L U' L' U' f R' f'",
      "U' L U' L' y R U2 R'",
      "L U2 L' U L' U' L",
      "L U2 L' U' R' U' R",
      "U' L U' L' y' L U2 L'",
      "U' L U' L' d' R U' R'",
    ],
  },
  {
    id: "af2l-11-b",
    name: "AF2L 11 / AF2L 29 / AF2L 35 / AF2L 39",
    subset: "Trapped Edge",
    algs: [
      "y U' R' U' L' U' L R",
      "f' L f R U R2 F R F'",
      "y' L' U L U R' U2 R U' R' U R",
      "f' L f U2 R' U' R U R' U2 R",
    ],
  },
  {
    id: "af2l-12",
    name:
      "AF2L 12 / AF2L 17 / AF2L 19 / AF2L 20 / AF2L 21 / AF2L 2a / AF2L 3a / AF2L 7a / AF2L 8a / AF2L 9a / AF2L 13",
    subset: "Trapped Edge",
    algs: [
      "U2 L U' L' R' U' R",
      "U2 L F' U' F L'",
      "U' L U2 L' F U F'",
      "U' L U2 L' U' R U R'",
      "U' L U2 L' y' U2 L U L'",
      "U2 L U' L' y' U2 R' U' R",
      "U2 L U' L' U R' U' R",
      "U2 L U' L' U2 L' U L",
      "U2 L U' L' U L' U2 L",
      "U2 L U' L' y L' U2 L",
      "U2 L U' L' y' R' U2 R",
      "U2 L U' L' R' U R",
      "U r' U L U' x L' U' L",
    ],
  },
  {
    id: "af2l-12-b",
    name: "AF2L 12",
    subset: "Trapped Edge",
    algs: ["U2 L U L' R' U R"],
  },
  {
    id: "af2l-13",
    name: "AF2L 13",
    subset: "Trapped Edge",
    algs: ["U L U' L' U S' L' S"],
  },
  {
    id: "af2l-14",
    name: "AF2L 14",
    subset: "Trapped Edge",
    algs: ["L U L' U' L U L' U R U R'"],
  },
  {
    id: "af2l-14-b",
    name: "AF2L 14",
    subset: "Trapped Edge",
    algs: ["U2 R2 D B2 D' R2", "U2 R2 u R2 u' R2"],
  },
  {
    id: "af2l-14-c",
    name: "AF2L 14",
    subset: "Trapped Edge",
    algs: ["U L U' L' U L U' L' R U2 R'"],
  },
  {
    id: "af2l-15",
    name: "AF2L 15",
    subset: "Trapped Edge",
    algs: ["U' R' U' R2 u R u' R'"],
  },
  {
    id: "af2l-19",
    name: "AF2L 19 / AF2L 5a / AF2L 17",
    subset: "Trapped Edge",
    algs: ["U f' L f L' U2 L", "y' U L' U L R' U2 R", "y U R' U R L' U2 L", "U2 R d' R' U R F'"],
  },
  {
    id: "af2l-19-b",
    name: "AF2L 19 / AF2L 20 / AF2L 21 / AF2L 4a / AF2L 5a / AF2L 6a",
    subset: "Trapped Edge",
    algs: [
      "U L U L' U F U F'",
      "U L U L' R U R'",
      "U L U L' U' f R f'",
      "U L U L' y' U' L U L'",
      "U L U L2 U2 L",
      "U L U L' F' U F",
      "U L U L' y' R' U R",
      "U L R' U R L'",
      "U L R' U L' R",
      "U L U L' d R U R'",
    ],
  },
  {
    id: "af2l-21",
    name: "AF2L 21 / AF2L 23",
    subset: "Trapped Edge",
    algs: ["U R u R u' R'", "R u R' U R u' R'"],
  },
  {
    id: "af2l-24",
    name: "AF2L 24",
    subset: "Trapped Edge",
    algs: ["R' L U2 L' R"],
  },
  {
    id: "af2l-26",
    name: "AF2L 26",
    subset: "Both Pieces Trapped",
    algs: ["R L U2 L' R'"],
  },
  {
    id: "af2l-34",
    name: "AF2L 34 / AF2L 35 / AF2L 36",
    subset: "Both Pieces Trapped",
    algs: [
      "L U' L' U' L U L' U y L U' L'",
      "L U' L' U' L U L' F' L F L'",
      "L U' L' U' L U L' R U' R'",
      "L U' L' U' L U L' y' L U2 L'",
    ],
  },
  {
    id: "af2l-2a",
    name: "AF2L 2a",
    subset: "Trapped Corner",
    algs: ["L' B L B' R U2 R'"],
  },
  {
    id: "af2l-10a",
    name: "AF2L 10a / AF2L 16",
    subset: "Trapped Edge",
    algs: ["U' F' D' L' D F", "d' L' u' L' u L"],
  },
];

// BR slot — 31 distinct states.
const BR_CASES: AlgCaseInput[] = [
  {
    id: "af2l-1",
    name:
      "AF2L 1 / AF2L 2 / AF2L 3 / AF2L 25 / AF2L 26 / AF2L 27 / AF2L 33 / AF2L 34 / AF2L 35 / AF2L 37 / AF2L 38 / AF2L 39 / AF2L 41 / AF2L 1a / AF2L 2a / AF2L 3a",
    subset: "Trapped Corner",
    algs: [
      "R' U' R U L U' L'",
      "L R' U' R L'",
      "R' U' R F U' F'",
      "R' U' R y' R U' R'",
      "R' U' R2 U2 R'",
      "R' U' R l U L' U' M'",
      "R' U' R U2 L' U L",
      "R' U' R U y L' U L",
      "R' U' R F' U2 F",
      "R' U R U R' U R2 U R'",
      "R' U' R y U R' U R U' R' U' R",
      "R' U' R L' U L U' L' U' L",
      "R' U' R y R' U2 R U R' U' R",
      "R' U' R U' L' U2 L U L' U' L",
      "R' U' R y' U2 R' U2 R U R' U' R",
      "R' U' R L' U2 L y U' L U L'",
      "R' U' R L' U2 L U' F U F'",
      "R' U' R y R' U' R",
      "R' U' R f' L' f",
      "R' U' R U' L' U' L",
      "R' U' R U2 F' U' F",
      "R' U' R y U2 L' U' L",
      "R' U' R y' U2 R' U' R",
      "M' f' E",
      "R' U' R U d R' U2 R U R' U' R",
    ],
  },
  {
    id: "af2l-1-b",
    name: "AF2L 1 / AF2L 2 / AF2L 25",
    subset: "Trapped Corner",
    algs: ["y R U' R2 F' U' F R", "y R U' R' L U2 L'", "y R U' R' U' f R f'"],
  },
  {
    id: "af2l-2",
    name: "AF2L 2",
    subset: "Trapped Corner",
    algs: ["F R' U2 R F'"],
  },
  {
    id: "af2l-3",
    name:
      "AF2L 3 / AF2L 17 / AF2L 19 / AF2L 20 / AF2L 21 / AF2L 24 / AF2L 36 / AF2L 4a / AF2L 5a / AF2L 11a",
    subset: "Trapped Corner",
    algs: [
      "R' U2 R2 U' R'",
      "U2 F U' R' U R F'",
      "U R' U R U f' L f",
      "U R' U R y R' U2 R",
      "U R' U R y' L' U2 L",
      "U R' U R L' U L",
      "U R' U R U' F' U F",
      "U R' U R F R' F' R",
      "R' U2 R2 U2 R'",
      "R' U2 R y' R' U R U' R' U' R",
      "U R' U R y U R' U2 R",
      "U R' U R y U2 R' U R",
      "U R' U R y' U2 L' U L",
      "U R' U R L' U2 L",
      "y U2 L U' F' U F L'",
      "U R' U R d L' U L",
    ],
  },
  {
    id: "af2l-4",
    name: "AF2L 4 / AF2L 5 / AF2L 6 / AF2L 9 / AF2L 18 / AF2L 12a / AF2L 13",
    subset: "Trapped Corner",
    algs: [
      "U2 R' U R U' L U L'",
      "U2 R' U R U2 F U F'",
      "U2 R' U R y' U2 R U R'",
      "U2 R' U R U R U R'",
      "U R' U2 R U' R U R'",
      "U R' U2 R F' U' F",
      "U R' U2 R y' R' U' R",
      "U R' U2 R y L' U' L",
      "U' l U' R' U x U2 L U L'",
    ],
  },
  {
    id: "af2l-5",
    name: "AF2L 5 / AF2L 6",
    subset: "Trapped Corner",
    algs: ["y R U R' U L U L'", "y R U R' F U F'", "f R f' R U R'"],
  },
  {
    id: "af2l-7",
    name: "AF2L 7 / AF2L 8 / AF2L 9",
    subset: "Trapped Corner",
    algs: [
      "U' R' U R L U' L'",
      "U' R' U R U2 F' r U r'",
      "U' R' U R F U2 F'",
      "U' R' U R U2 R U' R'",
      "U' R' U R d' L U' L'",
    ],
  },
  {
    id: "af2l-7-b",
    name: "AF2L 7 / AF2L 11 / AF2L 16 / AF2L 18 / AF2L 27 / AF2L 8",
    subset: "Trapped Corner",
    algs: [
      "U' R' U' R L U L'",
      "U' R' U' R L' U' L",
      "U' R' U' R y U R' U' R",
      "U' R' U' R U f' L' f",
      "U' R' U' R U' F' U' F",
      "F' R' U2 R U' F",
      "U' R' U' R d' L U L'",
      "U' R' U' R d' L' U' L",
    ],
  },
  {
    id: "af2l-10",
    name:
      "AF2L 10 / AF2L 23 / AF2L 24 / AF2L 28 / AF2L 29 / AF2L 30 / AF2L 31 / AF2L 32 / AF2L 33 / AF2L 34 / AF2L 35 / AF2L 36 / AF2L 39 / AF2L 40 / AF2L 41 / AF2L 42 / AF2L 25 / AF2L 27",
    subset: "Trapped Edge",
    algs: [
      "R' U R L U' L' U L U L'",
      "F R' U R F'",
      "R' U R y' U R U' R'",
      "R' U R y U L U' L'",
      "R' U R2 U' R'",
      "R' U R U L U L' U L U' L'",
      "R' U R F R' F R F2",
      "R' U R y' R U R' U R U' R'",
      "R' U R U' R U R' U R U' R'",
      "R' U R U L U' L' U' L U L'",
      "R' U R y L U' L' U' L U L'",
      "R' U R y' R U' R' U' R U R'",
      "R' U R2 U R' U R U R'",
      "R' U R y U2 R' U2 R U' R' U R",
      "R' U R U L' U2 L U' L' U L",
      "R' U R y' R' U2 R U' R' U R",
      "R' U R2 U' R2 F R F' R U' R'",
      "R' U R L F' R' F R F L'",
      "R' U R U2 L U2 L' U2 L U' L'",
      "R' U R y' U R U2 R' U2 R U' R'",
      "R' U R2 U2 R' U R' F R F'",
      "R' U R2 U2 R' U2 R U' R'",
      "R' U R d' R' U' R",
      "R' U R d R' U' R",
      "R' U R U' L' U L d' L U L'",
    ],
  },
  {
    id: "af2l-10-b",
    name: "AF2L 10 / AF2L 11a",
    subset: "Trapped Edge",
    algs: ["y U' R U R2 U' R", "y' U' L U L2 U' L", "U' f R f' U' L' U' L"],
  },
  {
    id: "af2l-12",
    name: "AF2L 12",
    subset: "Trapped Edge",
    algs: ["U2 R U2 R2 U' R2 U R'"],
  },
  {
    id: "af2l-12-b",
    name: "AF2L 12",
    subset: "Trapped Edge",
    algs: ["U' R S' U2 S R'"],
  },
  {
    id: "af2l-12-c",
    name: "AF2L 12",
    subset: "Trapped Edge",
    algs: ["U' R U R2 U' R2 U R'"],
  },
  {
    id: "af2l-13",
    name: "AF2L 13 / AF2L 15 / AF2L 17 / AF2L 7a / AF2L 8a / AF2L 9a / AF2L 11a",
    subset: "Trapped Edge",
    algs: [
      "y U R' F R F' R' U' R",
      "y U R' F R2 U' R' U2 F'",
      "y U R' F R F' U2 L' U' L",
      "U2 f R' f' U L' U' L",
      "U2 f U' R' U f'",
      "y U2 R U' R' U2 R' U R",
      "y' U2 L U' L' U2 L' U L",
      "y U2 R U' R' y R' U2 R",
      "y U2 R U' R' L' U L",
      "y' U2 L U' L' R' U R",
      "y' U2 L F' U' F L'",
    ],
  },
  {
    id: "af2l-13-b",
    name: "AF2L 13",
    subset: "Trapped Edge",
    algs: ["U' R B' R2 U R U2 R B R'"],
  },
  {
    id: "af2l-14",
    name: "AF2L 14",
    subset: "Trapped Edge",
    algs: ["R' U' R U R' U' R U' L' U' L"],
  },
  {
    id: "af2l-14-b",
    name: "AF2L 14",
    subset: "Trapped Edge",
    algs: ["U2 L2 D' B2 D L2", "U2 r2 U' F2 U r2", "U2 L2 u' L2 u L2"],
  },
  {
    id: "af2l-15",
    name: "AF2L 15 / AF2L 35",
    subset: "Trapped Edge",
    algs: ["U' R' U R U' S R S'", "y R U' R' U' R U R' L U' L'"],
  },
  {
    id: "af2l-16",
    name: "AF2L 16 / AF2L 23",
    subset: "Trapped Edge",
    algs: ["U' L' u' L' u L", "y' U' F' D' L' D F", "L' u' L U' L' u L"],
  },
  {
    id: "af2l-17",
    name: "AF2L 17 / AF2L 8a",
    subset: "Trapped Edge",
    algs: ["U2 f R f' L' U2 L", "U2 f R f' U L' U' L"],
  },
  {
    id: "af2l-18",
    name: "AF2L 18 / AF2L 24 / AF2L 35",
    subset: "Trapped Edge",
    algs: ["U' f R' f' U' R U' R'", "R2 F R2 F'", "y R U2 R' L U2 L' U' L U L'"],
  },
  {
    id: "af2l-21",
    name: "AF2L 21",
    subset: "Trapped Edge",
    algs: ["U F D R D' F'", "d R u R u' R'"],
  },
  {
    id: "af2l-22",
    name: "AF2L 22 / AF2L 7a",
    subset: "Trapped Edge",
    algs: ["L R' U2 R L'", "R B R' B R B' R'", "l U R' U R U' l'"],
  },
  {
    id: "af2l-26",
    name: "AF2L 26",
    subset: "Both Pieces Trapped",
    algs: ["R' L' U2 L R"],
  },
  {
    id: "af2l-36",
    name: "AF2L 36",
    subset: "Both Pieces Trapped",
    algs: ["R' U R U' R' U2 L F' R2 U' R2 U F L' R"],
  },
  {
    id: "af2l-37",
    name: "AF2L 37 / AF2L 38",
    subset: "Both Pieces Trapped",
    algs: ["R' U R U R' U' R y R' U2 R", "R' U R U R' U' R L' U L"],
  },
  {
    id: "af2l-42",
    name: "AF2L 42",
    subset: "Both Pieces Trapped",
    algs: ["R' U' R U2 R' U2 R2 U R'"],
  },
  {
    id: "af2l-1a",
    name: "AF2L 1a / AF2L 3a",
    subset: "Trapped Corner",
    algs: ["B' R B R' L U' L'", "B' R B R' U2 R U' R'"],
  },
  {
    id: "af2l-6a",
    name: "AF2L 6a",
    subset: "Trapped Corner",
    algs: ["U S R S'", "y U R L' U L R'", "y' U L R' U R L'"],
  },
  {
    id: "af2l-8a",
    name: "AF2L 8a",
    subset: "Trapped Corner",
    algs: ["U L' D L U' L' U' D' L"],
  },
  {
    id: "af2l-10a",
    name: "AF2L 10a",
    subset: "Trapped Edge",
    algs: ["y U' F' R' U' R F"],
  },
];

const BY_SLOT: Record<F2lSlot, AlgCaseInput[]> = {
  fr: FR_CASES,
  fl: FL_CASES,
  bl: BL_CASES,
  br: BR_CASES,
};

const forSlot = (slot: F2lSlot, id: string, name: string): AlgSet =>
  defineAlgSet({ id, name, cases: BY_SLOT[slot] });

/** Advanced F2L, front-right slot (DFR corner 4 + FR edge 8). */
export const advancedF2lFr: AlgSet = forSlot("fr", "advancedF2lFr", "Advanced F2L (front-right)");
/** Advanced F2L, front-left slot (DLF corner 5 + FL edge 9). */
export const advancedF2lFl: AlgSet = forSlot("fl", "advancedF2lFl", "Advanced F2L (front-left)");
/** Advanced F2L, back-left slot (DBL corner 6 + BL edge 10). */
export const advancedF2lBl: AlgSet = forSlot("bl", "advancedF2lBl", "Advanced F2L (back-left)");
/** Advanced F2L, back-right slot (DRB corner 7 + BR edge 11). */
export const advancedF2lBr: AlgSet = forSlot("br", "advancedF2lBr", "Advanced F2L (back-right)");

/** All four slots, keyed by slot — for a method that wires the slots generically. */
export const advancedF2lBySlot: Readonly<Record<F2lSlot, AlgSet>> = {
  fr: advancedF2lFr,
  fl: advancedF2lFl,
  bl: advancedF2lBl,
  br: advancedF2lBr,
};
