// OLL — algorithm case data for @moishy/algsets.
//
// Transformed from old/oll.ts via scripts/transform_old_algsets.ts.
// Every source alg is kept as an interchangeable variant; recognition is
// derived from the primary (first) alg of each case. See /DESIGN.md.

import { type AlgSet, defineAlgSet } from "../define.ts";

export const oll: AlgSet = defineAlgSet({
  id: "oll",
  name: "OLL",
  cases: [
    {
      id: "oll-1",
      name: "OLL 1",
      subset: "dot",
      algs: [
        { alg: "F R' F' R U2' F R' F' R2' U2' R'", source: "SpeedCubeDB" },
        { alg: "R U2 R' R' F R F' U2 R' F R F'", source: "SpeedCubeDB" },
        { alg: "R U2 R2 F R F' U2 R' F R F'", source: "SpeedCubeDB" },
        { alg: "U R U' R2 D' r U' r' D R2 U R'", source: "SpeedCubeDB" },
        { alg: "f R U R' U' R f' U' r' U' R U M'", source: "SpeedCubeDB" },
        { alg: "L' U2 L2 F' L' F U2 L F' L' F", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-2",
      name: "OLL 2",
      subset: "dot",
      algs: [
        { alg: "f U R U' R' f' F U R U' R' F'", source: "SpeedCubeDB" },
        { alg: "F R U R' U' F' f R U R' U' f'", source: "SpeedCubeDB" },
        { alg: "U' R U' R2 D' r U r' D R2 U R'", source: "SpeedCubeDB" },
        { alg: "F R U R' U' S R U R' U' f'", source: "SpeedCubeDB" },
        { alg: "U r U r' U2 R U2 R' U2 r U' r'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-3",
      name: "OLL 3",
      subset: "dot",
      algs: [
        { alg: "F U R U' R' F' U f U R U' R' f'", source: "SpeedCubeDB" },
        { alg: "U' f R U R' U' f' U' F R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "U R' F2 R2 U2 R' F R U2 R2 F2 R", source: "SpeedCubeDB" },
        { alg: "r' R2 U R' U r U2 r' U M'", source: "SpeedCubeDB" },
        { alg: "M R U R' U r U2 r' U M'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-4",
      name: "OLL 4",
      subset: "dot",
      algs: [
        { alg: "F U R U' R' F' U' f U R U' R' f'", source: "SpeedCubeDB" },
        { alg: "U' f R U R' U' f' U F R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "U' R' F2 R2 U2 R' F' R U2 R2 F2 R", source: "SpeedCubeDB" },
        { alg: "R' F R F' U' S R' U' R U R S'", source: "SpeedCubeDB" },
        { alg: "U F U R U' R' F' U' F R U R' U' F'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-5",
      name: "OLL 5",
      subset: "square",
      algs: [
        { alg: "r' U' R U' R' U2' r", source: "SpeedCubeDB" },
        { alg: "r' U2 R U R' U r", source: "SpeedCubeDB" },
        { alg: "U2 l' U2 L U L' U l", source: "SpeedCubeDB" },
        { alg: "U2 R' F2 r U r' F R", source: "SpeedCubeDB" },
        { alg: "U2 R' F2 L F L' F R", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-6",
      name: "OLL 6",
      subset: "square",
      algs: [
        { alg: "r U R' U R U2' r'", source: "SpeedCubeDB" },
        { alg: "r U2 R' U' R U' r'", source: "SpeedCubeDB" },
        { alg: "F U' R2 D R' U' R D' R2 U F'", source: "SpeedCubeDB" },
        { alg: "U2 l U2 L' U' L U' l'", source: "SpeedCubeDB" },
        { alg: "U' x' D R2 U' R' U R' D' x", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-7",
      name: "OLL 7",
      subset: "lightning-bolt",
      algs: [
        { alg: "r U2' R' U' R U' r'", source: "SpeedCubeDB" },
        { alg: "r U R' U R U2 r'", source: "SpeedCubeDB" },
        { alg: "S' R U R' U R U2 R' U S", source: "SpeedCubeDB" },
        { alg: "L' U2 L U2 L F' L' F", source: "SpeedCubeDB" },
        { alg: "U2 l U L' U L U2 l'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-8",
      name: "OLL 8",
      subset: "lightning-bolt",
      algs: [
        { alg: "r' U2' R U R' U r", source: "SpeedCubeDB" },
        { alg: "U2 r' U' R U' R' U2 r", source: "SpeedCubeDB" },
        { alg: "l' U' L U' L' U2 l", source: "SpeedCubeDB" },
        { alg: "R U2 R' U2 R' F R F'", source: "SpeedCubeDB" },
        { alg: "R' F' r U' r' F2 R", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-9",
      name: "OLL 9",
      subset: "fish-shape",
      algs: [
        { alg: "F U R U' R2' F' R U R U' R'", source: "SpeedCubeDB" },
        { alg: "U R U R' U' R' F R R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "U R U R' U' R' F R2 U R' U' F'", source: "SpeedCubeDB" },
        { alg: "R U2 R' U' S' R U' R' S", source: "SpeedCubeDB" },
        { alg: "U2 F' U' F r U' r' U r U r'", source: "SpeedCubeDB" },
        { alg: "U' L' U' L U' L F' L' F L' U2 L", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-10",
      name: "OLL 10",
      subset: "fish-shape",
      algs: [
        { alg: "R U2' R' F R' F' R U' R U' R'", source: "SpeedCubeDB" },
        { alg: "R U R' U R' F R F' R U2 R'", source: "SpeedCubeDB" },
        { alg: "U F U F' R' F R U' R' F' R", source: "SpeedCubeDB" },
        { alg: "U M' R' U2 R U R' U R U M", source: "SpeedCubeDB" },
        { alg: "U2 L' U' L U L F' L2 U' L U F", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-11",
      name: "OLL 11",
      subset: "lightning-bolt",
      algs: [
        { alg: "M U' R U2' R' U' R U' R2' r", source: "SpeedCubeDB" },
        { alg: "M R U R' U R U2 R' U M'", source: "SpeedCubeDB" },
        { alg: "r' R2 U R' U R U2 R' U M'", source: "SpeedCubeDB" },
        { alg: "U2 r U R' U R' F R F' R U2 r'", source: "SpeedCubeDB" },
        { alg: "S R U R' U R U2 R' U2 S'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-12",
      name: "OLL 12",
      subset: "lightning-bolt",
      algs: [
        { alg: "F U R U' R' F' U' F U R U' R' F'", source: "SpeedCubeDB" },
        { alg: "U' M' R' U' R U' R' U2 R U' M", source: "SpeedCubeDB" },
        { alg: "F R U R' U' F' U F R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "U' S R' U' R U' R' U2 R U2 S'", source: "SpeedCubeDB" },
        { alg: "U M L' U' L U' L' U2 L U' M'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-13",
      name: "OLL 13",
      subset: "knight-shape",
      algs: [
        { alg: "F' U' F r U' r' U r U r'", source: "SpeedCubeDB" },
        { alg: "r U' r' U' r U r' F' U F", source: "SpeedCubeDB" },
        { alg: "F U R U2 R' U' R U R' F'", source: "SpeedCubeDB" },
        { alg: "F U R U' R2 F' R U R U' R'", source: "SpeedCubeDB" },
        { alg: "U2 f R U R2 U' R' U R U' f'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-14",
      name: "OLL 14",
      subset: "knight-shape",
      algs: [
        { alg: "F U F' R' F R U' R' F' R", source: "SpeedCubeDB" },
        { alg: "R' F R U R' F' R F U' F'", source: "SpeedCubeDB" },
        { alg: "r U R' U' r' F R2 U R' U' F'", source: "SpeedCubeDB" },
        { alg: "l' U l U l' U' l F U' F'", source: "SpeedCubeDB" },
        { alg: "F' U' L' U L2 F L' U' L' U L", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-15",
      name: "OLL 15",
      subset: "knight-shape",
      algs: [
        { alg: "r' U' r U' R' U R r' U r", source: "SpeedCubeDB" },
        { alg: "r' U' r R' U' R U r' U r", source: "SpeedCubeDB" },
        { alg: "U2 l' U' l L' U' L U l' U l", source: "SpeedCubeDB" },
        { alg: "r' U' M' U' R U r' U r", source: "SpeedCubeDB" },
        { alg: "U2 R' F' R L' U' L U R' F R", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-16",
      name: "OLL 16",
      subset: "knight-shape",
      algs: [
        { alg: "r U r' U R U' R' r U' r'", source: "SpeedCubeDB" },
        { alg: "r U r' R U R' U' r U' r'", source: "SpeedCubeDB" },
        { alg: "r U M U R' U' r U' r'", source: "SpeedCubeDB" },
        { alg: "U2 R' F R U R' U' F' R U' R' U2 R", source: "SpeedCubeDB" },
        { alg: "U2 l U l' L U L' U' l U' l'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-17",
      name: "OLL 17",
      subset: "dot",
      algs: [
        { alg: "F R' F' R U2' F R' F' R U' R U' R'", source: "SpeedCubeDB" },
        { alg: "R U R' U R' F R F' U2 R' F R F'", source: "SpeedCubeDB" },
        { alg: "U2 F R' F' R U S' R U' R' S", source: "SpeedCubeDB" },
        { alg: "U2 F R' F' R2 r' U R U' R' U' M'", source: "SpeedCubeDB" },
        { alg: "U' F' r U r' U' S r' F r S'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-18",
      name: "OLL 18",
      subset: "dot",
      algs: [
        { alg: "r' U2' R U R' U r2' U2' R' U' R U' r'", source: "SpeedCubeDB" },
        { alg: "U R U2 R' R' F R F' U2 M' U R U' r'", source: "SpeedCubeDB" },
        { alg: "U R U2 R2 F R F' U2 M' U R U' r'", source: "SpeedCubeDB" },
        { alg: "r U R' U R U2 r2 U' R U' R' U2 r", source: "SpeedCubeDB" },
        { alg: "U F S' R U' R' S R U2 R' U' F'", source: "SpeedCubeDB" },
        { alg: "R D r' U' r D' R' U' R2 F R F' R", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-19",
      name: "OLL 19",
      subset: "dot",
      algs: [
        { alg: "F R' F' R M U R U' R' U' M'", source: "SpeedCubeDB" },
        { alg: "M U R U R' U' M' R' F R F'", source: "SpeedCubeDB" },
        { alg: "U S' R U R' S U' R' F R F'", source: "SpeedCubeDB" },
        { alg: "R' U2 F R U R' U' F2 U2 F R", source: "SpeedCubeDB" },
        { alg: "r' R U R U R' U' r R2 F R F'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-20",
      name: "OLL 20",
      subset: "dot",
      algs: [
        { alg: "r U R' U' M2' U R U' R' U' M'", source: "SpeedCubeDB" },
        { alg: "r U R' U' M2 U R U' R' U' M'", source: "SpeedCubeDB" },
        { alg: "M' U2 M U2 M' U M U2 M' U2 M", source: "SpeedCubeDB" },
        { alg: "S' R U R' S U' M' U R U' r'", source: "SpeedCubeDB" },
        { alg: "S R' U' R U R U R U' R' S'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-21",
      name: "OLL 21",
      subset: "cross",
      algs: [
        { alg: "R U R' U R U' R' U R U2' R'", source: "SpeedCubeDB" },
        { alg: "R U R' U R U' R' U R U2 R'", source: "SpeedCubeDB" },
        { alg: "U R U2 R' U' R U R' U' R U' R'", source: "SpeedCubeDB" },
        { alg: "U F R U R' U' R U R' U' R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "R' U' R U' R' U R U' R' U2 R", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-22",
      name: "OLL 22",
      subset: "cross",
      algs: [
        { alg: "R' U2' R2' U R2' U R2' U2' R'", source: "SpeedCubeDB" },
        { alg: "R U2 R2' U' R2 U' R2' U' U' R", source: "SpeedCubeDB" },
        { alg: "R U2 R2 U' R2 U' R2 U2 R", source: "SpeedCubeDB" },
        { alg: "R' U2 R2 U R2 U R2 U2 R'", source: "SpeedCubeDB" },
        { alg: "f R U R' U' S' R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "f R U R' U' f' F R U R' U' F'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-23",
      name: "OLL 23",
      subset: "cross",
      algs: [
        { alg: "R U2' R D R' U2' R D' R2'", source: "SpeedCubeDB" },
        { alg: "R2 D R' U2 R D' R' U2 R'", source: "SpeedCubeDB" },
        { alg: "U2 R2 D' R U2 R' D R U2 R", source: "SpeedCubeDB" },
        { alg: "R U R' U R U2 R2 U' R U' R' U2 R", source: "SpeedCubeDB" },
        { alg: "U R U R' U' R U' R' U2 R U' R' U2 R U R'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-24",
      name: "OLL 24",
      subset: "cross",
      algs: [
        { alg: "F R' F' r U R U' r'", source: "SpeedCubeDB" },
        { alg: "r U R' U' r' F R F'", source: "SpeedCubeDB" },
        { alg: "U2 R' F' r U R U' r' F", source: "SpeedCubeDB" },
        { alg: "U' x' R U R' D R U' R' D' x", source: "SpeedCubeDB" },
        { alg: "U R U R D R' U' R D' R2", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-25",
      name: "OLL 25",
      subset: "cross",
      algs: [
        { alg: "R' F' r U R U' r' F", source: "SpeedCubeDB" },
        { alg: "U F' r U R' U' r' F R", source: "SpeedCubeDB" },
        { alg: "R U2 R D R' U2 R D' R2", source: "SpeedCubeDB" },
        { alg: "F R' F' r U R U' r'", source: "SpeedCubeDB" },
        { alg: "x R' U R D' R' U' R D x'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-26",
      name: "OLL 26",
      subset: "cross",
      algs: [
        { alg: "R U R' U R U2' R'", source: "SpeedCubeDB" },
        { alg: "U R U2 R' U' R U' R'", source: "SpeedCubeDB" },
        { alg: "R' U' R U' R' U2 R", source: "SpeedCubeDB" },
        { alg: "U2 L' U' L U' L' U2 L", source: "SpeedCubeDB" },
        { alg: "U2 L' U R U' L U R'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-27",
      name: "OLL 27",
      subset: "cross",
      algs: [
        { alg: "R U2' R' U' R U' R'", source: "SpeedCubeDB" },
        { alg: "R U R' U R U2 R'", source: "SpeedCubeDB" },
        { alg: "U' R' U2 R U R' U R", source: "SpeedCubeDB" },
        { alg: "U L' U2 L U L' U L", source: "SpeedCubeDB" },
        { alg: "U2 L U L' U L U2 L'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-28",
      name: "OLL 28",
      subset: "corners-oriented",
      algs: [
        { alg: "R U R' U' M' U R U' r'", source: "SpeedCubeDB" },
        { alg: "r U R' U' M U R U' R'", source: "SpeedCubeDB" },
        { alg: "R' F R S R' F' R S'", source: "SpeedCubeDB" },
        { alg: "r U R' U' r' R U R U' R'", source: "SpeedCubeDB" },
        { alg: "U2 M' U M U2 M' U M", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-29",
      name: "OLL 29",
      subset: "awkward-shape",
      algs: [
        { alg: "M F R' F' R U R U' R' U' M'", source: "SpeedCubeDB" },
        { alg: "U R U R' U' R U' R' F' U' F R U R'", source: "SpeedCubeDB" },
        { alg: "r2 D' r U r' D r2 U' r' U' r", source: "SpeedCubeDB" },
        { alg: "U S' R U R' U' R' F R F' U S", source: "SpeedCubeDB" },
        { alg: "M U R U R' U' R' F R F' M'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-30",
      name: "OLL 30",
      subset: "awkward-shape",
      algs: [
        { alg: "F U R U2' R' U R U2' R' U' F'", source: "SpeedCubeDB" },
        { alg: "U2 F U R U2 R' U' R U2 R' U' F'", source: "SpeedCubeDB" },
        { alg: "U' r' D' r U' r' D r2 U' r' U r U r'", source: "SpeedCubeDB" },
        { alg: "U2 F R' F R2 U' R' U' R U R' F2", source: "SpeedCubeDB" },
        { alg: "U S' R' U' R f R' U R U' F'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-31",
      name: "OLL 31",
      subset: "p-shape",
      algs: [
        { alg: "R' F R U R' U' F' U R", source: "SpeedCubeDB" },
        { alg: "R' U' F U R U' R' F' R", source: "SpeedCubeDB" },
        { alg: "U2 S' L' U' L U L F' L' f", source: "SpeedCubeDB" },
        { alg: "U S R U R' U' f' U' F", source: "SpeedCubeDB" },
        { alg: "U' F R' F' R U R U R' U' R U' R'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-32",
      name: "OLL 32",
      subset: "p-shape",
      algs: [
        { alg: "f R' F' R U R U' R' S'", source: "SpeedCubeDB" },
        { alg: "S R U R' U' R' F R f'", source: "SpeedCubeDB" },
        { alg: "U2 L U F' U' L' U L F L'", source: "SpeedCubeDB" },
        { alg: "R U B' U' R' U R B R'", source: "SpeedCubeDB" },
        { alg: "U' R' F R F' U' r U' r' U r U r'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-33",
      name: "OLL 33",
      subset: "t-shape",
      algs: [
        { alg: "F R' F' R U R U' R'", source: "SpeedCubeDB" },
        { alg: "R U R' U' R' F R F'", source: "SpeedCubeDB" },
        { alg: "U2 L' U' L U L F' L' F", source: "SpeedCubeDB" },
        { alg: "U2 r' F' r U r U' r' F", source: "SpeedCubeDB" },
        { alg: "R U R' F' U' F R U' R'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-34",
      name: "OLL 34",
      subset: "c-shape",
      algs: [
        { alg: "F U R' U' R' F' R U R2' U' R'", source: "SpeedCubeDB" },
        { alg: "U2 R U R2 U' R' F R U R U' F'", source: "SpeedCubeDB" },
        { alg: "U f R f' U' r' U' R U M'", source: "SpeedCubeDB" },
        { alg: "F R U R' U' R' F' r U R U' r'", source: "SpeedCubeDB" },
        { alg: "U2 R U R' U' B' R' F R F' B", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-35",
      name: "OLL 35",
      subset: "fish-shape",
      algs: [
        { alg: "R U2' R' F R' F' R2' U2' R'", source: "SpeedCubeDB" },
        { alg: "R U2 R' R' F R F' R U2 R'", source: "SpeedCubeDB" },
        { alg: "R U2 R2 F R F' R U2 R'", source: "SpeedCubeDB" },
        { alg: "f R U R' U' f' R U R' U R U2 R'", source: "SpeedCubeDB" },
        { alg: "R U2 R' d' R' F R U' R' F' R", source: "SpeedCubeDB" },
        { alg: "U L' U2 L2 F' L' F L' U2 L", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-36",
      name: "OLL 36",
      subset: "w-shape",
      algs: [
        { alg: "F' L F L' U' L' U' L U L' U L", source: "SpeedCubeDB" },
        { alg: "U2 L' U' L U' L' U L U L F' L' F", source: "SpeedCubeDB" },
        { alg: "U R U R2 F' U' F U R2 U2 R'", source: "SpeedCubeDB" },
        { alg: "U2 R U R' F' R U R' U' R' F R U' R' F R F'", source: "SpeedCubeDB" },
        { alg: "U2 R' F' U' F2 U R U' R' F' R", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-37",
      name: "OLL 37",
      subset: "fish-shape",
      algs: [
        { alg: "F R U' R' U R U R' F'", source: "SpeedCubeDB" },
        { alg: "F R U' R' U' R U R' F'", source: "SpeedCubeDB" },
        { alg: "F R' F' R U R U' R'", source: "SpeedCubeDB" },
        { alg: "U F' r U r' U' r' F r", source: "SpeedCubeDB" },
        { alg: "U2 r2 D' r U' r' D r U r", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-38",
      name: "OLL 38",
      subset: "w-shape",
      algs: [
        { alg: "F R' F' R U R U R' U' R U' R'", source: "SpeedCubeDB" },
        { alg: "R U R' U R U' R' U' R' F R F'", source: "SpeedCubeDB" },
        { alg: "U F R U' R' S U' R U R' f'", source: "SpeedCubeDB" },
        { alg: "r U R' U' r' F R U R U' R' F'", source: "SpeedCubeDB" },
        { alg: "U2 L U L' U L U' L' U' L' B L B'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-39",
      name: "OLL 39",
      subset: "lightning-bolt",
      algs: [
        { alg: "L U F' U' L' U L F L'", source: "SpeedCubeDB" },
        { alg: "U L F' L' U' L U F U' L'", source: "SpeedCubeDB" },
        { alg: "U' f' r U r' U' r' F r S", source: "SpeedCubeDB" },
        { alg: "U' R U R' F' U' F U R U2 R'", source: "SpeedCubeDB" },
        { alg: "U' f' L F L' U' L' U L S", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-40",
      name: "OLL 40",
      subset: "lightning-bolt",
      algs: [
        { alg: "R' U' F U R U' R' F' R", source: "SpeedCubeDB" },
        { alg: "U R' F R U R' U' F' U R", source: "SpeedCubeDB" },
        { alg: "U' f R' F' R U R U' R' S'", source: "SpeedCubeDB" },
        { alg: "R r D r' U r D' r' U' R'", source: "SpeedCubeDB" },
        { alg: "U' L' U' L F U F' U' L' U2 L", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-41",
      name: "OLL 41",
      subset: "awkward-shape",
      algs: [
        { alg: "F U R U' R' F' R U2' R' U' R U' R'", source: "SpeedCubeDB" },
        { alg: "U2 R U R' U R U2 R' F R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "U2 F U R2 D R' U' R D' R2 F'", source: "SpeedCubeDB" },
        { alg: "U' S U' R' F' U' F U R S'", source: "SpeedCubeDB" },
        { alg: "M U' F' L' U' L U F M'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-42",
      name: "OLL 42",
      subset: "awkward-shape",
      algs: [
        { alg: "F U R U' R' F' R' U2' R U R' U R", source: "SpeedCubeDB" },
        { alg: "R' U' R U' R' U2 R F R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "U F S' R U R' U' F' U S", source: "SpeedCubeDB" },
        { alg: "U R' F R F' R' F R F' R U R' U' R U R'", source: "SpeedCubeDB" },
        { alg: "U F R' F' R U2 R' U' R2 U' R2 U2 R", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-43",
      name: "OLL 43",
      subset: "p-shape",
      algs: [
        { alg: "f' U' L' U L f", source: "SpeedCubeDB" },
        { alg: "U R' U' F' U F R", source: "SpeedCubeDB" },
        { alg: "U2 F' U' L' U L F", source: "SpeedCubeDB" },
        { alg: "f' L' U' L U f", source: "SpeedCubeDB" },
        { alg: "B' U' R' U R B", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-44",
      name: "OLL 44",
      subset: "p-shape",
      algs: [
        { alg: "f U R U' R' f'", source: "SpeedCubeDB" },
        { alg: "f R U R' U' f'", source: "SpeedCubeDB" },
        { alg: "U2 F U R U' R' F'", source: "SpeedCubeDB" },
        { alg: "U R U B U' B' R'", source: "SpeedCubeDB" },
        { alg: "U' L U F U' F' L'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-45",
      name: "OLL 45",
      subset: "t-shape",
      algs: [
        { alg: "F U R U' R' F'", source: "SpeedCubeDB" },
        { alg: "F R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "U R' F' U' F U R", source: "SpeedCubeDB" },
        { alg: "U2 f U R U' R' f'", source: "SpeedCubeDB" },
        { alg: "U2 F' L' U' L U F", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-46",
      name: "OLL 46",
      subset: "c-shape",
      algs: [
        { alg: "R' U' F R' F' R U R", source: "SpeedCubeDB" },
        { alg: "R' U' R' F R F' U R", source: "SpeedCubeDB" },
        { alg: "R' F' U' F R U' R' U2 R", source: "SpeedCubeDB" },
        { alg: "U F R U R' U' F' U' R U R' U R U2 R'", source: "SpeedCubeDB" },
        { alg: "l' U2 L2 F' L' F U L' U l", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-47",
      name: "OLL 47",
      subset: "l-shape",
      algs: [
        { alg: "F' U' L' U L U' L' U L F", source: "SpeedCubeDB" },
        { alg: "F' L' U' L U L' U' L U F", source: "SpeedCubeDB" },
        { alg: "U' F R' F' R U2 R U' R' U R U2 R'", source: "SpeedCubeDB" },
        { alg: "R' U' R' F R F' R' F R F' U R", source: "SpeedCubeDB" },
        { alg: "U' R' F' U' F U F' U' F U R", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-48",
      name: "OLL 48",
      subset: "l-shape",
      algs: [
        { alg: "F U R U' R' U R U' R' F'", source: "SpeedCubeDB" },
        { alg: "F R U R' U' R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "U2 f U R U' R' U R U' R' f'", source: "SpeedCubeDB" },
        { alg: "R U2 R' U' R U R' U2 R' F R F'", source: "SpeedCubeDB" },
        { alg: "F R' F' U2 R U R' U R2 U2 R'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-49",
      name: "OLL 49",
      subset: "l-shape",
      algs: [
        { alg: "r' U r2' U' r2' U' r2' U r'", source: "SpeedCubeDB" },
        { alg: "U2 r U' r2 U r2 U r2 U' r", source: "SpeedCubeDB" },
        { alg: "l U' l2 U l2 U l2 U' l", source: "SpeedCubeDB" },
        { alg: "R B' R2 F R2 B R2 F' R", source: "SpeedCubeDB" },
        { alg: "U2 R' F R' F' R2 U2 B' R B R'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-50",
      name: "OLL 50",
      subset: "l-shape",
      algs: [
        { alg: "r U' r2' U r2' U r2' U' r", source: "SpeedCubeDB" },
        { alg: "r' U r2 U' r2 U' r2 U r'", source: "SpeedCubeDB" },
        { alg: "U2 R' F R2 B' R2 F' R2 B R'", source: "SpeedCubeDB" },
        { alg: "U' R U2 R' U' R U' R' F R U R' U' F'", source: "SpeedCubeDB" },
        { alg: "U2 l' U l2 U' l2 U' l2 U l'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-51",
      name: "OLL 51",
      subset: "i-shape",
      algs: [
        { alg: "f U R U' R' U R U' R' f'", source: "SpeedCubeDB" },
        { alg: "f R U R' U' R U R' U' f'", source: "SpeedCubeDB" },
        { alg: "U2 F U R U' R' U R U' R' F'", source: "SpeedCubeDB" },
        { alg: "U' R' U' R' F R F' R U' R' U2 R", source: "SpeedCubeDB" },
        { alg: "U r' F' U' F U F' U' F U r", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-52",
      name: "OLL 52",
      subset: "i-shape",
      algs: [
        { alg: "F R U R' d R' U' R U' R'", source: "SpeedCubeDB" },
        { alg: "U2 R' F' U' F U' R U R' U R", source: "SpeedCubeDB" },
        { alg: "R U R' U R U' B U' B' R'", source: "SpeedCubeDB" },
        { alg: "R U R' U R d' R U' R' F'", source: "SpeedCubeDB" },
        { alg: "R U R' U R U' y R U' R' F'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-53",
      name: "OLL 53",
      subset: "l-shape",
      algs: [
        { alg: "r' U2' R U R' U' R U R' U r", source: "SpeedCubeDB" },
        { alg: "r' U' R U' R' U R U' R' U2 r", source: "SpeedCubeDB" },
        { alg: "U2 l' U' L U' L' U L U' L' U2 l", source: "SpeedCubeDB" },
        { alg: "U r' U2 R U R' U' R U R' U r", source: "SpeedCubeDB" },
        { alg: "U' l' U2 L U L' U' L U L' U l", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-54",
      name: "OLL 54",
      subset: "l-shape",
      algs: [
        { alg: "r U2' R' U' R U R' U' R U' r'", source: "SpeedCubeDB" },
        { alg: "r U R' U R U' R' U R U2 r'", source: "SpeedCubeDB" },
        { alg: "U' r U2 R' U' R U R' U' R U' r'", source: "SpeedCubeDB" },
        { alg: "U' r U r' R U R' U' R U R' U' r U' r'", source: "SpeedCubeDB" },
        { alg: "U2 l U L' U L U' L' U L U2 l'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-55",
      name: "OLL 55",
      subset: "i-shape",
      algs: [
        { alg: "F R' F' U2' R U R' U R2' U2' R'", source: "SpeedCubeDB" },
        { alg: "R U2 R2 U' R U' R' U2 F R F'", source: "SpeedCubeDB" },
        { alg: "U R' F U R U' R2 F' R2 U R' U' R", source: "SpeedCubeDB" },
        { alg: "U R' F R U R U' R2 F' R2 U' R' U R U R'", source: "SpeedCubeDB" },
        { alg: "r U2 R2 F R F' U2 r' F R F'", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-56",
      name: "OLL 56",
      subset: "i-shape",
      algs: [
        { alg: "r U r' R U R' U' R U R' U' r U' r'", source: "SpeedCubeDB" },
        { alg: "r U r' U R U' R' U R U' R' r U' r'", source: "SpeedCubeDB" },
        { alg: "r U r' U R U' R' M' U R U2 r'", source: "SpeedCubeDB" },
        { alg: "F R U R' U' R F' r U R' U' r'", source: "SpeedCubeDB" },
        { alg: "r' U' r U' R' U R U' R' U R r' U r", source: "SpeedCubeDB" },
      ],
    },
    {
      id: "oll-57",
      name: "OLL 57",
      subset: "corners-oriented",
      algs: [
        { alg: "r U R' U' M U R U' R'", source: "SpeedCubeDB" },
        { alg: "R U R' U' M' U R U' r'", source: "SpeedCubeDB" },
        { alg: "U R U' R' S' R U R' S", source: "SpeedCubeDB" },
        { alg: "U R U R' S' R U' R' S", source: "SpeedCubeDB" },
        { alg: "R U R' U' R' r U R U' r'", source: "SpeedCubeDB" },
      ],
    },
  ],
});
