// ZBLS — algorithm case data for @moishy/algsets.
//
// ZBLS — solve the last slot while orienting last-layer edges (ZBLL setup).
// From the zbls Google Sheet
// (https://docs.google.com/spreadsheets/d/1s8Q2VM2c1eV3oLIxFfM4exvABO0AcCeMCUdMiYKnzC0).
// subset = the source's F2L case grouping (F2L 1..41).
//
// Authored per packages/algsets/AUTHORING.md — algs only; recognition/AUF/cost are derived.

import { type AlgSet, defineAlgSet } from "../define.ts";

export const zbls: AlgSet = defineAlgSet({
  id: "zbls",
  name: "ZBLS",
  cases: [
    { id: "f2l-1-1", subset: "F2L 1", algs: ["U R U' R'"] },
    { id: "f2l-1-2", subset: "F2L 1", algs: ["R' F R F'", "M' U R U' r'"] },
    {
      id: "f2l-1-3",
      subset: "F2L 1",
      algs: [
        "U2' R' F R F' R U2 R'",
        "U R B U' B' R'",
        "U R' F R F2 U F",
        "U2 F2 r U r' F",
        "y' U2' R2' F R F' R",
      ],
    },
    {
      id: "f2l-1-4",
      subset: "F2L 1",
      algs: ["R' U' F U R U' F'", "U F' L' U' L F", "U2 R U2 B U B' U' R'"],
    },
    {
      id: "f2l-1-5",
      subset: "F2L 1",
      algs: ["R' U' F U R2 U' R' F'", "U R U R' U2' R' F R F'", "U R U R' U2 M' U R U' r'"],
    },
    {
      id: "f2l-1-6",
      subset: "F2L 1",
      algs: ["M U R U' R' U' M'", "U S' R U' R' S", "U2 R U' B U' B' R'"],
    },
    { id: "f2l-1-7", subset: "F2L 1", algs: ["R' F R2 U R' U' F'", "U2 R U' R' U' R' F R F'"] },
    {
      id: "f2l-1-8",
      subset: "F2L 1",
      algs: ["M' U R U' r2 U2' R U R' U r", "y R' F' R U2 M' U' M", "U2 R' F R F' U2 R' F R F'"],
    },
    { id: "f2l-2-1", subset: "F2L 2", algs: ["y U' L' U L"] },
    { id: "f2l-2-2", subset: "F2L 2", algs: ["F R' F' R", "r U R' U' M"] },
    {
      id: "f2l-2-3",
      subset: "F2L 2",
      algs: ["U' r U' r' U r U r'", "U2 R2 B' R' B R'", "U2 l R U' R' U l'"],
    },
    {
      id: "f2l-2-4",
      subset: "F2L 2",
      algs: ["U' R B U B' R'", "d' F R U R' F'", "U2' R U R' U' R' F R F' R U' R'"],
    },
    { id: "f2l-2-5", subset: "F2L 2", algs: ["U R' D' r U' r' D R", "U' R2 D r' U r D' R2"] },
    { id: "f2l-2-6", subset: "F2L 2", algs: ["U' R' D' r U r' D R", "U' F2 r U r' U F"] },
    { id: "f2l-2-7", subset: "F2L 2", algs: ["R U2 R D r' U' r D' R2"] },
    { id: "f2l-2-8", subset: "F2L 2", algs: ["U' R U' R2' D' r U r' D R", "r U r' U2 M' U M"] },
    { id: "f2l-3-1", subset: "F2L 3", algs: ["y L' U' L"] },
    {
      id: "f2l-3-2",
      subset: "F2L 3",
      algs: ["S U R U' R' S'", "R U' R' F' r U' r' F2", "M y' R' U' R U S'"],
    },
    { id: "f2l-3-3", subset: "F2L 3", algs: ["F' r U' r' F2 R U' R'"] },
    { id: "f2l-3-4", subset: "F2L 3", algs: ["U' R' F R U R U' R2 F' R"] },
    { id: "f2l-3-5", subset: "F2L 3", algs: ["y' S' R' U' R S"] },
    { id: "f2l-3-6", subset: "F2L 3", algs: ["U R2 D r' U' r D' R2"] },
    { id: "f2l-3-7", subset: "F2L 3", algs: ["U2 R' D' r U' r' D R2 U' R'"] },
    { id: "f2l-3-8", subset: "F2L 3", algs: ["R' F R2 U' M' U2 r' U' F'"] },
    { id: "f2l-4-1", subset: "F2L 4", algs: ["R U R'"] },
    {
      id: "f2l-4-2",
      subset: "F2L 4",
      algs: ["U M U' R U R' M'", "R U2 R' U' R' F R F'", "R U R' F R U R' U' F'"],
    },
    { id: "f2l-4-3", subset: "F2L 4", algs: ["U' F' U2 F U R U' R'", "R U R' F U R U' R' F'"] },
    { id: "f2l-4-4", subset: "F2L 4", algs: ["U2 r U' r' U' r U r'", "R U' R' U2 R' F R F'"] },
    {
      id: "f2l-4-5",
      subset: "F2L 4",
      algs: ["R U R' U' F R U R' U' F'", "R U y R U R' U' F'", "S' R U R' S"],
    },
    {
      id: "f2l-4-6",
      subset: "F2L 4",
      algs: ["R U2 B U' B' R'", "U F U R U' R2' F' R", "R U R' U' r' U2 R U R' U r"],
    },
    { id: "f2l-4-7", subset: "F2L 4", algs: ["R U' R2' F R F' R U2' R'", "R U' R' F2 r U r' F"] },
    {
      id: "f2l-4-8",
      subset: "F2L 4",
      algs: [
        "R' D' r U' r' D R2 U R'",
        "R U' r' U r U2' r' U' r U2' R'",
        "R U' R2' F R F' U2 R' F R F'",
      ],
    },
    { id: "f2l-5-1", subset: "F2L 5", algs: ["U' R U R' U2 R U' R'"] },
    {
      id: "f2l-5-2",
      subset: "F2L 5",
      algs: ["U2 R U' R' U2 R U' R' U R' F R F'", "R U' R B2 r' U' r B' R2"],
    },
    {
      id: "f2l-5-3",
      subset: "F2L 5",
      algs: ["y' U r' U R U' R' U' r", "r U' r' U' r U r' F' r U' r' F2"],
    },
    { id: "f2l-5-4", subset: "F2L 5", algs: ["R' D' R U R' D F R F'"] },
    { id: "f2l-5-5", subset: "F2L 5", algs: ["U' R U R' U R' F R F'"] },
    { id: "f2l-5-6", subset: "F2L 5", algs: ["U' r U R' U' R2 r' U2 R'"] },
    {
      id: "f2l-5-7",
      subset: "F2L 5",
      algs: ["U' F R U R' U' F' R U2 R'", "U R U' R' U' R' F R F' R U R'"],
    },
    {
      id: "f2l-5-8",
      subset: "F2L 5",
      algs: ["U2 R2 D r' U' r D' R' U' R'", "U' r U' r' U2 r U r' U' R U' R'"],
    },
    { id: "f2l-6-1", subset: "F2L 6", algs: ["y' U R' U' R U R' U2' R", "y F2 R U R' U' F2"] },
    {
      id: "f2l-6-2",
      subset: "F2L 6",
      algs: [
        "U R U' R' y' U' R' U R U' R' U R",
        "U2' R' F' U' F U R2 U' R'",
        "R U R' U' R U R' U' F' U' F",
      ],
    },
    { id: "f2l-6-3", subset: "F2L 6", algs: ["U' r U' R' U R U r'"] },
    { id: "f2l-6-4", subset: "F2L 6", algs: ["R' D' F r U2 r' F D R"] },
    {
      id: "f2l-6-5",
      subset: "F2L 6",
      algs: ["y U L' U' L U' L F' L' F", "F R U' R' U' R U R' F2 U F"],
    },
    {
      id: "f2l-6-6",
      subset: "F2L 6",
      algs: ["U' R' F R F' R U2' R2' F R F'", "R2 D r' U' r D' R' U R'"],
    },
    {
      id: "f2l-6-7",
      subset: "F2L 6",
      algs: [
        "U2 y' R' F' U' F U2' R",
        "U' R' F2 R U' F U' R U2 R' F2",
        "U2 F' L' U' L U2' F",
        "U R U R2' F R F' r U' r' U' r U r'",
      ],
    },
    {
      id: "f2l-6-8",
      subset: "F2L 6",
      algs: [
        "U M' U M U2 r U R' U M",
        "U R U R D r' U' r D' R2' U' R U R'",
        "U R U' R' d' L' U L2 F' L' F",
      ],
    },
    { id: "f2l-7-1", subset: "F2L 7", algs: ["U' R U2 R' U2 R U' R'"] },
    {
      id: "f2l-7-2",
      subset: "F2L 7",
      algs: ["R U R' U R U' R2 F R F'", "U R' F R F' R U' R' U R U R'", "U R F U R U' R' F' R'"],
    },
    { id: "f2l-7-3", subset: "F2L 7", algs: ["R' D' R U2 R' D F R F'"] },
    {
      id: "f2l-7-4",
      subset: "F2L 7",
      algs: [
        "R' D' r U2 r' D F R F'",
        "y' R2' F R F' U R U2' R' U R",
        "F2 r U r' F R U R' U2 R U R'",
      ],
    },
    { id: "f2l-7-5", subset: "F2L 7", algs: ["U' R U2 R' U R' F R F'"] },
    {
      id: "f2l-7-6",
      subset: "F2L 7",
      algs: ["F R' F' R U2 R U' R' U R U' R'", "r' F' R2 U R' U2 R U' R2 F r"],
    },
    {
      id: "f2l-7-7",
      subset: "F2L 7",
      algs: ["U R U' R' U R' F R F' R U R'", "U' R B r' U r B2 U' R'"],
    },
    { id: "f2l-7-8", subset: "F2L 7", algs: ["M' U' M U2 r U' r'"] },
    { id: "f2l-8-1", subset: "F2L 8", algs: ["y' U R' U2 R U2 R' U R"] },
    {
      id: "f2l-8-2",
      subset: "F2L 8",
      algs: ["B' R' U' R2 U R' B", "U2 R U' R' F' U' F U' R U R'"],
    },
    {
      id: "f2l-8-3",
      subset: "F2L 8",
      algs: ["r' U2 R2 U R2' U r", "U2 r' D' r U r' D r2 U' R' U R U r'"],
    },
    {
      id: "f2l-8-4",
      subset: "F2L 8",
      algs: [
        "U R U' R' d R' U R U' R' U R",
        "r' U2 R2 U R' U' R' U2 r",
        "R l U' R' U F' l' U2 R U' R'",
      ],
    },
    {
      id: "f2l-8-5",
      subset: "F2L 8",
      algs: ["U y L' U2 L U' L F' L' F", "r' U2 R2 U R2' F' U F r"],
    },
    {
      id: "f2l-8-6",
      subset: "F2L 8",
      algs: [
        "F R' F' R U' R U R' U' F' U' F",
        "R2 D R' U' R r' U' r D' R' U R'",
        "x' R2 U' R' U F' l' U R' F R F'",
      ],
    },
    {
      id: "f2l-8-7",
      subset: "F2L 8",
      algs: [
        "U2 r' U r2 U' r2' U' r U2' r U r'",
        "U' r' F' r U r U' r2' F2 r F",
        "r' U2 R U R' U r2 U' R' U' R U r'",
      ],
    },
    { id: "f2l-8-8", subset: "F2L 8", algs: ["r U r' U' R U' M' U r'"] },
    {
      id: "f2l-9-1",
      subset: "F2L 9",
      algs: ["y' U2' R' U R U R' U' R", "U y' R' U' R U' R' U' R", "R' D' R U' R' D R F' U' F"],
    },
    { id: "f2l-9-2", subset: "F2L 9", algs: ["F R U R' U' F' R U' R'"] },
    { id: "f2l-9-3", subset: "F2L 9", algs: ["U' R U' R' d R' U' R", "F2 r U r' U' r' F r U' F"] },
    { id: "f2l-9-4", subset: "F2L 9", algs: ["U r U R' U' M R U' R'", "R' F R U2 r U2 r' U2 F'"] },
    {
      id: "f2l-9-5",
      subset: "F2L 9",
      algs: ["F R U R' U' F' U' R' F R F'", "M' U R2 r' U2 M' U r'"],
    },
    {
      id: "f2l-9-6",
      subset: "F2L 9",
      algs: ["U' r U2 r' U' r U' r' U r U2 r'", "U r U' r' U2' r U r' R U' R'"],
    },
    {
      id: "f2l-9-7",
      subset: "F2L 9",
      algs: ["U r U r' S' r U' r' S r U' r'", "R' F R2 U' R' U' r U2 r' U' F'"],
    },
    {
      id: "f2l-9-8",
      subset: "F2L 9",
      algs: [
        "U r U r' U2 M' U M R U' R'",
        "U2 R U R' U' R' F R F' R U2' R2' F R F'",
        "U2 R U R D r' U' r D' R' U R'",
        "R' F2 R2 U' R' U' R' F' R2 U R' F2",
      ],
    },
    { id: "f2l-10-1", subset: "F2L 10", algs: ["U' R U R' U R U R'"] },
    {
      id: "f2l-10-2",
      subset: "F2L 10",
      algs: ["F R' F' R U R' F R F' R U R'", "r' D' r U r' D R r U R'"],
    },
    { id: "f2l-10-3", subset: "F2L 10", algs: ["R U R2 F R F' R U R'", "U2' r U' R' U' R U r'"] },
    {
      id: "f2l-10-4",
      subset: "F2L 10",
      algs: [
        "U' r' D' r U' r' D r2 U' r' U' r U r'",
        "U' F' U' F r U' r' U' r U r'",
        "R' D2 r U' r2' D r D2 R",
        "R' F R F' U2' R U R' U' R U R'",
      ],
    },
    {
      id: "f2l-10-5",
      subset: "F2L 10",
      algs: ["U F R' F' R U2 R U' R'", "R U R' F' U F U R U' R'"],
    },
    {
      id: "f2l-10-6",
      subset: "F2L 10",
      algs: ["U2 R U' R' U r U' r' U' r U r'", "R B' R' U' R U B U2 R'"],
    },
    {
      id: "f2l-10-7",
      subset: "F2L 10",
      algs: ["U' R U R' U' r U' r' U' r U r'", "R' F' R U R U' R' F' r U r' F"],
    },
    {
      id: "f2l-10-8",
      subset: "F2L 10",
      algs: [
        "r U' r' U' r U r' U2' R' F R F'",
        "R U' R D r' U' r D' R' U' R'",
        "R' D' R U M' U r' D R2 U R'",
      ],
    },
    {
      id: "f2l-11-1",
      subset: "F2L 11",
      algs: ["y' R U2 R2 U' R2 U' R'", "R U2' R' U R U R' F' U' F"],
    },
    {
      id: "f2l-11-2",
      subset: "F2L 11",
      algs: ["U' R U R' U' R U' R' U' F' U' F", "R U' R' U R U' R2' F R F' R U' R'"],
    },
    { id: "f2l-11-3", subset: "F2L 11", algs: ["R U R' U' R U' R' F' U' F"] },
    { id: "f2l-11-4", subset: "F2L 11", algs: ["U' R U2 R' U F' U' F"] },
    { id: "f2l-11-5", subset: "F2L 11", algs: ["F' U r' F2 r U2 F"] },
    {
      id: "f2l-11-6",
      subset: "F2L 11",
      algs: [
        "R U2 R' U' r U' r' U2 r U r'",
        "r' U' R2 U' R2' U2' r F' U F",
        "R U' R' U' R U' R2' F R F2 U' F",
      ],
    },
    {
      id: "f2l-11-7",
      subset: "F2L 11",
      algs: ["F' L' U' L U' L' U L U' F", "R' D' r U r U R U' r2' D"],
    },
    {
      id: "f2l-11-8",
      subset: "F2L 11",
      algs: [
        "F R' F' R U' R U' R2 F R F'",
        "R U R' U2 R' F R F2 U' F",
        "R U' R' U y r' F2 r2 U' r' F",
      ],
    },
    { id: "f2l-12-1", subset: "F2L 12", algs: ["R U' R' U R U' R' U2 R U' R'"] },
    { id: "f2l-12-2", subset: "F2L 12", algs: ["R U' r' U R U' R' U' r U2 R'"] },
    {
      id: "f2l-12-3",
      subset: "F2L 12",
      algs: ["R U' R' U R U' R' U R' F R F'", "U r U' R' U' R U r' U' R U R'"],
    },
    { id: "f2l-12-4", subset: "F2L 12", algs: ["U F' U2 F U' R U R'"] },
    { id: "f2l-12-5", subset: "F2L 12", algs: ["R d' R U2 R' U2 F'"] },
    {
      id: "f2l-12-6",
      subset: "F2L 12",
      algs: ["R U M' U' M U2 M' U' r'", "U2 R' F2 r U r' F R2 U R'"],
    },
    { id: "f2l-12-7", subset: "F2L 12", algs: ["R U R' U R' F R F' R U R'"] },
    {
      id: "f2l-12-8",
      subset: "F2L 12",
      algs: ["R' D' R U2 M' U r' D R2 U R'", "R U2 R' U' M' U' M U2' r U' r'"],
    },
    {
      id: "f2l-13-1",
      subset: "F2L 13",
      algs: ["U y' R' U R U' R' U' R", "R' D' R U R' D R F' U' F"],
    },
    {
      id: "f2l-13-2",
      subset: "F2L 13",
      algs: ["R2 D R' U R D' R2 F' U' F", "U R U' R' U R U' R' U' y' R' U R"],
    },
    {
      id: "f2l-13-3",
      subset: "F2L 13",
      algs: ["M' U' R U R' U2 R U' r'", "R U' R' U R' F R F' R U' R'", "R U R' U R U' R' F' U' F"],
    },
    { id: "f2l-13-4", subset: "F2L 13", algs: ["R' F' r U R U2 r' F2"] },
    {
      id: "f2l-13-5",
      subset: "F2L 13",
      algs: [
        "R' D' r U r' D R U R U' R'",
        "R' F R F' U' R' F R F' R U R'",
        "U' S' U' R B U B' U2 R' U' S",
      ],
    },
    { id: "f2l-13-6", subset: "F2L 13", algs: ["M' U' R U' r' U2 r U' r'"] },
    {
      id: "f2l-13-7",
      subset: "F2L 13",
      algs: ["R' F R U2 r U' r' U2 F'", "U2' r U2' r' U' r U r' U r U2' r'"],
    },
    { id: "f2l-13-8", subset: "F2L 13", algs: ["U2 R U R D r' U r D' R' U R'"] },
    { id: "f2l-14-1", subset: "F2L 14", algs: ["U' R U' R' U R U R'"] },
    {
      id: "f2l-14-2",
      subset: "F2L 14",
      algs: [
        "U' R' F R2 U R' U' R' F' R",
        "r' D' r U' r' D r R U R'",
        "U F R U R' D R2 U' R2 D' F'",
      ],
    },
    { id: "f2l-14-3", subset: "F2L 14", algs: ["M' U' R U' R' U R U R' U' M"] },
    { id: "f2l-14-4", subset: "F2L 14", algs: ["U2 R U R' U R U2 R2 F R F'"] },
    { id: "f2l-14-5", subset: "F2L 14", algs: ["R U R' U' R' F R F' R U R'"] },
    {
      id: "f2l-14-6",
      subset: "F2L 14",
      algs: ["R U R' U' F' U' F U R U R'", "U2 r U R' U R U2 r' U R U' R'", "R B r' U r B2 U2' R'"],
    },
    {
      id: "f2l-14-7",
      subset: "F2L 14",
      algs: ["F' r U' r' F2 U' R U R'", "U' R U' R' U' r U' r' U' r U r'"],
    },
    {
      id: "f2l-14-8",
      subset: "F2L 14",
      algs: [
        "U2 r U' r' U M' U2' R U r'",
        "R' F R F' R U' R' U R U2' R2' F R F'",
        "U2 r U' r' U2 r U r' U R U R'",
        "U R2 D r' U r D' R2' U2' R U R'",
      ],
    },
    {
      id: "f2l-15-1",
      subset: "F2L 15",
      algs: [
        "R' D' R U' R' D R U R U' R'",
        "R U2 R' U R U R' U R U' R'",
        "R U R' U2 R U' R' U R U' R'",
      ],
    },
    { id: "f2l-15-2", subset: "F2L 15", algs: ["M U r U' r' U' M'", "F D R U R U' R2 D' F'"] },
    {
      id: "f2l-15-3",
      subset: "F2L 15",
      algs: ["F' U L' U L U2' F", "F' U F U2 R U R'", "U R' F R F' U R U R'"],
    },
    {
      id: "f2l-15-4",
      subset: "F2L 15",
      algs: [
        "R U2' R' U R U R2' F R F'",
        "R' D' R U' R' D F R F'",
        "U' R' F R F' R U R' U2' R U R'",
        "y' R2' F R F' R U2' R' U R",
      ],
    },
    { id: "f2l-15-5", subset: "F2L 15", algs: ["R U R' U2 R U' R2 F R F'"] },
    { id: "f2l-15-6", subset: "F2L 15", algs: ["R U2' R2' F R F' U' R U2' R'"] },
    { id: "f2l-15-7", subset: "F2L 15", algs: ["M U R U R' U' r U' R'"] },
    {
      id: "f2l-15-8",
      subset: "F2L 15",
      algs: [
        "l U r U' r2' F r U2 l'",
        "U R U' R D r' U r D' R' U' R'",
        "r' U' R U M' U' R' F U R U' F'",
      ],
    },
    {
      id: "f2l-16-1",
      subset: "F2L 16",
      algs: [
        "U M' U R U' r' U' R U R'",
        "r U r' U r U2 r' U' r U' r'",
        "U F R' F' R2 U' R' U R' F R F'",
        "F' U R U R' U R U2' R' F",
      ],
    },
    {
      id: "f2l-16-2",
      subset: "F2L 16",
      algs: ["R U R' U2' R U' R' U' F' U F", "U F R U R' U' F' U R U' R'", "y' M' U' r' U r U M"],
    },
    { id: "f2l-16-3", subset: "F2L 16", algs: ["F' U2 L' U' L U' F", "R U' R' U2 F' U' F"] },
    {
      id: "f2l-16-4",
      subset: "F2L 16",
      algs: ["U F U R U' R' F' R U R'", "l R U' R' U l' U2 R U' R'", "R' D' R U R' D R F R' F' R"],
    },
    {
      id: "f2l-16-5",
      subset: "F2L 16",
      algs: [
        "r U' r' U l' U2 R U' R' U2 l",
        "U2 r' F' r U' r' F2' r2 U' r' U2' r U r'",
        "U r U' r' U2 r U r' U r U' r' U' r U r'",
      ],
    },
    {
      id: "f2l-16-6",
      subset: "F2L 16",
      algs: ["U2 R' D' r U' M U' R' D R", "U r U' r' U2' r U r' U' R U R'"],
    },
    {
      id: "f2l-16-7",
      subset: "F2L 16",
      algs: ["F' U R U R' U' R' F2 R F'", "U2 R U R' r U' r' U2' r U r'"],
    },
    {
      id: "f2l-16-8",
      subset: "F2L 16",
      algs: [
        "U' r U' R' U' M U2 r U r'",
        "U R U2' R' r U' r' U2' r U r'",
        "U R U2 R' F' L' U2 L F",
        "R U' R2 D' r U' r' D R2 U' R'",
      ],
    },
    { id: "f2l-17-1", subset: "F2L 17", algs: ["R U2 R' U' R U R'"] },
    {
      id: "f2l-17-2",
      subset: "F2L 17",
      algs: ["F' U' F U R U' R' U R U' R'", "R U2' R' U r U' r' U' r U r'"],
    },
    { id: "f2l-17-3", subset: "F2L 17", algs: ["R U R' U' F R' F' R2 U R'"] },
    {
      id: "f2l-17-4",
      subset: "F2L 17",
      algs: [
        "F' U2' F R U R' U2 R U' R'",
        "y' M U' R' U2 R U' R' U R U2' M'",
        "R U l' U R' U' R U R' U' l",
        "B' R U' R U R' U' R2 U B",
      ],
    },
    {
      id: "f2l-17-5",
      subset: "F2L 17",
      algs: [
        "U R U2 R' U' R U R' U R' F R F'",
        "U' F R U R' U' F2 r U' r' F2",
        "U' R U2 R' U' F' U' F R U R'",
        "R U' R' U' F R' F' R U2 R U' R'",
      ],
    },
    { id: "f2l-17-6", subset: "F2L 17", algs: ["R U2 R' F U R U' R2 F' R"] },
    {
      id: "f2l-17-7",
      subset: "F2L 17",
      algs: ["R U' R' r U' R' U' R U r'", "R U' M' U' R' U' R U r'"],
    },
    {
      id: "f2l-17-8",
      subset: "F2L 17",
      algs: ["r' D' r U2' r' D r2 U' R' U2' R U r'", "F' r U' r' F2 R U2' R2 F R F'"],
    },
    {
      id: "f2l-18-1",
      subset: "F2L 18",
      algs: ["R' F R F' R U' R' U R U' R'", "y' R' U2 R U R' U' R"],
    },
    {
      id: "f2l-18-2",
      subset: "F2L 18",
      algs: ["R U' R' F' U' F U R U' R'", "R U R' d' L' U L U' L' U L"],
    },
    {
      id: "f2l-18-3",
      subset: "F2L 18",
      algs: [
        "R U' R' F' U F U R U R'",
        "U R U' R2' F R F' U R U' R'",
        "U R' F R F' R U' R' U F' U' F",
      ],
    },
    {
      id: "f2l-18-4",
      subset: "F2L 18",
      algs: ["R' F R F' R U' R2' F R F'", "R U R' U' R U2 R' F' U2 F"],
    },
    {
      id: "f2l-18-5",
      subset: "F2L 18",
      algs: [
        "r U R' U R U r' U M' U2 R U r'",
        "U' R2 D' r U' r' D r U R2 U' r'",
        "R' D' R U2 R' D R r U' r' U2' r U r'",
        "M' U2 r' F2 R U2 r U' r' U2 F",
        "R U2 R' r U r' U2 r U R' U R r'",
      ],
    },
    {
      id: "f2l-18-6",
      subset: "F2L 18",
      algs: ["R U' R2' F R F' r U' r' U' r U r'", "R' D R2 U2' r' U2 R U r D' R2"],
    },
    {
      id: "f2l-18-7",
      subset: "F2L 18",
      algs: [
        "R U R' d' r' F r2 U' r' F",
        "R U R' F' L' U2 L U' F",
        "R U' R D r' U' r D' R2' U' R U R'",
        "U F2 r U r' U F R U2 R'",
      ],
    },
    {
      id: "f2l-18-8",
      subset: "F2L 18",
      algs: ["F R' F' R2 U' R' U R U2' R2' F R F'", "F R U R' U' F' R U2' R2 F R F'"],
    },
    { id: "f2l-19-1", subset: "F2L 19", algs: ["U R U2 R' U R U' R'"] },
    {
      id: "f2l-19-2",
      subset: "F2L 19",
      algs: ["R' U R U' R2 F R2 U R' U' R F'", "U' R U' R' U r U' R' U2' R U r'"],
    },
    {
      id: "f2l-19-3",
      subset: "F2L 19",
      algs: [
        "U R' F R F' R U' R' U2 R U' R'",
        "F' U R U R' U' R' F R2 U R'",
        "U R U2' r' U R U' R' U' M'",
      ],
    },
    {
      id: "f2l-19-4",
      subset: "F2L 19",
      algs: [
        "F' U' F U2 R U' R' U R U' R'",
        "U' r U' R' U' R U r' U R U' R'",
        "U R U2' R' U R U R' U2' R' F R F'",
      ],
    },
    {
      id: "f2l-19-5",
      subset: "F2L 19",
      algs: [
        "U' l R U' R' U x U' R' U2 R U R'",
        "U F R' F' R r U' R' U R U r'",
        "F R' F' R2 U2 R' U2 R U R'",
      ],
    },
    { id: "f2l-19-6", subset: "F2L 19", algs: ["U F R U R' U' F' R U R'"] },
    { id: "f2l-19-7", subset: "F2L 19", algs: ["U R U2 R2 F R F'"] },
    {
      id: "f2l-19-8",
      subset: "F2L 19",
      algs: ["U2 R U R2' r U' M U2' r U' r'", "R' U' F' U F2 R2 U R' U' R' F' R"],
    },
    { id: "f2l-20-1", subset: "F2L 20", algs: ["y' U' R' U2 R U' R' U R y"] },
    {
      id: "f2l-20-2",
      subset: "F2L 20",
      algs: [
        "R' U' R' F R F' U R2 U' R'",
        "U2' r U' R' U R U r' F' U' F",
        "x R' U R U' R' U R U2' x' U' F",
        "U2' R U' R' U F' r U' r' F2'",
      ],
    },
    {
      id: "f2l-20-3",
      subset: "F2L 20",
      algs: [
        "U' R U' R' U R U' R' d R' U R",
        "R' F2 r U2 R U' r2' F r F",
        "S R U2 R' U' R U R' U S'",
      ],
    },
    { id: "f2l-20-4", subset: "F2L 20", algs: ["U' R U' R2 F R F' R U' R'"] },
    {
      id: "f2l-20-5",
      subset: "F2L 20",
      algs: ["R' F2 R U' F U R' F2 R", "U' r U' r' U2 r U r' R U R' U R U' R'"],
    },
    {
      id: "f2l-20-6",
      subset: "F2L 20",
      algs: [
        "r' D' r U r' D r2 U' r' U2' r U r'",
        "U' R U' r' U r U2' r' U' r U R'",
        "F D R2 U' R' U2 R U R2 D' F'",
      ],
    },
    { id: "f2l-20-7", subset: "F2L 20", algs: ["U' F' U' r U' r' F2", "y U' L' U2 L2 F' L' F"] },
    {
      id: "f2l-20-8",
      subset: "F2L 20",
      algs: [
        "U' R U' R2' F R F' U' R' F R F'",
        "U' R U R' U r U' r' U2 r U r'",
        "U2 R U' R' U' r U' r' U2 r U r'",
        "U R U' R2 F R F2 U' F",
      ],
    },
    { id: "f2l-21-1", subset: "F2L 21", algs: ["U2 R U R' U R U' R'"] },
    { id: "f2l-21-2", subset: "F2L 21", algs: ["U R' F R F' U' R U2 R'", "U2 F' U' F R U R'"] },
    { id: "f2l-21-3", subset: "F2L 21", algs: ["U2' R U R2' F R F'", "U2 R B' R B R2"] },
    {
      id: "f2l-21-4",
      subset: "F2L 21",
      algs: [
        "U R U' R' U2 R U' R2' F R F'",
        "R U R' U' F' U F R U R'",
        "U2 F' r U R' U' r' F2 R F'",
      ],
    },
    { id: "f2l-21-5", subset: "F2L 21", algs: ["r U' R' U2 R U r'"] },
    { id: "f2l-21-6", subset: "F2L 21", algs: ["U2 F R U R' U' F' U' R U2 R'"] },
    {
      id: "f2l-21-7",
      subset: "F2L 21",
      algs: [
        "U F R' F' R2 U' R' U R U R'",
        "U2' R U r' U R U' R' U' M'",
        "r' U2 R' U R2 U' R U2 r",
      ],
    },
    {
      id: "f2l-21-8",
      subset: "F2L 21",
      algs: [
        "U2' F' r' F2 r2 U' r' F2",
        "U R' F R F2 U' F R U2 R'",
        "U M' U R U' r' U R U R2' F R F'",
      ],
    },
    {
      id: "f2l-22-1",
      subset: "F2L 22",
      algs: ["y' R' U R U2 R' U' R y", "U2 R' F R F' R U R' U R U' R'"],
    },
    { id: "f2l-22-2", subset: "F2L 22", algs: ["U2' R U R' F' U' F", "y' R' F' U F U R y"] },
    { id: "f2l-22-3", subset: "F2L 22", algs: ["U2 F' r U' r' F2"] },
    {
      id: "f2l-22-4",
      subset: "F2L 22",
      algs: ["U R U' R' U' R U' R' y' R' U' R", "R2 U2 R2 F R F' R U2 R2"],
    },
    { id: "f2l-22-5", subset: "F2L 22", algs: ["r U' r' U2' r U r'", "F' L' U2 L F"] },
    {
      id: "f2l-22-6",
      subset: "F2L 22",
      algs: ["U2 R' F R F2 U' F R U R'", "U' r U' r' U' r U r' F' U' F"],
    },
    {
      id: "f2l-22-7",
      subset: "F2L 22",
      algs: ["U2' R' F R F' R U R2' F R F'", "r U' r' U2 y' R U R U' R' y"],
    },
    {
      id: "f2l-22-8",
      subset: "F2L 22",
      algs: [
        "U' R U2 r' U r U2 r' U' r U R'",
        "U' F R' F' R U2' r U' r' U r U r'",
        "M' U R U' r' F2 r U r' U2 F",
      ],
    },
    {
      id: "f2l-23-1",
      subset: "F2L 23",
      algs: ["U2 R2 U2' R' U' R U' R2'", "R U' R2' D' R U2 R' D R"],
    },
    {
      id: "f2l-23-2",
      subset: "F2L 23",
      algs: ["U2 R U2 R' U' R U' R2 F R F'", "U2 R U R' U' R U' R' U R' F R F'"],
    },
    {
      id: "f2l-23-3",
      subset: "F2L 23",
      algs: ["U R U' R' U' R U' R2' F R F'", "F' U' F U' R U' R' U R U' R'"],
    },
    {
      id: "f2l-23-4",
      subset: "F2L 23",
      algs: ["U R' F R F' R U R' U2 R U' R'", "F U R U' R' F' U' F' U' F"],
    },
    { id: "f2l-23-5", subset: "F2L 23", algs: ["U F R' F' R U R U R'", "R U R' F' U F R U R'"] },
    {
      id: "f2l-23-6",
      subset: "F2L 23",
      algs: ["R U2' R' U r U' R' U' R U r'", "R U2 R' F' U F U' R U R'"],
    },
    {
      id: "f2l-23-7",
      subset: "F2L 23",
      algs: [
        "U2 r U' r' U r U r' U R U' R'",
        "M U2 R U R' U r U' R'",
        "U2' r U' r' U r U r' U R U' R'",
      ],
    },
    {
      id: "f2l-23-8",
      subset: "F2L 23",
      algs: [
        "U F R' F' R U S' R U R' S",
        "F' U' F U' R U' R2' F R F'",
        "U' R' F R F' U2' R U' R' U R' F R F'",
        "U F R' F' R2 r' U R U R' U' M'",
        "U' F2 r U r' U' r' F' r2 U' r' F2",
      ],
    },
    { id: "f2l-24-1", subset: "F2L 24", algs: ["U' R U R2' F R F' R U' R'"] },
    { id: "f2l-24-2", subset: "F2L 24", algs: ["R U' R' U r U' R' U R U r'"] },
    {
      id: "f2l-24-3",
      subset: "F2L 24",
      algs: [
        "R U R' d R' U R U' R' U R",
        "y U' L' U L U L' U L2 F' L' F",
        "R U' R2 F' U' F U R2 U' R'",
        "U' R U R' U R U' l U' R' U R'",
        "U F' r' F r F R U R'",
      ],
    },
    { id: "f2l-24-4", subset: "F2L 24", algs: ["F U R U' R' F' R U' R'"] },
    {
      id: "f2l-24-5",
      subset: "F2L 24",
      algs: ["U' R U' R' U r U' r' U2' r U r'", "F U R U' R' F2 U' F R U' R'"],
    },
    {
      id: "f2l-24-6",
      subset: "F2L 24",
      algs: [
        "y' R' U' R' F R F' U2 R",
        "r U' r' U' r U r2' D' r U2' r' D r",
        "r U R' U R U r' U' r U r'",
        "r U' r' U' r U r' F' U2' F",
      ],
    },
    {
      id: "f2l-24-7",
      subset: "F2L 24",
      algs: [
        "y' M' U2 R' U' R U' r' U R",
        "U r U' r' U2' r U r' R U2' R' U R U' R'",
        "F' U' r U2 R' U' R U' r' U2' F",
        "U2 R' F R y' R U2' R U R' U R2",
        "U' R U' R' F' L' U' L U' F",
        "U' F' U r' F r U r' F r U' F",
      ],
    },
    {
      id: "f2l-24-8",
      subset: "F2L 24",
      algs: [
        "R U' R2 D' r U r' R U R' D R",
        "R U R' d R' U R l U' R' U x",
        "R U R' U2 F' r' F2 r U' F",
        "U2 R U R' U' r U2' r' U' r U' r' U r U2' r'",
      ],
    },
    {
      id: "f2l-25-1",
      subset: "F2L 25",
      algs: ["R' F' R U R U' R' F", "U' F' R U R' U' R' F R", "R' U' R' U' R' U R U R"],
    },
    { id: "f2l-25-2", subset: "F2L 25", algs: ["U' M' U R U' r' R U R'", "U' R' F R F' R U R'"] },
    { id: "f2l-25-3", subset: "F2L 25", algs: ["U' F' U F U R U' R'", "L D R' F R F' D' L'"] },
    {
      id: "f2l-25-4",
      subset: "F2L 25",
      algs: ["U' F' U' F U R U R'", "R2' U R U' R' U F R2 F' R'"],
    },
    {
      id: "f2l-25-5",
      subset: "F2L 25",
      algs: ["r U r' U2 r U R' U2 R U' r'", "F2 r U2 R' U' r' F2 R F'"],
    },
    {
      id: "f2l-25-6",
      subset: "F2L 25",
      algs: ["U2 r U2' R' U R U' R' U2' R U' r'", "r' U' R' U' R' U R U r"],
    },
    {
      id: "f2l-25-7",
      subset: "F2L 25",
      algs: [
        "U2 r U' r' R U' R' U' r U' r'",
        "U r U r' U R U M' U r'",
        "U2 F' L' U' L U R U R' U' R' F R",
      ],
    },
    {
      id: "f2l-25-8",
      subset: "F2L 25",
      algs: ["U R2 D r' U r D' R' U' R'", "r U r' U2 r U R' U' R U2 r'"],
    },
    {
      id: "f2l-26-1",
      subset: "F2L 26",
      algs: [
        "L E' L' U L E L'",
        "U2 L E' L' U' L E L'",
        "U2 R U' R' U' r U' R' U R U r'",
        "r2 U2' R2' F R2 U2' r2' F",
      ],
    },
    {
      id: "f2l-26-2",
      subset: "F2L 26",
      algs: ["U R U' R' F R' F' R", "U R U' M' U R' U' M", "R2 U R' U' R' F R F' R'"],
    },
    { id: "f2l-26-3", subset: "F2L 26", algs: ["U R U' R' U' F' U F"] },
    { id: "f2l-26-4", subset: "F2L 26", algs: ["U R U R' U' y' R' U' R", "F U' r U M U' R' U F'"] },
    {
      id: "f2l-26-5",
      subset: "F2L 26",
      algs: ["r U R' U2 R U r' U2 r U' r'", "R' D' R U M' U' r' D R"],
    },
    {
      id: "f2l-26-6",
      subset: "F2L 26",
      algs: [
        "r U r' U2' r U' R' U2' R U' r'",
        "R' D' R U' M' U r' D R",
        "y' r U R U R U' R' U' r'",
      ],
    },
    {
      id: "f2l-26-7",
      subset: "F2L 26",
      algs: ["r U2' B U' B' U2' r'"],
    },
    {
      id: "f2l-26-8",
      subset: "F2L 26",
      algs: ["r U2 R' U R U' r' U2 r U' r'", "U R U R D r' U' r D' R2'"],
    },
    { id: "f2l-27-1", subset: "F2L 27", algs: ["R U' R' U R U' R'"] },
    { id: "f2l-27-2", subset: "F2L 27", algs: ["R U' R2 F R2 U R' U' F'"] },
    {
      id: "f2l-27-3",
      subset: "F2L 27",
      algs: [
        "R' F2 r U' R U r' F2",
        "R' D' R U' R' D R U R' F R F'",
        "R' D' R U R' D R U' R' F R F'",
      ],
    },
    { id: "f2l-27-4", subset: "F2L 27", algs: ["R U' r' U R U' R' U' M'"] },
    { id: "f2l-27-5", subset: "F2L 27", algs: ["R U' R2 F R F'"] },
    {
      id: "f2l-27-6",
      subset: "F2L 27",
      algs: [
        "U2 r U' r' U r U r' R U2' R'",
        "R U' R2 U' F U R2 U' R' F'",
        "R U' R' U R U R' U2' R' F R F'",
      ],
    },
    {
      id: "f2l-27-7",
      subset: "F2L 27",
      algs: ["R U' R2 U' F U R U' F'", "U2 R U R' U R U R2' F R F'"],
    },
    {
      id: "f2l-27-8",
      subset: "F2L 27",
      algs: ["U' R U' R2 r U' M U2 r U' r'", "R U' R' y R' F' R U2 M' U' M"],
    },
    { id: "f2l-28-1", subset: "F2L 28", algs: ["y' R' U R U' R' U R y"] },
    {
      id: "f2l-28-2",
      subset: "F2L 28",
      algs: ["R U R' d R' U2 R", "R U R' r' D' r U' r' D r", "F U R U' R2 F' R2 U R'"],
    },
    { id: "f2l-28-3", subset: "F2L 28", algs: ["R U2 l U' R' U l'"] },
    {
      id: "f2l-28-4",
      subset: "F2L 28",
      algs: ["R U2 R' y' R' U2 R y", "U2 R' F R F' r U' r' U2' r U r'"],
    },
    { id: "f2l-28-5", subset: "F2L 28", algs: ["y r' F r2 U' r' F", "F' U2' r U' r' F2"] },
    {
      id: "f2l-28-6",
      subset: "F2L 28",
      algs: ["R U2 R' U R2 D r' U r D' R2'", "R U R' F R U R' U' F2 U' F"],
    },
    {
      id: "f2l-28-7",
      subset: "F2L 28",
      algs: [
        "y L' U L U' F R U R' F'",
        "R U2 R' U' F R U R' U' F2 U' F",
        "R U' R' r U' R' U' R r' U' r U r'",
      ],
    },
    {
      id: "f2l-28-8",
      subset: "F2L 28",
      algs: ["U r U r' U2 M' U M R U R'", "R U2' R2' F R F2 U2' F"],
    },
    {
      id: "f2l-29-1",
      subset: "F2L 29",
      algs: ["y' R' U' R U R' U' R", "R' F R F' U R U' R'", "M' U R U' r' U R U' R'"],
    },
    { id: "f2l-29-2", subset: "F2L 29", algs: ["U2 R U' R' F' U' F"] },
    { id: "f2l-29-3", subset: "F2L 29", algs: ["R' F R F' R' F R F'", "x R' U R U' R' U R U' x'"] },
    {
      id: "f2l-29-4",
      subset: "F2L 29",
      algs: [
        "R' F R F' U R U R' U2' R' F R F'",
        "U' F R' F' R2 U' R2' D' R U2 R' D R",
        "U2 R U' R' U' R' F R U R U' R2' F' R",
        "R U' R2' D' r U' r' D F R F'",
        "r U2 R' U' R U' r' R U' R' U R U' R'",
      ],
    },
    { id: "f2l-29-5", subset: "F2L 29", algs: ["U R' F R F2 U' F"] },
    {
      id: "f2l-29-6",
      subset: "F2L 29",
      algs: [
        "U R2 D r' U' r D' R2' U' R U2 R'",
        "F' r2 D2 r' U r D2 r' U2 r' F2",
        "U2 r U' r' U2 r U r' U' R U2 R' U R U R'",
      ],
    },
    { id: "f2l-29-7", subset: "F2L 29", algs: ["U' R U R' U' r U' r' U2 r U r'"] },
    { id: "f2l-29-8", subset: "F2L 29", algs: ["M' U' M U2 r U' R' U R U' r'"] },
    { id: "f2l-30-1", subset: "F2L 30", algs: ["R U R' U' R U R'"] },
    { id: "f2l-30-2", subset: "F2L 30", algs: ["U2' F' U F R U R'", "R U R' F U R U' R2 F' R"] },
    { id: "f2l-30-3", subset: "F2L 30", algs: ["x U R' U' R U R' U' l"] },
    { id: "f2l-30-4", subset: "F2L 30", algs: ["U2 R' F R F' R U' R' U2 R U R'"] },
    { id: "f2l-30-5", subset: "F2L 30", algs: ["U' F R' F' R2 U R'"] },
    { id: "f2l-30-6", subset: "F2L 30", algs: ["R U r' U' R U R2 r"] },
    { id: "f2l-30-7", subset: "F2L 30", algs: ["R U R' U r U' r' U' r U r'"] },
    {
      id: "f2l-30-8",
      subset: "F2L 30",
      algs: [
        "R U R' U' R' D' r U r' D R2 U R'",
        "r U R' U' R U r' U2' M' U M",
        "U' F' U2 r' F r2 U' r' F2",
      ],
    },
    { id: "f2l-31-1", subset: "F2L 31", algs: ["R U' R' U F' U F", "R U' R' U y' R' U R y"] },
    { id: "f2l-31-2", subset: "F2L 31", algs: ["U' R' F R F' R U' R'"] },
    { id: "f2l-31-3", subset: "F2L 31", algs: ["R U2 R' U' F R' F' R"] },
    { id: "f2l-31-4", subset: "F2L 31", algs: ["F' U F R U2' R'", "R' F' R U R U' R' U2 F"] },
    { id: "f2l-31-5", subset: "F2L 31", algs: ["r U' r' U M' U R U r'"] },
    {
      id: "f2l-31-6",
      subset: "F2L 31",
      algs: ["U' R' F R F' U' R' F R F'", "F2 r U r' U2 F R U' R'"],
    },
    { id: "f2l-31-7", subset: "F2L 31", algs: ["R U2 R2 D' r U' r' D R"] },
    { id: "f2l-31-8", subset: "F2L 31", algs: ["r U' R' U' M U' r U r'"] },
    { id: "f2l-32-1", subset: "F2L 32", algs: ["U R U' R' U R U' R' U R U' R'"] },
    {
      id: "f2l-32-2",
      subset: "F2L 32",
      algs: [
        "U' F' U L' U2 L U' F",
        "U2 r U S' r' U r S U' r'",
        "U2 R U r' U R U R' U' r U' R'",
        "R U' R2 F2 r U r' F R2 U R'",
        "U R U' R' U R U' r' U R U' R' U' M'",
      ],
    },
    { id: "f2l-32-3", subset: "F2L 32", algs: ["U R U' R' U R U' R2 F R F'"] },
    { id: "f2l-32-4", subset: "F2L 32", algs: ["U' R U R' U' R U R2 F R F'"] },
    {
      id: "f2l-32-5",
      subset: "F2L 32",
      algs: ["U R' F R F' d R' U' R", "U2 F' U r' F' r U' F", "U2 R' F R F2 r U' r' F2"],
    },
    {
      id: "f2l-32-6",
      subset: "F2L 32",
      algs: [
        "U2 R U' f R f' U R'",
        "U' F R' F' R U' R U R'",
        "U' r U r' R' F R F' r U' r'",
        "r U' R2 U' R U' R' U2 R2 U r'",
      ],
    },
    {
      id: "f2l-32-7",
      subset: "F2L 32",
      algs: [
        "U2 F R' F' R2 U R' U R U' R'",
        "U2 R U2 R' U2 R U' R2 F R F'",
        "R U R' U F' U F R U R'",
      ],
    },
    {
      id: "f2l-32-8",
      subset: "F2L 32",
      algs: [
        "U2' r U2' r' U2 r U' r' U2 r U2' r'",
        "U2' R' F R F' U2' r U' r' U2' r U r'",
        "y U2 R' F2 R U2' R' F R U2' R' F2 R",
        "r U M U2 r R2' U2' R U r'",
      ],
    },
    { id: "f2l-33-1", subset: "F2L 33", algs: ["U' R U' R' U2 R U' R'"] },
    { id: "f2l-33-2", subset: "F2L 33", algs: ["R U M U' R' U r U' R'"] },
    {
      id: "f2l-33-3",
      subset: "F2L 33",
      algs: [
        "U' R U' R' U2' R U R' U2' R' F R F'",
        "R' F R F' R2 U R' U' R' F R F' R'",
        "r2 D r2 U' R2 r' U r2 D' R2 r'",
      ],
    },
    { id: "f2l-33-4", subset: "F2L 33", algs: ["U R U' R2 F R F' R U R'"] },
    {
      id: "f2l-33-5",
      subset: "F2L 33",
      algs: ["U r U' r' U r U r' R U' R'", "M' U' R U r' U2 r U' r'"],
    },
    {
      id: "f2l-33-6",
      subset: "F2L 33",
      algs: ["U' R U' R' U R' F R F'", "U' R U' R' U M' U R U' r'"],
    },
    {
      id: "f2l-33-7",
      subset: "F2L 33",
      algs: ["y U2 F R U2 R' U2 F'", "R U R' U' F' U' F U' R U2 R'", "U' F' U2 L' U2 L F"],
    },
    {
      id: "f2l-33-8",
      subset: "F2L 33",
      algs: ["U' F R' F' R2 U2' R2' F R F'", "D' r U' r' F2 U R' F R F2 D"],
    },
    { id: "f2l-34-1", subset: "F2L 34", algs: ["U R' D' R U' R' D R", "U' R' D' R U R' D R"] },
    { id: "f2l-34-2", subset: "F2L 34", algs: ["U' R U' R' F' U' F R U2 R'"] },
    {
      id: "f2l-34-3",
      subset: "F2L 34",
      algs: [
        "U R U' R' F R' F' R2 U R'",
        "U' R U2' R' U' r U' r' U' r U r'",
        "R U' R' U' R' F R F' U R U R'",
        "r U r' U R U2 R' U r U' r'",
      ],
    },
    {
      id: "f2l-34-4",
      subset: "F2L 34",
      algs: [
        "U r U' R' U R U r' U' R U R'",
        "y' U R2' F R F' R U' R' U R",
        "U R U' R' U' F' U F R U R'",
        "F U R2 D2 R' U' R D2 R2 F'",
      ],
    },
    {
      id: "f2l-34-5",
      subset: "F2L 34",
      algs: ["y U L' U L U' L F' L' F", "U r U R' U' M U' R U R'", "r' D' r U2 r' U' F2 U F2 D r"],
    },
    {
      id: "f2l-34-6",
      subset: "F2L 34",
      algs: ["U R U M' U' r' U' r U r'", "F U' R2 D2 R' U' R D2 R2 U F'"],
    },
    {
      id: "f2l-34-7",
      subset: "F2L 34",
      algs: ["R U R' U2 R' F R F' R U R'", "U2 R U' R' U r U' R' U' R U r'"],
    },
    {
      id: "f2l-34-8",
      subset: "F2L 34",
      algs: ["U r U2' r' U2' r U r' U2' r U2' r'", "R U R D r' U r D' R' U' R'"],
    },
    {
      id: "f2l-35-1",
      subset: "F2L 35",
      algs: ["U2' R U R' y' U' R' U R", "R' D' r U' r' D F R F'"],
    },
    {
      id: "f2l-35-2",
      subset: "F2L 35",
      algs: [
        "U' R U R' d R' U' R",
        "U M' U R U' M U' R'",
        "R U R2 F R F' R' F R F'",
        "R U R' l' U R U' R' U R U' x'",
      ],
    },
    {
      id: "f2l-35-3",
      subset: "F2L 35",
      algs: ["U2 R U' R' U' F' U' F", "R U R2 F R F' U R U' R'"],
    },
    {
      id: "f2l-35-4",
      subset: "F2L 35",
      algs: ["U2' R U R' F R' F' R", "R2 D R' U2 R D' R2 F' U' F"],
    },
    {
      id: "f2l-35-5",
      subset: "F2L 35",
      algs: ["R2 D r' U' r D' R2 U R U' R'", "U2 r U' r' U R' F R F' r U2' r'"],
    },
    { id: "f2l-35-6", subset: "F2L 35", algs: ["U2 R U' R D r' U' r D' R2"] },
    { id: "f2l-35-7", subset: "F2L 35", algs: ["R' D' r U' r' D R U R U' R'"] },
    {
      id: "f2l-35-8",
      subset: "F2L 35",
      algs: ["U R' D' r U r' D R2 U2' R'", "R' F R F' U2' R' F R F' R U R'"],
    },
    { id: "f2l-36-1", subset: "F2L 36", algs: ["U F' U' F U' R U R'"] },
    {
      id: "f2l-36-2",
      subset: "F2L 36",
      algs: ["U2 F' U' F U R U' R'", "R U R' U R U' R' d' r' F r", "R U R' F U2' r U r' U2' F'"],
    },
    {
      id: "f2l-36-3",
      subset: "F2L 36",
      algs: ["U2' R' F R F' U2 R U R'", "R U R' F R S R' F' R S' R'", "R U R2 U' R F' R' U R F"],
    },
    {
      id: "f2l-36-4",
      subset: "F2L 36",
      algs: ["F' U' F R U R' U' R U R'", "R U R U R' U' R' F R F' R'"],
    },
    { id: "f2l-36-5", subset: "F2L 36", algs: ["R2 D r' U r D' R' U R'"] },
    { id: "f2l-36-6", subset: "F2L 36", algs: ["U2 R' F R F' r U' r' U' r U r'"] },
    {
      id: "f2l-36-7",
      subset: "F2L 36",
      algs: [
        "U2 R2 D r' U' r D' R2' U' R U R'",
        "R' F' r U2 r' F2 R2 U2' R' U' F",
        "F' U2' r' F2 r2 U' r' F U' F",
        "R2 D R' U2 R r' U' r D' R' U R'",
      ],
    },
    {
      id: "f2l-36-8",
      subset: "F2L 36",
      algs: [
        "R U M' U2 f R f' U2 r'",
        "U F' U' F2 U R U' R2' F' R",
        "R U R2' D' r U r' D R U' R U R'",
        "R U R2' D' r U' r' D R U R U R'",
        "R' F2 D' F' D R U R U' R2 F' R",
      ],
    },
    {
      id: "f2l-37-1",
      subset: "F2L 37",
      algs: [
        "U' R' F R F' R U' R' U R U' R' U2 R U' R'",
        "U' R' F R F' R' U2' R2 U R2' U R",
        "R U M' U2 M U R' F' R S R' F R S' R'",
        "U L E' L' U' L E L2' E2 L U L' E2 L",
        "U' L E' L' U L E L2' E2 L U' L' E2 L",
        "U R2 U R' U' R' U2' r U R U' r' R'",
        "R U' R' B' R' U' R2 U R' B",
      ],
    },
    {
      id: "f2l-37-2",
      subset: "F2L 37",
      algs: [
        "U' r U' r' R U R' U r U' r' R U R'",
        "R' F R F' U F' U2' F U' R U R'",
        "R' F R F2 U' F U' R U R' U' R U R'",
        "R U' R' U R' F R F2 U2 F R U R'",
      ],
    },
    { id: "f2l-38-1", subset: "F2L 38", algs: ["R2 U2 R' U' R U' R' U2 R'"] },
    {
      id: "f2l-38-2",
      subset: "F2L 38",
      algs: ["U R U' R' U' R U R' U R' F R F'", "R' F R U R U' R2 F' R U' R U2' R'"],
    },
    { id: "f2l-38-3", subset: "F2L 38", algs: ["F R' F' R2 U2' R' U' R U R'"] },
    {
      id: "f2l-38-4",
      subset: "F2L 38",
      algs: [
        "M' U R U' R' U' R U' r' U2 r U' r'",
        "R U' R' U' r U' r' U2' r U r' R U2 R'",
        "R U2' B2 r' U' r B' R2 F R F'",
        "R U' R' U2 R2 D r' U' r D' R' U' R'",
      ],
    },
    { id: "f2l-39-1", subset: "F2L 39", algs: ["R U2 R' U R U' R' U R U R'"] },
    { id: "f2l-39-2", subset: "F2L 39", algs: ["R U2' R' U R' F R2 U R' U' R' F' R"] },
    { id: "f2l-39-3", subset: "F2L 39", algs: ["R U' R' U R U2 R2 F R F'"] },
    {
      id: "f2l-39-4",
      subset: "F2L 39",
      algs: [
        "R U2' R' r U' r' U M' U2' R U r'",
        "r' U' R2 U' R2' U2' r F' r' F2 r F",
        "R U R D r' U r D' R2' U2' R U R'",
      ],
    },
    {
      id: "f2l-40-1",
      subset: "F2L 40",
      algs: ["U R U' R' F R U R' U' F' R U' R'", "F2 r U r' F U2' R U R'"],
    },
    {
      id: "f2l-40-2",
      subset: "F2L 40",
      algs: ["r U' r' U2' r U r' R U R'", "R' F R D R U R U' R2 D' F'"],
    },
    {
      id: "f2l-41-1",
      subset: "F2L 41",
      algs: ["U' R U R' F U R U' R' F' R U R'", "R U R' U' R U' R' U2 F' U' F"],
    },
    { id: "f2l-41-2", subset: "F2L 41", algs: ["R U' M' U' r' U2 r U r'"] },
  ],
});
