// DF/DB Pair — algorithm case data for @moishy/algsets.
//
// Transformed from old/dfdb.ts via scripts/transform_old_algsets.ts.
// Every source alg is kept as an interchangeable variant; recognition is
// derived from the primary (first) alg of each case. See /DESIGN.md.
//
// Region mask from the source (for a future signature projection; not yet
// wired — recognition currently uses the default full-facelet signature):
//   {
//     "CORNERS": {
//       "slots": [
//         5,
//         6
//       ],
//       "pieces": [
//         5,
//         6
//       ],
//       "orientation": [
//         0,
//         0
//       ]
//     },
//     "EDGES": {
//       "slots": [
//         4,
//         6,
//         7,
//         9,
//         11
//       ],
//       "pieces": [
//         4,
//         6,
//         7,
//         9,
//         11
//       ],
//       "orientation": [
//         0,
//         0,
//         0,
//         0,
//         0
//       ]
//     }
//   }
//
// Source flagged usesMccLookahead: true (a method-runner concern, step 8).

import { type AlgSet, defineAlgSet } from "../define.ts";

export const dfdb: AlgSet = defineAlgSet({
  id: "dfdb",
  name: "DF/DB Pair",
  cases: [
    { id: "dfdb-1", algs: ["r'", "r2 M'", "M"] },
    { id: "dfdb-2", algs: ["r2", "r M'", "M2"] },
    { id: "dfdb-3", algs: ["r", "M'", "r R"] },
    { id: "dfdb-4", algs: ["R U' R' U' r2", "R' U' R U' r2", "U R U R' U r2"] },
    { id: "dfdb-5", algs: ["R U' r' U' r'", "U R U2 r' U r'", "U' r' U' r'"] },
    { id: "dfdb-6", algs: ["r' U r U2 r'", "r' U r U2 M", "r U R2 U' r2"] },
    { id: "dfdb-7", algs: ["R' U' r2", "R' U' r M'", "R' U' r2 R"] },
    { id: "dfdb-8", algs: ["r' U' r2", "r' U' r2 R", "r' U' r2 R'"] },
    { id: "dfdb-9", algs: ["R' U2 r U r", "R' U2 r U M'", "U2 r R2 U' r"] },
    { id: "dfdb-10", algs: ["r U' r' U r", "r U' r' U M'", "U r U r' U2 r"] },
    { id: "dfdb-11", algs: ["r2 U' r'", "r2 U' r' R'", "M2 U' M"] },
    { id: "dfdb-12", algs: ["R U' r' U2 r'", "U' r' U2 r'", "U' M U2 r'"] },
    { id: "dfdb-13", algs: ["r U R U' r2", "R2 U' r' U r U' r'", "r2 U2 r' U r U2 r"] },
    { id: "dfdb-14", algs: ["R2 U' r2", "U R U' R U' r2", "R2 U' r2 R"] },
    { id: "dfdb-15", algs: ["R' U' r", "U' R' U' r R", "R' U' M'"] },
    { id: "dfdb-16", algs: ["r' U' r", "U' r' U' r R", "U' r' U' r R2"] },
    { id: "dfdb-17", algs: ["R' U r' U' r2", "U2 R' U' r' U' r2", "U r' R' U' r2"] },
    { id: "dfdb-18", algs: ["r' R2 U' r2 U' r", "M' U r' U2 r U r", "r' R2 U' r' U r' U' r"] },
    { id: "dfdb-19", algs: ["r2 U' r2", "r2 U' r2 R", "r2 U' r' M"] },
    { id: "dfdb-20", algs: ["R' U' r2 U' r'", "r' U2 r U r", "r' U2 r U M'"] },
    { id: "dfdb-21", algs: ["r' U2 r2", "r' U2 r2 R", "r' U2 r2 R'"] },
    { id: "dfdb-22", algs: ["R U' R' U r2", "R' U' R U r2", "R U' R' U M2"] },
    { id: "dfdb-23", algs: ["r2 U2 r' U r", "U' R U r U' r", "r2 U2 r' U M'"] },
    { id: "dfdb-24", algs: ["R2 U' r2 U' r'", "R2 U' r' M U' r'", "R2 U' r2 R U' r'"] },
    { id: "dfdb-25", algs: ["r' U2 r", "r' U2 r R", "M U2 M'"] },
    { id: "dfdb-26", algs: ["r' U' r2 U r' U2 r", "r' U' r2 U r' U2 M'", "r' R2 U' R2 U' r2"] },
    { id: "dfdb-27", algs: ["R2 U' M'", "R2 U' r", "U' R2 U' r2 M"] },
    { id: "dfdb-28", algs: ["r U' r'", "U2 M' U M", "U2 M' U r'"] },
    { id: "dfdb-29", algs: ["r' U' r U' r", "U r' U' r U2 r", "U r' U' r U2 M'"] },
    { id: "dfdb-30", algs: ["R U' r' U M U r'", "U2 r' R2 U' r' U' r'", "R U r' U M U r'"] },
    { id: "dfdb-31", algs: ["r2 U2 r'", "M2 U2 M", "r2 U2 r' R'"] },
    { id: "dfdb-32", algs: ["R' U M", "R' U r'", "U' R' U' R U2 M"] },
    { id: "dfdb-33", algs: ["r' U r'", "r' U M", "r' U r2 M'"] },
    { id: "dfdb-34", algs: ["R U' r' U r U' r'", "R2 U' r' U r U2 r'", "R U' r' U M' U' r'"] },
    { id: "dfdb-35", algs: ["R U' r2", "R U' r M'", "R U' r2 R"] },
    { id: "dfdb-36", algs: ["r U r U2 r'", "U' R U2 r' U r U' r", "r2 U' r' U r U2 r'"] },
    { id: "dfdb-37", algs: ["R2 U2 r' U r", "R2 U2 r' U M'", "R' U r' U' r"] },
    { id: "dfdb-38", algs: ["r2 U' r", "r2 U' M'", "r' U r' U' r"] },
    { id: "dfdb-39", algs: ["R2 U' r' U' r2", "U R U2 r' U r2", "U' r' R2 U' r2"] },
    { id: "dfdb-40", algs: ["R2 U' r U' r", "R' U' R' U' r U r", "R' U' R' U' r U M'"] },
    { id: "dfdb-41", algs: ["R' U' r2 U' r2", "U' r2 R' U' r2", "U' r M' U' r2"] },
    { id: "dfdb-42", algs: ["r' R' U' r U' r", "r2 M' U' r U' r", "R' U r' U' r U2 r"] },
    { id: "dfdb-43", algs: ["r' R2 U' R U' r2", "r' U' R' U' r2", "R U' r' U' R2 U' r2"] },
    { id: "dfdb-44", algs: ["r2 U2 r' U r2 U r'", "r' U r' M U' r", "r R U2 R' U r2 U r'"] },
    { id: "dfdb-45", algs: ["R2 U2 R' U r2 U r'", "R2 U' r M' U r'", "R' U' R' U' r2 U' r'"] },
    { id: "dfdb-46", algs: ["r U' r2", "r U' r2 R", "r U' r M'"] },
    { id: "dfdb-47", algs: ["r2 U' r U' r", "r' U r' U' r U2 r", "r' U r' U' r U2 M'"] },
    { id: "dfdb-48", algs: ["r' U' r' U' r2", "R2 U2 r2 U r U r", "r' U' r' U' r M'"] },
    { id: "dfdb-49", algs: ["r U' r2 R U M2", "r U' r2 R U r2", "r U' r' M U r2"] },
    { id: "dfdb-50", algs: ["R2 U2 r' U r2 U r'", "R' U2 r U' r2 U' r", "r' R' U' r M' U r'"] },
    { id: "dfdb-51", algs: ["r2 U2 r2", "U' r2 U2 r2 R", "M2 U2 r2"] },
    { id: "dfdb-52", algs: ["R' U M2", "R' U r2", "R' U' R U2 M2"] },
    { id: "dfdb-53", algs: ["r' U r2", "r' U r' M", "r' U M2"] },
    { id: "dfdb-54", algs: ["r' U' R U' r2", "U r U' r' U r' U2 r2", "r' R2 U' R' U' r2"] },
    { id: "dfdb-55", algs: ["r U' r", "r U' r R2", "r U' r U' R'"] },
    { id: "dfdb-56", algs: ["R U' r' M U r'", "R U' r2 R U M", "U' R U' r' M U' r'"] },
    { id: "dfdb-57", algs: ["r U r U2 r2", "R U2 r' U M2 U r'", "r2 R' U2 r U r"] },
    { id: "dfdb-58", algs: ["R2 U r' U r U2 r", "U' r R U' r' U r' U' r2", "R2 U' r' U R U' r2"] },
    { id: "dfdb-59", algs: ["R U' r' U r' U2 r", "U' r' U r' U2 r", "R2 U' r' U r' U2 r"] },
    { id: "dfdb-60", algs: ["r' U' r U r' U2 r", "r2 U' R' U r U' r", "r' U' r U M U2 r"] },
    { id: "dfdb-61", algs: ["r2 R' U' R U' r2", "r U2 r' U r2 U' r2", "R2 U' r' U2 r' U2 r2"] },
    { id: "dfdb-62", algs: ["r U' r2 U r2", "r' U' r U2 r' U2 r2", "U r U r' U r' U r2"] },
    { id: "dfdb-63", algs: ["R U' r", "R U' M'", "U' R U' r R2"] },
    { id: "dfdb-64", algs: ["R2 U' r' U' r", "R U2 r' U r", "R U2 r' U M'"] },
    { id: "dfdb-65", algs: ["R' U R' U2 r U r", "R' U R' U2 r U M'", "R' U' r R2 U' M'"] },
    { id: "dfdb-66", algs: ["r2 U' r' U r2 U' r2", "r' U' r R2 U' M'", "R2 U' r' U R2 U' r2"] },
    { id: "dfdb-67", algs: ["R' U2 r U r' U2 r", "R' U r U' r' U r", "M' R' U' r' U2 r"] },
    { id: "dfdb-68", algs: ["R' U r U2 r'", "R' U r U2 M", "R' U' R U2 r U2 r'"] },
    { id: "dfdb-69", algs: ["r' U' r2 U' r'", "r' U' r2 R U' r'", "r' U' r2 R' U' r'"] },
    { id: "dfdb-70", algs: ["r2 U' r2 U' r", "U r' U2 r U2 r", "U r' U2 r U2 M'"] },
    { id: "dfdb-71", algs: ["r2 U' r' U r U' r'", "U' R2 U2 r' U r U' r", "R' U r' U' r U' r"] },
    { id: "dfdb-72", algs: ["r' U r' U' r U' r", "r2 R' U R U' r2", "R2 U r U2 r'"] },
    { id: "dfdb-73", algs: ["M2 U M", "M2 U r'", "M2 U M R"] },
    { id: "dfdb-74", algs: ["r2 U' r' U' r'", "U2 M2 U M U r'", "r2 U' r' U' r2 M'"] },
    { id: "dfdb-75", algs: ["r2 U' M' U' r U' r", "r R2 U r U M' U r2", "r2 R' U r U r U' M'"] },
    { id: "dfdb-76", algs: ["R' U' r U r2 U2 r2", "R' U' r M2 U2 r2", "R' U2 R U r' U2 r2"] },
    { id: "dfdb-77", algs: ["R U' r' U r'", "R U' r' U M", "U R U' R U' r' U r'"] },
    { id: "dfdb-78", algs: ["R U' r U' r2 R U M", "r2 U' r' U M U' r2", "R U r' U' r2 U' r"] },
    {
      id: "dfdb-79",
      algs: ["r2 U' r' U r2 R' U' r2", "r2 U' r' R' U r2 U' r2", "r2 U' r' U r M' U' r2"],
    },
    { id: "dfdb-80", algs: ["M U r'", "r' U' R U M", "r' U' R U r'"] },
    { id: "dfdb-81", algs: ["r U2 r'", "M' U2 M", "M' U2 r'"] },
    { id: "dfdb-82", algs: ["r U r2 R U M2", "U2 r' R2 U' r' U2 r'", "r U r2 R U r2"] },
    { id: "dfdb-83", algs: ["r' U2 r2 U r", "r' U2 r2 R' U M'", "r' U2 r M' U r"] },
    { id: "dfdb-84", algs: ["R2 U r'", "U' R2 U' R' U2 M", "U' R2 U r' R'"] },
    { id: "dfdb-85", algs: ["R2 U2 r' U' r'", "U2 r2 R' U r U r'", "U2 r2 R' U' r U r'"] },
    { id: "dfdb-86", algs: ["r' U' r U2 r'", "r' U' r U2 M", "U r' U r U' r'"] },
    { id: "dfdb-87", algs: ["r2 U r'", "r2 U r' R'", "r2 U r' R2"] },
    { id: "dfdb-88", algs: ["R U r' U' r U' r", "U2 r' U r U2 r", "M' U r U2 r'"] },
    { id: "dfdb-89", algs: ["R' U' r2 U' r", "U' r2 R' U' r", "U R' U2 r2 U' r"] },
    { id: "dfdb-90", algs: ["R' U' r M2 U2 r", "R' U2 R U r' U2 r", "r' U2 r U r' U2 r"] },
    { id: "dfdb-91", algs: ["r U' R2 U r2", "U' r' U2 r2 U' r' U r'", "r' U' r M2 U2 r"] },
    { id: "dfdb-92", algs: ["M2 U2 r", "r2 R' U2 M'", "M2 U2 M'"] },
    { id: "dfdb-93", algs: ["r' U r", "M U M'", "U R U' r' U r"] },
    { id: "dfdb-94", algs: ["M U M2", "M U r2", "U2 M U' M2"] },
    { id: "dfdb-95", algs: ["R U R2 U2 r U r", "R U R2 U2 r U M'", "R U' r2 R U r' U' r"] },
    { id: "dfdb-96", algs: ["M2 U r2", "M2 U r M'", "U2 M2 U' r2"] },
    {
      id: "dfdb-97",
      algs: ["R' U' r R U r U2 r'", "R U2 r' U r R2 U' r", "r U r' R' U' r2 U2 r'"],
    },
    { id: "dfdb-98", algs: ["r' U' R2 U' r2", "r U' r' U2 r' U2 r2", "r' U' R2 U' r M'"] },
    { id: "dfdb-99", algs: ["R U' r U' r", "R U' r U' M'", "R2 U' R' U' r U r"] },
    { id: "dfdb-100", algs: ["r U r U2 r2 U r", "r U r U2 r2 R U M'", "r' R2 U' r U' M'"] },
    { id: "dfdb-101", algs: ["M' U r2", "M' U r M'", "U2 M' U' r2"] },
    { id: "dfdb-102", algs: ["R' U r U' r U' r2", "r' U' r R U r U2 r'", "r2 R' U' r2 U2 r' U r"] },
    { id: "dfdb-103", algs: ["R U2 r2 U r U r", "r2 U' R' U' r U' r", "R U2 r2 U r U M'"] },
    { id: "dfdb-104", algs: ["r2 R' U' r U' r", "r2 U' R' U' r U r", "R U r U2 r2 U r"] },
    { id: "dfdb-105", algs: ["r2 U' R' U' r2", "R U' r' U2 r' U2 r2", "r2 U' R' U' r M'"] },
    { id: "dfdb-106", algs: ["R' U2 R' U' r2", "R2 U2 R U r2", "R' U' R U' R2 U' r2"] },
    { id: "dfdb-107", algs: ["R' U2 r' U' r2", "r2 U2 r U r2", "r2 U2 r U r M'"] },
    { id: "dfdb-108", algs: ["r U' r2 R' U M", "r U' r2 R' U r'", "r R U' R' U' r2 U' r'"] },
    { id: "dfdb-109", algs: ["R2 U' R' U' r2 U' r'", "R2 U' r' U2 r U r", "R U2 R' U r2 U r'"] },
    { id: "dfdb-110", algs: ["R U2 r' U r2 U r'", "r U r U2 r' U' r'", "r R U r' M U' r"] },
    { id: "dfdb-111", algs: ["R' U M U r'", "R' U' r U r' U2 r2", "U2 R' U M U' r'"] },
    { id: "dfdb-112", algs: ["r' U r U' r U' r2", "r U' r2 R U r' U' r", "r U' r2 R U' r' U' r"] },
    { id: "dfdb-113", algs: ["r' U' r2 U' r2", "r U' r R2 U2 r", "r' U' r2 U' r M'"] },
    { id: "dfdb-114", algs: ["r U' r U' r", "r U' r U' M'", "r U' r U' r' M2"] },
    { id: "dfdb-115", algs: ["r2 U' r' U' r2", "r2 U' r' U' r M'", "r U' r U' R' U' r"] },
    { id: "dfdb-116", algs: ["R' U' R U' r2 U' r2", "r' U2 r' U' r2", "R' U2 r2 R U' r2"] },
    { id: "dfdb-117", algs: ["r' U R U M2", "r' U' r U2 r' U' r2", "r' U R U r2"] },
    { id: "dfdb-118", algs: ["r' U' R U M U r'", "R U' r' U r' U r2 M'", "M U r' U r'"] },
    {
      id: "dfdb-119",
      algs: ["R' U' r M2 U M U r2", "R' U' r M2 U M U M2", "r2 R' U M' U r2 U r'"],
    },
    { id: "dfdb-120", algs: ["r' R2 U' r' U r'", "U' r' U' r U r' U' r2", "U' r U' r' U M2 U r'"] },
    { id: "dfdb-121", algs: ["r2 U' r' U2 r U r", "R2 U r' M U' r", "R2 U r2 R U' r"] },
    {
      id: "dfdb-122",
      algs: ["r2 R' U r U' r", "U2 R2 U' r' U r' U' r2", "U' R2 U2 r' U r2 U' r'"],
    },
    { id: "dfdb-123", algs: ["R U' r2 U r2", "U' r' M U r2", "U' M2 R' U r2"] },
    { id: "dfdb-124", algs: ["r U2 r2", "M' U2 r2", "r U2 r2 R"] },
    { id: "dfdb-125", algs: ["r' U' r U r2 U2 r2", "r' U' r U2 r2 U2 r2", "r' U' r M2 U2 r2"] },
    { id: "dfdb-126", algs: ["R2 U r2", "U r2 U' r' U2 r", "R2 U' R' U2 M2"] },
    { id: "dfdb-127", algs: ["R2 U' r' U M' U r", "R2 U' r' U r U r", "U' R2 U' R' U M U M2"] },
    { id: "dfdb-128", algs: ["r U r2 U r'", "U2 r' U r M' U' r", "U2 r' U r2 R' U' r"] },
    { id: "dfdb-129", algs: ["r2 U r2", "r2 U r2 R", "U' r2 U r' U2 r'"] },
    { id: "dfdb-130", algs: ["R' U2 r2 U' r'", "U2 r' M U r'", "U2 M2 R' U M"] },
    { id: "dfdb-131", algs: ["r2 U2 r' U2 r'", "r2 U2 r' U2 M", "U' r2 U' R2 U' r2"] },
    { id: "dfdb-132", algs: ["R2 U' r' U2 r2", "R2 U' r' U2 M2", "R2 U' r' U2 r M'"] },
    { id: "dfdb-133", algs: ["r U r", "M' U r", "r U M'"] },
    { id: "dfdb-134", algs: ["M' U r U2 r2", "U' R U' r' U M2 U r'", "U2 r U' r U2 r2"] },
    { id: "dfdb-135", algs: ["R U r' U r U2 r", "U r' U' R U2 r U' r", "U r' U r R U' r"] },
    { id: "dfdb-136", algs: ["R U' r2 U r'", "R2 U' R' U' r2 U r'", "R U' r2 U r2 M'"] },
    { id: "dfdb-137", algs: ["R2 U' r' U' r2 U r'", "r' U' r2 U r U2 r2", "r R2 U r2 U' r"] },
    { id: "dfdb-138", algs: ["r U r U2 r' U r'", "r U2 r2 U r", "r U2 r2 R U M'"] },
    { id: "dfdb-139", algs: ["R U R2 U r' U r'", "R U' R2 U r' U r'", "R U2 R2 U r' U r'"] },
    { id: "dfdb-140", algs: ["r2 U' r' U r2 U r2", "r U r2 U r' U r'", "r' U r' U r2 M'"] },
    { id: "dfdb-141", algs: ["R U' r2 U' r", "R U' r' U r' U' r", "U R U2 r2 U' r"] },
    { id: "dfdb-142", algs: ["r U' R' U r U' r", "r R U' R' U r U' r", "U2 r U r' U2 M2 U' r"] },
    { id: "dfdb-143", algs: ["r U' r R2 U' r", "U' r' U r2 U' r2", "U r R U' R' U' r2"] },
    { id: "dfdb-144", algs: ["r2 U' r' U r' U r", "r2 U' r' U M U r", "U' M' U' r2 U r2"] },
    { id: "dfdb-145", algs: ["R U' R' U r U' r", "U' R' U r U' r", "R2 U' R' U r U' r"] },
    { id: "dfdb-146", algs: ["r2 R' U R U r2", "r2 U r2 U' r U2 r'", "M2 U R2 U r2"] },
    { id: "dfdb-147", algs: ["r U' r U2 r'", "M' U' r U2 r'", "U2 R U' r' U' r U' r"] },
    { id: "dfdb-148", algs: ["M' U' r", "M' U' M'", "U r U' r' U' r2"] },
    { id: "dfdb-149", algs: ["R' U2 R U r U' r", "r' U2 r U r U' r", "R' U' r R U' r"] },
    { id: "dfdb-150", algs: ["r U' r' U r' U' r2", "r' U' r R U' r", "r' U' r U R U' r"] },
    { id: "dfdb-151", algs: ["M2 U' r", "M2 U' M'", "r M' R' U' M'"] },
    { id: "dfdb-152", algs: ["R2 U' r' M2 U' r", "R U' R U' r' M2 U r", "R2 U' M' R' U' M'"] },
    { id: "dfdb-153", algs: ["R U' r' U R2 U' r2", "R U' r U r U2 r'", "R2 U2 r' R' U r U' r"] },
    { id: "dfdb-154", algs: ["r U' r' U r2 U' r2", "R2 U2 r2 U r U' r", "r2 U r' U r U2 r2"] },
    { id: "dfdb-155", algs: ["R U' r U' r' U2 r", "R U' r U' r' U2 M'", "r R U' r' U2 r"] },
    { id: "dfdb-156", algs: ["R2 U' r' U2 r", "R2 U' r' U2 M'", "R U' R U' r' U2 r"] },
    { id: "dfdb-157", algs: ["r' U' r U' r'", "R U' r' U M' U r'", "r' U M' U r'"] },
    { id: "dfdb-158", algs: ["r2 R' U2 r U' r", "r2 U' r' U r U' r2", "r2 U2 r U r"] },
    { id: "dfdb-159", algs: ["r U2 r U' r", "r2 U' r2 U' r'", "r2 U' r2 R U' r'"] },
    { id: "dfdb-160", algs: ["M' U2 r U2 r2", "r U2 r U2 r2", "U2 M2 U2 r U2 r"] },
    { id: "dfdb-161", algs: ["r' U2 r2 U' r'", "r' U2 r2 R U' r'", "r' U2 r2 R' U' r'"] },
    { id: "dfdb-162", algs: ["R U r U2 r'", "r U' r' U r U' r'", "r2 U R' U' r2"] },
    { id: "dfdb-163", algs: ["M' R' U M", "M' R' U r'", "R' U2 r U' r'"] },
    { id: "dfdb-164", algs: ["r U' r' U' r'", "U2 R' U' r U r2", "U2 R' U' r U M2"] },
    { id: "dfdb-165", algs: ["R' U r U M' U r2", "R' U r U M' U r' M", "R' U r U M' U r M'"] },
    {
      id: "dfdb-166",
      algs: ["r U M' U r U r", "r2 U' r' R' U' r2 U' r", "r2 U' r' U' r2 R' U' r"],
    },
    { id: "dfdb-167", algs: ["r2 R' U' r' U' r2 U' r", "M' U r U r U' M'", "R2 U r U M' U r2"] },
    { id: "dfdb-168", algs: ["r2 U2 r' U' r'", "R2 U2 r' U r' U2 r2", "r2 U2 r' R2 U' r'"] },
    { id: "dfdb-169", algs: ["r' U' r2 U' r", "U2 r U' r2 R U M", "U2 r U' r2 R U r'"] },
    { id: "dfdb-170", algs: ["r U M' U M' U r2", "r U M' U M' U r' M", "r U r U' M' U' r2"] },
    {
      id: "dfdb-171",
      algs: ["r R2 U r U r U' r", "r U' r' U r2 R' U' r2", "r2 U' r' R2 U' r2 U' r"],
    },
    { id: "dfdb-172", algs: ["r' U M U r'", "r' U' r U r' U2 r2", "r' U M U r2 M'"] },
    { id: "dfdb-173", algs: ["R' U' r2 U2 r'", "R' U' r M' U2 r'", "R' U' r M' U2 M"] },
    { id: "dfdb-174", algs: ["r U2 r' U r' U' r", "r U2 r2 U' r", "r' U' r2 U2 r'"] },
    { id: "dfdb-175", algs: ["r2 U' r' U2 r'", "r2 U' r' U2 M", "U2 R' U' r M' U r2"] },
    { id: "dfdb-176", algs: ["r' R2 U2 r' U2 r'", "r U2 r' U2 r' U2 r2", "r' U' R2 U' r' U2 r'"] },
    { id: "dfdb-177", algs: ["r2 U2 r' U r2 U' r'", "r2 U2 r' U M2 U' r'", "r R U' r' M U2 r'"] },
    { id: "dfdb-178", algs: ["r2 U2 r2 U r", "R2 U' r' M U2 r'", "r2 U2 r2 R U M'"] },
    { id: "dfdb-179", algs: ["R U r'", "R U M", "U' R U r' R'"] },
    { id: "dfdb-180", algs: ["R2 U' r' U r'", "U R2 U2 r' U r'", "R2 U' r' U M"] },
    { id: "dfdb-181", algs: ["r2 R' U M", "r2 R' U r'", "r M' U r'"] },
    { id: "dfdb-182", algs: ["r U r'", "U' r U r' R'", "U' r U r' R2"] },
    { id: "dfdb-183", algs: ["r U' r' U r2 U r'", "U r U r' U2 r2 U r'", "U r' U' r2 U' r U r'"] },
    { id: "dfdb-184", algs: ["r U' r U' r'", "U r' U r U' r", "U2 R U' r' U r U' r"] },
    { id: "dfdb-185", algs: ["R' U' r U M' U r'", "U2 R' U' r U r U2 r'", "R' U' r U M' U M"] },
    { id: "dfdb-186", algs: ["R U' r U r' U r'", "r U' R U r2", "U R U2 r U r' U r'"] },
    { id: "dfdb-187", algs: ["R2 U' r' U r2 U' r2", "r2 U' r' U R2 U' r2", "r2 U' r U r U2 r'"] },
    { id: "dfdb-188", algs: ["R2 U' r2 U' r", "U r U2 r' U2 r'", "R2 U' r' U r' U' r"] },
    { id: "dfdb-189", algs: ["r U2 r", "M' U2 r", "M' U2 M'"] },
    { id: "dfdb-190", algs: ["r U2 r' U r'", "U M2 U r", "U r2 R' U M'"] },
    { id: "dfdb-191", algs: ["R U' r2 U' r2", "U2 R U r2 U' r2", "U' M2 R' U' M2"] },
    { id: "dfdb-192", algs: ["R' U2 r U r2", "U2 r R2 U' r2", "R' U2 r U M2"] },
    { id: "dfdb-193", algs: ["R U' r' U' r2", "U R U r' U r2", "U R U r' U r' M"] },
    { id: "dfdb-194", algs: ["M2 U r U r", "r2 R' U M' U r", "r2 R' U r U r"] },
    { id: "dfdb-195", algs: ["R' U2 R2 U' r2", "R U2 R2 U r2", "r' U2 r R U' r2"] },
    { id: "dfdb-196", algs: ["r U2 r2 U r2", "r' U2 R2 U' r2", "R U' R' U' r' U r2"] },
    { id: "dfdb-197", algs: ["r' U r U M' U r2", "U' M' U R' U2 r U r", "U M' U' R' U2 r U r"] },
    { id: "dfdb-198", algs: ["R2 U' r2 U' r2", "R' U' r M' U' r2", "R U' r' M U' r2"] },
    { id: "dfdb-199", algs: ["M' U r U2 r", "U R' U' r U r U2 r", "U2 M' U' r U2 r"] },
    { id: "dfdb-200", algs: ["r U r U' r", "r U r U' M'", "r U r U' r2 M"] },
    { id: "dfdb-201", algs: ["M' U r U r", "U R' U' r U M' U r", "U R' U' r U r U r"] },
    { id: "dfdb-202", algs: ["R' U2 r2 U' r2", "R U2 r2 U r2", "R' U2 r2 U' r M'"] },
    { id: "dfdb-203", algs: ["R' U' r U r U' r", "U R' U2 r U' r U' r", "U R' U' r U' r U' r"] },
    { id: "dfdb-204", algs: ["r U' R' U' r2", "U r' U' r U M' U r2", "r R U' R2 U' r2"] },
    { id: "dfdb-205", algs: ["R U2 R U r2", "R2 U2 R' U' r2", "R U' R' U' R2 U r2"] },
    { id: "dfdb-206", algs: ["R2 U2 r' U' r2", "r2 R' U2 r U r2", "R U2 r' R2 U r2"] },
    { id: "dfdb-207", algs: ["R2 U2 R' U r U' r", "U R2 U' r U r", "U R2 U' r U M'"] },
    { id: "dfdb-208", algs: ["r U2 r U r2", "R U' R' U' r2 U r2", "r2 U2 R' U' r2"] },
    {
      id: "dfdb-209",
      algs: ["r U' r' U2 r U r", "U2 r U' r' U2 r U2 r", "U2 r' U' r2 U' r' U2 r2"],
    },
    { id: "dfdb-210", algs: ["r U' r U' r' U2 r'", "U r' U r2 U r'", "r U' r U' r' U2 M"] },
    { id: "dfdb-211", algs: ["r U2 r' U' r'", "r R U2 r' U r'", "r U r U' r' U r2"] },
    { id: "dfdb-212", algs: ["R U' r' U r' U' r2", "R U' r' U r' U' r M'", "R U r U' r U' r2"] },
    { id: "dfdb-213", algs: ["R U' r' U M U' r2", "R U' r' U M U' M2", "R U' r' U M U' r M'"] },
    { id: "dfdb-214", algs: ["R2 U r' U' r'", "R U' R U r' U r'", "U R U' R U r' U' r'"] },
    { id: "dfdb-215", algs: ["r' U' r2 R' U' r", "U2 r U r2 R U M", "U2 r U r2 R U r'"] },
    { id: "dfdb-216", algs: ["r2 U r' U' r'", "r U' r U r' U' r'", "r2 U r' U' r2 M'"] },
    { id: "dfdb-217", algs: ["R' U' r U' r2", "U M' U M U r'", "R' U' r U' r M'"] },
    { id: "dfdb-218", algs: ["r' U' r U' r2", "U' r2 U r' U r", "U' r2 U r' U M'"] },
    { id: "dfdb-219", algs: ["r' U2 r2 U' r2", "R' U' R U' r U' r2", "R' U2 r R U' r2"] },
    { id: "dfdb-220", algs: ["R U2 r U r2", "r2 U2 r' U' r2", "r U2 R U r2"] },
    { id: "dfdb-221", algs: ["r U' r U' r2", "U2 r' U r' U' r2", "r U' r U' M2"] },
    { id: "dfdb-222", algs: ["R2 U' r' U r2 U r'", "U r' U' R U' r2 U' r'", "U' M R U r2 U r'"] },
    { id: "dfdb-223", algs: ["R2 U' r' U M U r2", "R2 U' r' U M U M2", "R2 U' r' U M U r M'"] },
    { id: "dfdb-224", algs: ["M' U M' U r2 U r'", "r R2 U r U r2 U r'", "r U M' U r2 R' U M"] },
    { id: "dfdb-225", algs: ["R' U2 r U r U' r", "r U' R2 U' r U r", "r U' R2 U' r U M'"] },
    { id: "dfdb-226", algs: ["R U' r' U M2 U' r2", "r' U' r2 R' U r U' r", "r2 U2 r' U2 r U r"] },
    {
      id: "dfdb-227",
      algs: ["r' U r' U2 r U r", "U' r2 U' r' U M' U' r2", "U' R' U r U' r2 U' r"],
    },
    { id: "dfdb-228", algs: ["R' U2 r2 U' r' U r'", "U R U2 r' U r' U r2", "U2 R U r' U r' U r2"] },
    { id: "dfdb-229", algs: ["r' U' r2 R U r2", "R U' r' U' r2 U r2", "M U' r2 U r2"] },
    { id: "dfdb-230", algs: ["r U' r R2 U' r2", "U' R U' r2 U r U' r", "U2 R U' r' U r2 U2 r'"] },
    { id: "dfdb-231", algs: ["r' U r U r U' r'", "U2 R U' r U' r2 U' r", "U r U' r' U M U' r"] },
    { id: "dfdb-232", algs: ["r2 U' r' U2 r2", "U' R2 U r2 U' r", "r2 U' r' U2 M2"] },
    { id: "dfdb-233", algs: ["R U r2", "R U M2", "R U r M'"] },
    { id: "dfdb-234", algs: ["R2 U' r' U r2", "R2 U' r' U M2", "R2 U' r' U r' M"] },
    { id: "dfdb-235", algs: ["r2 U' r' U2 r2 U r'", "R2 U r' R2 U r'", "R2 U r M2 U r'"] },
    { id: "dfdb-236", algs: ["r2 R' U M2", "U R' U' r2 U r2", "r2 R' U r2"] },
    {
      id: "dfdb-237",
      algs: ["r R U' r' U2 r2 U r'", "R' U r U' r2 U r2", "R2 U2 r' R' U' r' U r'"],
    },
    { id: "dfdb-238", algs: ["R' U2 r U r2 U r'", "r R2 U' r2 R U r'", "M' R' U R' U2 r2 U' r'"] },
    { id: "dfdb-239", algs: ["R' U' r2 R U r'", "R' U2 R U r2 U r'", "r' U2 r U r2 U r'"] },
    { id: "dfdb-240", algs: ["r U r2", "r U r2 R", "r U r M'"] },
    { id: "dfdb-241", algs: ["R2 U' r' U2 r2 U r'", "r2 U r' R2 U r'", "r' U r U' r2 U r2"] },
    { id: "dfdb-242", algs: ["r' U' r2 R U r'", "r' U' r U' r R U r'", "r' U' r U r R U r'"] },
    { id: "dfdb-243", algs: ["r U R U' R' U r2", "r U R U' R' U M2", "U r U r' U M' U' r2"] },
    { id: "dfdb-244", algs: ["r2 R' U' R U' r' U r'", "r' U r' U' R U' r2", "r2 U' R U' r' U r'"] },
    { id: "dfdb-245", algs: ["R U' r' U2 r2", "R U' r' U2 M2", "R U' r' U2 r M'"] },
    { id: "dfdb-246", algs: ["r2 U2 r' U r'", "r U r2 R U M'", "r2 U2 r' U M"] },
    { id: "dfdb-247", algs: ["r' U r2 U' r", "r U' r2 U r'", "r2 U' r' U' r2 U r'"] },
    { id: "dfdb-248", algs: ["R' U r U2 r2", "r R2 U2 r U r", "r R2 U2 r U M'"] },
    { id: "dfdb-249", algs: ["R2 U r' U r' U' r2", "r' U r U r U2 r'", "U2 R U' r' U' r2 U2 r'"] },
    { id: "dfdb-250", algs: ["R U' r' U r2 U r'", "U R U' r U r2 U' r", "U R U' r' U' r2 U r'"] },
    { id: "dfdb-251", algs: ["r U r R2 U' r", "U r U r' U' r U r2", "r U' r' U r U2 r2"] },
    { id: "dfdb-252", algs: ["R2 U r' U r'", "R2 U r' U M", "R2 U r' U r2 M'"] },
    { id: "dfdb-253", algs: ["M' U r2 U r' U r'", "M' U' r2 U r' U r'", "r2 M' U r' U r'"] },
    { id: "dfdb-254", algs: ["M' U r2 U r'", "U R' U' r U r2 U r'", "U2 M' U' r2 U r'"] },
    { id: "dfdb-255", algs: ["r2 U r' U r'", "r2 U r' U M", "r2 U r' U r2 M'"] },
    { id: "dfdb-256", algs: ["r' U M' U r2", "M U M' U r2", "U2 R U2 r' U M' U r2"] },
    { id: "dfdb-257", algs: ["r' R2 U r' U r'", "r U' r' U2 r2 U' r'", "r' R2 U r' U M"] },
    { id: "dfdb-258", algs: ["r2 U R' U M2", "r2 U R' U r2", "M2 U R U r2"] },
    { id: "dfdb-259", algs: ["M' U R U r2", "r R U R' U r2", "r R U R' U M2"] },
    { id: "dfdb-260", algs: ["R' U' r U' r", "U' R' U' r U r", "U' R' U' r U M'"] },
    { id: "dfdb-261", algs: ["R U2 R' U r U' r", "r U2 r' U r U' r", "U R U' r U r"] },
    { id: "dfdb-262", algs: ["R U' r' U r2 U' r'", "R U' r' U M2 U' r'", "R' U2 r U' r U' r2"] },
    { id: "dfdb-263", algs: ["r U' r' U2 r", "r U' r' U2 M'", "r U' r' U2 r' M2"] },
    { id: "dfdb-264", algs: ["R U' r' U2 r", "R U' r' U2 M'", "r2 U' R' U M2"] },
    { id: "dfdb-265", algs: ["R' U' R U' R2 U r2", "R' U2 R' U r2", "R' U' R2 U' R U r2"] },
    { id: "dfdb-266", algs: ["R' U2 r' U r2", "R2 U2 r' R2 U' r2", "r' U' R U' R2 U r2"] },
    { id: "dfdb-267", algs: ["r U r' U r'", "U' r U r' U2 r'", "r U r' U M"] },
    { id: "dfdb-268", algs: ["r U r' U r2", "r U r' U r' M", "r U r' U r M'"] },
    { id: "dfdb-269", algs: ["R U r U2 r2", "R' U' r U2 r U' r", "r U' r' U r U' r2"] },
    { id: "dfdb-270", algs: ["r M' R' U R' U r2", "r2 R' U R2 U r2", "M2 U R' U r2"] },
    { id: "dfdb-271", algs: ["M' U R' U r2", "r U R2 U r2", "M' U R' U r M'"] },
    { id: "dfdb-272", algs: ["R2 U' r' U r' U r2", "U' r' U2 r2 R U r'", "U R U r2 U' r' U r'"] },
    { id: "dfdb-273", algs: ["r2 U' r' U2 r U' r", "R2 U r2 U2 r", "R2 U' r' U M2 U r2"] },
    { id: "dfdb-274", algs: ["r' U r2 U' r'", "U' r U' r U' r' U' r'", "U' R U r' U r2 U' r'"] },
    { id: "dfdb-275", algs: ["M' U2 r U2 r", "R' U' r U2 r U2 r", "r U2 r U2 r"] },
    { id: "dfdb-276", algs: ["R U' r U r'", "r R U r'", "R U2 r U r'"] },
    { id: "dfdb-277", algs: ["R' U2 r2 U' r' U' r'", "M2 R' U M U r'", "R' U2 r2 R U' r' U' r'"] },
    { id: "dfdb-278", algs: ["r2 R' U' R2 U' r2", "r2 U' R U' r2", "R U' r2 R U' R' U' r2"] },
    { id: "dfdb-279", algs: ["r U' r' U r U2 r", "r U r' U R U' r2", "r U' r' U M' U2 r"] },
    {
      id: "dfdb-280",
      algs: ["r2 U2 r' U r U' r'", "U2 r' U' r U2 M2 U r'", "r' R2 U R U' r' U r'"],
    },
    { id: "dfdb-281", algs: ["R' U' r U M' U r2", "U' r U M' U r2", "U R' U2 r U M' U r2"] },
    { id: "dfdb-282", algs: ["r2 R' U r U r2", "r M' U r U r2", "M2 R U r U r2"] },
    { id: "dfdb-283", algs: ["r U r U r2", "r U r U' R' U2 M2", "r2 R' U R U r' U r'"] },
    { id: "dfdb-284", algs: ["r U' r' U2 r'", "r U' r' U2 M", "U2 r U' R' U M2"] },
    { id: "dfdb-285", algs: ["R' U M U2 M", "R' U M U2 r'", "r2 R' U r2 U r2"] },
    { id: "dfdb-286", algs: ["r U r2 U r2", "r' U M U2 r'", "r' U r' U2 r2 M'"] },
    { id: "dfdb-287", algs: ["r' U2 r2 U' r", "r U' r2 R U2 M", "r U' r2 R U2 r'"] },
    { id: "dfdb-288", algs: ["R U' r' M U2 r'", "r U2 r' U r2 U' r'", "R U' r2 R U2 M"] },
    { id: "dfdb-289", algs: ["r U' r' U M U r2", "r U' r' U M U M2", "U' r2 M' U' r' U r'"] },
    { id: "dfdb-290", algs: ["R' U' r2 U r'", "R' U' r U' r U r'", "R' U' r U r U r'"] },
    { id: "dfdb-291", algs: ["r U r2 U' r", "r' U' r2 U r'", "r U r' U r' U' r"] },
    { id: "dfdb-292", algs: ["r2 U' r' U r'", "U r U r2 U2 r", "U r' U2 r2 U r'"] },
    { id: "dfdb-293", algs: ["r U' r2 U' r", "r U' r' U r' U' r", "U' r' U' r U r U' r'"] },
    {
      id: "dfdb-294",
      algs: ["r R U' r' U r2 U' r2", "r2 U' r' U r R U' r2", "M2 R' U R' U2 r U r"],
    },
    { id: "dfdb-295", algs: ["r' R2 U' r' U r", "r' R2 U' r' U M'", "U R U' r' U M U' r"] },
    { id: "dfdb-296", algs: ["R U' r' U r2 U' r2", "r U' r' U r R U' r2", "R U' r' U r2 U' r' M"] },
    { id: "dfdb-297", algs: ["r R2 U' r U' r", "U r U' R2 U' r2", "r U R2 U' r U' r"] },
    { id: "dfdb-298", algs: ["r' U2 r U2 r2", "U2 r2 U2 r' U2 r", "U' r2 U r2 U' r2"] },
    { id: "dfdb-299", algs: ["r U' r' U r U' r", "U r' U' r2 U2 r", "U r' U' r2 R' U2 M'"] },
    { id: "dfdb-300", algs: ["R' U2 r U r U2 r", "r R2 U' r U2 r", "r R2 U' r U2 M'"] },
    { id: "dfdb-301", algs: ["R U' r U' r2", "U' r R U' r2", "U2 R U r U' r2"] },
    { id: "dfdb-302", algs: ["r' U M U r2", "r' U M U M2", "r' U M U r M'"] },
    { id: "dfdb-303", algs: ["R U' r' U r2", "R U' r' U M2", "R U' r' U r' M"] },
    { id: "dfdb-304", algs: ["R U r' U' r' U' r2", "R U' r' U' r' U' r2", "R U2 r' U' r' U' r2"] },
    { id: "dfdb-305", algs: ["R' U2 r U M' U r", "R' U2 r U r U r", "r2 U' r' R2 U' r2"] },
    { id: "dfdb-306", algs: ["R U2 r' U r' U' r2", "U R U r' U r' U' r2", "U' R U r2 U' r U' r"] },
    { id: "dfdb-307", algs: ["R' U' r U2 r", "R' U' r U2 M'", "R' U' r U2 r' M2"] },
    { id: "dfdb-308", algs: ["M' R' U r2", "M' R' U M2", "U2 R' U2 r U' r2"] },
    { id: "dfdb-309", algs: ["R U' r U r2", "U' r R U r2", "U' r R U r2 R"] },
    { id: "dfdb-310", algs: ["r U' R U' r2", "U r2 U2 r' U r U' r", "r U r U2 r' U r2"] },
    { id: "dfdb-311", algs: ["r R2 U' r2 U' r", "r U' r' U2 r' U2 r", "r U r U2 r' U2 r'"] },
    { id: "dfdb-312", algs: ["r U r' U R U r2", "r2 U r' U M U r2", "U' R' U r' U' r2 U' r"] },
    { id: "dfdb-313", algs: ["r' U M U' r2", "U2 r2 U2 r' U M' U r2", "r' U M U' M2"] },
    { id: "dfdb-314", algs: ["r U' R U' r' U r'", "U r2 U' r' U r U2 r", "r U' R U' r' U M"] },
    { id: "dfdb-315", algs: ["r U' r U r2", "U2 r' U r' U r2", "U r U2 r U r' U r'"] },
    { id: "dfdb-316", algs: ["R U r' U r'", "U R U r' U' r'", "R U r' U M"] },
    { id: "dfdb-317", algs: ["R' U' r2 U r' U' r'", "R' U2 r2 U r' U' r'", "M' U r U r' U' r'"] },
    { id: "dfdb-318", algs: ["r U r' U' r'", "r2 U' r' U r2", "r2 U' r' U r' M"] },
    { id: "dfdb-319", algs: ["R' U' R U' r2 U r2", "R2 U' R' U' r2 U' r2", "r' U2 r' U r2"] },
    { id: "dfdb-320", algs: ["r' U' r U' r U2 r'", "r' U' r U' r R U2 r'", "r' U' r U' M' U2 r'"] },
    { id: "dfdb-321", algs: ["R' U' r2 U r' U r", "R' U' r2 U r' U M'", "r' U2 r U M' U' r"] },
    { id: "dfdb-322", algs: ["r U2 r' U r' U' r2", "r' U' r2 U r' U r", "r2 U' r U' r2"] },
    { id: "dfdb-323", algs: ["r2 U r' U' r2", "r2 U r' U' r M'", "r' U2 r U' r U' r2"] },
    { id: "dfdb-324", algs: ["r2 U' r' U R U r2", "R2 U r' U M U' r", "R2 U r' U M U' M'"] },
    { id: "dfdb-325", algs: ["R U' r' U M U r2", "R U' r' U M U M2", "R U' r' U M U r M'"] },
    {
      id: "dfdb-326",
      algs: ["r' R2 U' r' U M U r2", "r' R2 U' r' U M U M2", "r2 U' M U' r' U r'"],
    },
    { id: "dfdb-327", algs: ["R U r2 U r' U r'", "R U' r2 U r' U r'", "r2 R U r' U r'"] },
    {
      id: "dfdb-328",
      algs: ["r2 U' r' R2 U' r' U r'", "r' U' r2 R' U M' U r", "r' U' r2 R' U r U r"],
    },
    { id: "dfdb-329", algs: ["r2 U2 r' U2 r2", "r2 U2 r' U2 M2", "r2 U2 r' U2 r M'"] },
    { id: "dfdb-330", algs: ["R' U' r U r2 U' r'", "U' r U r2 U' r'", "U' r U2 r' U2 r U' r"] },
    { id: "dfdb-331", algs: ["r' U' r2 U r2", "r' U' r2 U r M'", "r' U' r2 U r' M"] },
    { id: "dfdb-332", algs: ["r2 U' r2 R U M2", "r2 U' r2 R U r2", "r2 U' r' M U r2"] },
    { id: "dfdb-333", algs: ["R' U' R2 U' r U r2", "R' U2 r R2 U r2", "r' U2 r2 R U r2"] },
    { id: "dfdb-334", algs: ["r' U2 r U2 M2 U' r", "r' M U' M2 U r'", "M2 R' U' M2 U M"] },
    { id: "dfdb-335", algs: ["R U' r' U r' U2 r2", "U R' U' r U M2 U r", "U' r' U r' U2 r2"] },
    { id: "dfdb-336", algs: ["R' U R2 U r' U' r'", "r' U' r R U r' U2 r'", "R U r' R' U' R U2 M"] },
    {
      id: "dfdb-337",
      algs: ["r' U R2 U r' U' r'", "r U' r' R' U2 r2 U' r'", "r R2 U r U' r U r2"],
    },
    { id: "dfdb-338", algs: ["R U' r U' r' U2 r2", "R2 U' R' U M U r'", "R U' r U' r' U2 M2"] },
    { id: "dfdb-339", algs: ["r U' r' U2 r2 U r'", "r U2 r2 U' r' U r'", "r U' r U r2 U2 r"] },
    {
      id: "dfdb-340",
      algs: ["R' U r U' r U r2", "R U' r' R' U2 r2 U' r'", "r' U r U' r2 R' U M2"],
    },
    { id: "dfdb-341", algs: ["R U' r' U2 r2 U r'", "r2 U' R' U M U r'", "R U2 r2 U' r' U r'"] },
    { id: "dfdb-342", algs: ["r R U' r' M U r'", "r R U' r2 R U M", "r R U' r2 R U r'"] },
    { id: "dfdb-343", algs: ["R2 U' r' M U r'", "R2 U' r2 R U M", "R2 U' r2 R U r'"] },
    { id: "dfdb-344", algs: ["r U r2 R' U' r", "r U r' R2 U2 r' U r", "r U r M' U' r"] },
    { id: "dfdb-345", algs: ["r' U r U' r U r2", "r U r' R' U' R U2 M", "r U r2 U2 r U' r'"] },
    { id: "dfdb-346", algs: ["r U' r U' r' U2 r2", "r U' r U' r' U2 M2", "r U' r U' r' U2 r M'"] },
    { id: "dfdb-347", algs: ["r2 U' r2 R U M", "r2 U' r2 R U r'", "r2 U' r' M U r'"] },
    { id: "dfdb-348", algs: ["R' U M2 U r", "R' U r2 U r", "U2 R' U M2 U' r"] },
    {
      id: "dfdb-349",
      algs: ["r' U2 r R2 U' r' U r'", "r U' r' U R' U r2", "R' U' R2 U2 r' U' r'"],
    },
    { id: "dfdb-350", algs: ["r U' r' U r' U r2", "r U' r' U r' U r M'", "R U' r' U R' U r2"] },
    { id: "dfdb-351", algs: ["r U R' U M2", "r U R' U r2", "r U R' U r M'"] },
    { id: "dfdb-352", algs: ["R' U R' U r2 U r", "R2 U r M' U' r", "R U' r2 U' r2 R U r'"] },
    { id: "dfdb-353", algs: ["R U r2 U' r", "R U r' U r' U' r", "R U r' U' r' U' r"] },
    { id: "dfdb-354", algs: ["r R2 U' r2 U r'", "r' R2 U r2 U' r", "r R2 U' r U' r U r'"] },
    { id: "dfdb-355", algs: ["R' U' r U' r U r2", "U2 R' U' r2 U r' U r'", "r U' r' U r' U r"] },
    { id: "dfdb-356", algs: ["r2 U' r' U r' U2 r", "U r' U2 r2 U r' U r", "U r U r' U M2 U r'"] },
    { id: "dfdb-357", algs: ["r U' r' U r'", "r U' r' U M", "U R U' r U' r' U r'"] },
    { id: "dfdb-358", algs: ["r' R2 U' r U' r2", "r' U' r R2 U' r2", "r2 U r' U r2 U2 r'"] },
    { id: "dfdb-359", algs: ["R' U' R2 U' r U' r2", "R2 U2 r U r2", "R' U2 r R2 U' r2"] },
    { id: "dfdb-360", algs: ["R' U2 R2 U r2", "R' U' R U' R U r2", "R U R' U R' U' r2"] },
    { id: "dfdb-361", algs: ["r U2 r2 U' r2", "r U' r2 U' r U2 r", "r' U' r2 U' r' U2 r"] },
    { id: "dfdb-362", algs: ["R2 U2 R' U r2", "R2 U2 R' U M2", "R2 U2 R' U r M'"] },
    { id: "dfdb-363", algs: ["R2 U2 r' U r2", "R2 U2 r' U M2", "R2 U2 r' U r' M"] },
    { id: "dfdb-364", algs: ["r U2 r U' r2", "r2 U2 R' U M2", "r2 U2 R' U r2"] },
    { id: "dfdb-365", algs: ["M' U R2 U r2", "r U R U r2", "r U R U' R' U2 M2"] },
    { id: "dfdb-366", algs: ["R U r2 U2 r", "R U' r' U M2 U r2", "R U r' M U2 r"] },
    { id: "dfdb-367", algs: ["r U' r' U2 r U' r", "r U2 r2 U' r'", "r U2 r2 R U' r'"] },
    { id: "dfdb-368", algs: ["R2 U' r' U r2 U r2", "r R2 U r' U r'", "r2 U' r' U R2 U r2"] },
    {
      id: "dfdb-369",
      algs: ["R2 U' r' U M2 U' r2", "R2 U' r' U M2 U' r M'", "r2 U' r2 R U' R U r'"],
    },
    { id: "dfdb-370", algs: ["r U' r2 U2 r", "r U' r2 R U2 M'", "r U' r2 R U2 r"] },
    { id: "dfdb-371", algs: ["r' U2 r U2 r'", "r' U2 r U2 M", "r' U2 r U2 r2 M'"] },
    { id: "dfdb-372", algs: ["R' U' r U M U2 r'", "M' U r' U r'", "U' R' U' r U' r' U2 r'"] },
    { id: "dfdb-373", algs: ["R2 U' r' U M U r'", "M2 U r U r2", "R2 U r' U M U r'"] },
    { id: "dfdb-374", algs: ["M' U r U r2", "R' U' r U r U r2", "r2 R' U M U r'"] },
    { id: "dfdb-375", algs: ["r U2 r' U r U' r'", "r U2 r' U M' U' r'", "r2 R' U R U' r' U r'"] },
    { id: "dfdb-376", algs: ["R2 U r' U2 r'", "R2 U r' U2 M", "M2 U r2 U r2"] },
    { id: "dfdb-377", algs: ["M' U r2 U r2", "r2 U2 r' U r' U2 r", "R' U' r U r2 U r2"] },
    { id: "dfdb-378", algs: ["M' U r2 U2 r'", "U R' U' r U r2 U2 r'", "U2 M' U' r2 U2 r'"] },
    {
      id: "dfdb-379",
      algs: ["r' U2 r U r U' r'", "U' R' U' r U M2 U' r", "U' R U r' U2 r2 U' r'"],
    },
    { id: "dfdb-380", algs: ["r2 U r' U r U2 r", "r2 U' r' U R U' r2", "r2 U r' U M' U2 r"] },
    { id: "dfdb-381", algs: ["r2 U' r' U r", "U r U r' U' r2", "r2 U' r' U M'"] },
    { id: "dfdb-382", algs: ["R' U r2 U' r", "r2 R' U' r2 U r'", "r M' U' r2 U r'"] },
    { id: "dfdb-383", algs: ["r2 M U' r U' r", "M' R2 U' r U' r", "M' U' R2 U' r U' r"] },
    { id: "dfdb-384", algs: ["r U2 r' U2 r", "r U2 r' U2 M'", "M' U2 r' U2 r"] },
    { id: "dfdb-385", algs: ["r' U' r2 U r", "r' U' r2 R' U M'", "r' U' r M' U r"] },
    { id: "dfdb-386", algs: ["r' U2 r2 U2 r", "M' U2 r2 U2 r'", "r' U2 r2 R' U2 M'"] },
    { id: "dfdb-387", algs: ["r' U' r2 R U' r2", "R U r' U' r2 U' r2", "R U' r' U' r2 U' r2"] },
    { id: "dfdb-388", algs: ["R2 U' r U2 r", "R2 U' r U2 M'", "R2 U' r' M2 U2 r"] },
    { id: "dfdb-389", algs: ["R' U' r2 U' r' U r'", "U2 r U' r2 U r", "U2 r U' r2 R U M'"] },
    { id: "dfdb-390", algs: ["R' U2 R U' r2 U' r", "r' U2 r U' r2 U' r", "r2 U' r M' U r'"] },
    { id: "dfdb-391", algs: ["M2 U M U M2", "M2 U M U r2", "r2 R' U M U M2"] },
    {
      id: "dfdb-392",
      algs: ["r' U' r U' r2 R' U' r", "r2 R' U M U r U2 r", "r2 U r' R' U r U' r"],
    },
    { id: "dfdb-393", algs: ["R U r2 U' r' U' r2", "r U2 r' U r R U' r2", "R2 U2 r U M' U r"] },
    { id: "dfdb-394", algs: ["R U2 r2 U' r2", "R' U2 r2 U r2", "R U' r2 U' r U2 r"] },
    { id: "dfdb-395", algs: ["r' U2 r2 U r2", "R' U' R U' r U r2", "r U2 R2 U' r2"] },
    { id: "dfdb-396", algs: ["r2 R' U M' U r2", "r M' R' U M' U r2", "r2 R' U M' U r M'"] },
    { id: "dfdb-397", algs: ["R' U' r2 U r' U' r2", "r2 R' U r' U' r2", "U r' U2 r U M' U r2"] },
    { id: "dfdb-398", algs: ["M2 U' M U r'", "U2 r' R2 U' r' U r2", "U r' U2 r U M' U r'"] },
    { id: "dfdb-399", algs: ["r U2 r2 U' r U' r'", "M' U r U r' U r2", "M' U r U r' U r M'"] },
    {
      id: "dfdb-400",
      algs: ["r2 U' r' U r R U' M'", "r' U' r M2 U' M U r2", "r2 U' r' U r R U' r"],
    },
    { id: "dfdb-401", algs: ["r R U' r2 U' r", "r U' r2 R U' r", "r U' r' M U' r"] },
    { id: "dfdb-402", algs: ["M' U' M U r'", "U2 M' U M U' r'", "U2 R' U' r2 U' r' U r2"] },
    { id: "dfdb-403", algs: ["r2 U2 r' U r2", "R U2 r U' r2", "r2 U2 r' U r M'"] },
    { id: "dfdb-404", algs: ["R2 U' r' U M U' r2", "R2 U' r' U M U' M2", "R2 U' r' U M U' r M'"] },
    { id: "dfdb-405", algs: ["r U' r U' r2 R U M", "r U' r U' r2 R U r'", "r U r' U' r2 U' r"] },
    { id: "dfdb-406", algs: ["r2 R' U' r U' r2", "R' U2 r2 U' r U' r2", "R' U' r2 U' r U' r2"] },
    { id: "dfdb-407", algs: ["r U' r' R2 U r'", "r U r U' r' U2 r2", "U' R2 U r' U r' U2 r"] },
    { id: "dfdb-408", algs: ["R U r' U M U' r", "R U r' U M U' M'", "R U r' U' r' U r"] },
    { id: "dfdb-409", algs: ["r U' r' U R U r2", "r U' r' U R U r M'", "r U' r' R2 U R' U r2"] },
    { id: "dfdb-410", algs: ["r2 U r' R2 U' r2", "R U' r2 R U r' U' r2", "r R2 U' r2 U' r' U r"] },
    { id: "dfdb-411", algs: ["r' U' r2 R' U M2", "r' U' r M' U r2", "r' U' r2 R' U r2"] },
    { id: "dfdb-412", algs: ["R U' r' U r' U r2", "R U' r' U r' U r M'", "R' U2 r2 R U' r' U r'"] },
    { id: "dfdb-413", algs: ["r R U r' U r'", "r R U r' U M", "R U' r U r' U2 r'"] },
    { id: "dfdb-414", algs: ["R' U2 r U r2 U' r'", "R' U2 r U M2 U' r'", "M' R' U' M2 U M"] },
    { id: "dfdb-415", algs: ["M2 R' U r' U r2", "R U r2 U r' U r2", "R U' r2 U r' U r2"] },
    { id: "dfdb-416", algs: ["r U' r U r' U' r2", "r' U' r U' r U2 r2", "M' U' r U r' U' r2"] },
    { id: "dfdb-417", algs: ["r U2 r' U2 r2", "r U2 r' U2 M2", "r U2 r' U2 r M'"] },
    { id: "dfdb-418", algs: ["r2 U2 r' U r2 U2 r'", "r2 U2 r' U M2 U2 r'", "R2 U2 r U r2 U' r'"] },
    { id: "dfdb-419", algs: ["M' U' M U M2", "M' U' M U r2", "M' U M U' M2"] },
    { id: "dfdb-420", algs: ["r2 U' M U' r U' r", "r R2 U r U M U r2", "M2 R' U M U r U2 r"] },
    { id: "dfdb-421", algs: ["r2 U2 r' U r U r", "r2 U2 r' U M' U r", "r' U2 r R U' r U' r2"] },
    { id: "dfdb-422", algs: ["r U' r' U r' U2 r", "U' R U r U' r2 U' r", "r U' r' U M U2 r"] },
    { id: "dfdb-423", algs: ["r R U' r' U r'", "U R U' r U' r' U2 r'", "U' R U r' U r' U2 r"] },
    { id: "dfdb-424", algs: ["r' U' r U r2", "r' U' r U r M'", "r' U' r U M2"] },
    {
      id: "dfdb-425",
      algs: ["R' U2 r R2 U' r' U r'", "r' U2 r2 R U' r' U r'", "r' U' r R U r2 U2 r"],
    },
    { id: "dfdb-426", algs: ["r' U' r U r U r", "r' U' r U M' U r", "U2 M U' M' U r2"] },
    { id: "dfdb-427", algs: ["r' U' r R U' r2", "r' U' r R U' r M'", "r' U' r R U' r' M"] },
    { id: "dfdb-428", algs: ["r U r' U r2 U2 r'", "R2 U2 r2 U' r U' r2", "r U r' U M2 U2 r'"] },
    { id: "dfdb-429", algs: ["r2 U r' U r2 U r'", "r' U' r U' r' U2 r'", "r' U' r R U' r' U2 r'"] },
    { id: "dfdb-430", algs: ["r U r' U r R2 U' r", "R' U r U M U r2", "R' U r U M U M2"] },
    { id: "dfdb-431", algs: ["R2 U' r' U' r2 U r2", "r' U2 r2 U' r' U2 r'", "r' R2 U' r2 U r2"] },
    { id: "dfdb-432", algs: ["r2 U' r2 U r U' r", "r U' r R2 U' r U r'", "r U' r2 R U' R U r'"] },
    {
      id: "dfdb-433",
      algs: ["r U r' U r2 U' r'", "U2 R U r2 U' r U' r2", "U2 R U2 r2 U' r U' r2"],
    },
    { id: "dfdb-434", algs: ["r' U2 r U' r' U' r'", "r' U2 r R U' r' U' r'", "R' U r2 U r U' r'"] },
    {
      id: "dfdb-435",
      algs: ["R2 U' r' U M' U r2", "R2 U' r' U M' U r' M", "R2 U' r' U M' U r M'"],
    },
    {
      id: "dfdb-436",
      algs: ["R2 U' r' U M' U' r2", "R2 U' r' U M' U' M2", "R2 U' r' U M' U' r M'"],
    },
    { id: "dfdb-437", algs: ["R' U r2 U2 r", "R' U M2 U2 M'", "R' U r M' U2 r"] },
    { id: "dfdb-438", algs: ["r U' r' R' U r2 U' r", "r U M' U r2 U r'", "r2 U' r' U' r' R' U M"] },
    { id: "dfdb-439", algs: ["R U r' U2 r'", "R U r' U2 M", "R U r' U2 r2 M'"] },
    { id: "dfdb-440", algs: ["r' R2 U r' U2 r'", "M2 U r U r' U r'", "r' R2 U r' U2 M"] },
    { id: "dfdb-441", algs: ["r U r' U r U2 r", "r U' r' U R U' r2", "r U r' U M' U2 r"] },
    { id: "dfdb-442", algs: ["M2 U r' U r2", "r M' R' U r' U r2", "r' U' r U' r2 R' U2 M'"] },
    { id: "dfdb-443", algs: ["R' U' r R2 U r' U2 r'", "R U' r U r' R2 U r'", "r R U r' R2 U r'"] },
    { id: "dfdb-444", algs: ["r2 R' U r2 U' r2", "R' U' r2 U2 r' U2 r", "R' U' r2 U2 r' U2 M'"] },
    { id: "dfdb-445", algs: ["r U r2 U' r2", "r U r2 U' r M'", "r U r2 U' M2"] },
    { id: "dfdb-446", algs: ["r2 U' r2 U r", "r2 U' r2 R U M'", "U R U' r2 U' r2 U r"] },
    {
      id: "dfdb-447",
      algs: ["r' U2 r R U' R U' r2", "R2 U r' U2 r U2 r2", "R U' r2 R U r2 U' r2"],
    },
    { id: "dfdb-448", algs: ["r' U r2 U2 r", "r U2 r2 U r'", "r' U r M' U2 r"] },
    { id: "dfdb-449", algs: ["R U' r' M2 U2 r", "R U2 R' U r U2 r", "R U' r R2 U2 r"] },
    { id: "dfdb-450", algs: ["r' U' r U r", "r' U' r U M'", "r' U' r U r' M2"] },
    { id: "dfdb-451", algs: ["M' U M U M2", "M' U M U r2", "U R' U' r U M U r2"] },
    { id: "dfdb-452", algs: ["R U' r' U' r' U r2", "M U' r' U r2", "R U r2 U r' U' r'"] },
    { id: "dfdb-453", algs: ["r R U r' U r2 U r'", "r U M U r2 U r'", "r2 U' r R U' r' U r'"] },
    { id: "dfdb-454", algs: ["R' U' r2 U' r' U r", "R' U' r2 U' r' U M'", "r U r' R' U' r2"] },
    { id: "dfdb-455", algs: ["r2 U r' U r2", "r2 U r' U r' M", "r2 U r' U r M'"] },
    { id: "dfdb-456", algs: ["M2 U' r' U r2", "r2 U' r' R2 U r2", "M' R' U M U' r'"] },
    {
      id: "dfdb-457",
      algs: ["r2 U' r' R' U r U' r", "r' R2 U' r' U M U' r2", "r2 R' U M U' r U2 r"],
    },
    { id: "dfdb-458", algs: ["r2 U' r' U r U' r", "r2 R' U2 r U' r U' r'", "r2 U' r' U r U' M'"] },
    { id: "dfdb-459", algs: ["R U' r' U' r U r", "R U r' U' r U r", "M U' M' U r"] },
    { id: "dfdb-460", algs: ["r2 U' r' U r2 U' r'", "r U r' R2 U' r2", "r2 U' r' U M2 U' r'"] },
    { id: "dfdb-461", algs: ["R U r2 U' r U' r'", "r R U r' U r2", "r R U r' U r' M"] },
    { id: "dfdb-462", algs: ["R' U' r U2 r' U2 r2", "r2 R' U' r2 U r2", "R' U' r U2 M U2 r2"] },
    {
      id: "dfdb-463",
      algs: ["r2 U' r2 R U r U' r", "r' U r' U' r2 R' U M2", "r' U r' U' r M' U r2"],
    },
    {
      id: "dfdb-464",
      algs: ["r2 U r2 R U r U' r", "r U r' R2 U' r' U2 r'", "r U r' U' r' R2 U2 r'"],
    },
    { id: "dfdb-465", algs: ["r R U r' U r U2 r", "r R U' r' U R U' r2", "r U r' U r R U' M'"] },
    { id: "dfdb-466", algs: ["R' U' r2 U r' U r2", "U2 r2 U r' U r U r", "U2 r2 U r' U M' U r"] },
    { id: "dfdb-467", algs: ["r U2 r' U r U r", "r R U r' U' r2", "r U2 r' U M' U r"] },
    { id: "dfdb-468", algs: ["R' U M U' M U M'", "R' U M U' r' U r", "r2 U r' U' r' R' U M"] },
    { id: "dfdb-469", algs: ["R2 U' r' U M2 U' r", "r2 U2 r' U2 r2 U' r'", "R2 U2 r' U M2 U' r"] },
    { id: "dfdb-470", algs: ["r' U' r U r2 U r'", "r2 U r' U r' U2 r", "r2 U r' U M U2 r"] },
    { id: "dfdb-471", algs: ["r' U' r U r2 U' r'", "r' U' r U M2 U' r'", "r' U' r U M2 U' M"] },
    { id: "dfdb-472", algs: ["r2 U' r U r2", "r U2 r' U r' U r2", "r2 U' r U r M'"] },
    { id: "dfdb-473", algs: ["r U r U' r'", "U2 R' U2 r U r U' r'", "U r U r U' r2 U' r"] },
    { id: "dfdb-474", algs: ["r' U' r R2 U r2", "r' R2 U' r U r2", "M R U' r U r2"] },
    {
      id: "dfdb-475",
      algs: ["r2 R' U r2 U' r' U r'", "r2 U2 r' U2 M2 U r'", "r2 U' r' U r' R2 U r2"],
    },
    { id: "dfdb-476", algs: ["R U' r' U M' U r2", "R U' r' U M' U r' M", "R U' r' U M' U r M'"] },
    { id: "dfdb-477", algs: ["r U r' U r' U2 r2", "r' U2 r2 U r U' r'", "r' U r' U' r U r2"] },
    { id: "dfdb-478", algs: ["r' U' r U r2 U2 r'", "r2 U2 r' U r' U r", "r' U' r U M2 U2 r'"] },
    { id: "dfdb-479", algs: ["r U r' U r2 U r'", "M' U M U r2 U r'", "r2 U' r U' r' U2 r'"] },
    { id: "dfdb-480", algs: ["R2 U' r' U' r U r", "R2 U r' U' r U r", "R U2 r' U M' U' r"] },
    { id: "dfdb-481", algs: ["r U r' U r", "r U r' U M'", "M' U M U M'"] },
    { id: "dfdb-482", algs: ["r' U M2 U' r", "r' U M2 U' M'", "r' U2 r2 U r' U2 r2"] },
    { id: "dfdb-483", algs: ["r U r2 U' r2 U r", "r2 R' U M2 U' r2", "M2 U' M2 U r2"] },
    { id: "dfdb-484", algs: ["M2 U' r2 U r2", "r U' r' R2 U r' U r'", "r2 U' r2 U r U2 r"] },
    { id: "dfdb-485", algs: ["r2 R' U' r U r2", "R' U' r2 U' r U r2", "r M' U' r U r2"] },
    {
      id: "dfdb-486",
      algs: ["r2 R' U' r U' r' U2 r'", "r' R2 U' r' U M' U r2", "M' U r' U r2 U r'"],
    },
    { id: "dfdb-487", algs: ["r' U' r U r U' r", "r U' r U r U' r'", "R U' r' U M' U' r2"] },
    { id: "dfdb-488", algs: ["R U' r U r U' r'", "R U' r R2 U r U' r'", "R U' M' R' U' M' U M"] },
    { id: "dfdb-489", algs: ["r' U' r U r U2 r", "r' U' r U M' U2 r", "r' U' r U M' U2 M'"] },
    { id: "dfdb-490", algs: ["M' U2 r2 U r'", "R' U' r U2 r2 U r'", "r R U' r' U2 r U' r"] },
    { id: "dfdb-491", algs: ["r U r' R2 U r2", "r2 U' r' U2 M2 U r'", "M' R' U r' U r2"] },
    { id: "dfdb-492", algs: ["R' U' r U r2 U' r2", "R' U2 r U r2 U' r2", "R' U r U r2 U' r2"] },
    { id: "dfdb-493", algs: ["r U r2 U' r' U' r'", "r' U' r' U' r2 U r", "r U' r R2 U r U r2"] },
    { id: "dfdb-494", algs: ["r2 U r2 R U' r2", "R U r' U2 r U2 r2", "r2 U r' M U' r2"] },
    { id: "dfdb-495", algs: ["r R2 U r2 U' r2", "M' U r2 R' U' M2", "R' U' r U r2 R' U' r2"] },
    { id: "dfdb-496", algs: ["R' U' r2 U r U' r2", "r2 R' U r U' r2", "R' U2 r2 U r U' r2"] },
    { id: "dfdb-497", algs: ["r U r U' r2", "r2 U' r U r", "r U r U' r' M"] },
    { id: "dfdb-498", algs: ["M2 U' M U M2", "M2 U M U' M2", "M2 U' M U r2"] },
    { id: "dfdb-499", algs: ["R U' r U r' U' r'", "r R U r' U' r'", "r2 U' r' U r U r"] },
    { id: "dfdb-500", algs: ["M2 U' M' U r2", "r2 R' U M' U' M2", "r M' R' U' M' U r2"] },
    {
      id: "dfdb-501",
      algs: ["r' U' r U r2 R' U M", "r' U' r U r2 R' U r'", "r' U' r U r M' U r'"],
    },
    { id: "dfdb-502", algs: ["M2 R' U M U r' U2 r", "M R U' M' U r2 U r'", "r2 U r R U' r' U r'"] },
    { id: "dfdb-503", algs: ["r U r2 R U' r2", "R U' r U r2 U' r2", "r R U r2 U' r2"] },
    { id: "dfdb-504", algs: ["r R2 U' r U r U' r'", "M' R' U' r U r U' r'", "r' U r U' R' U' r2"] },
    { id: "dfdb-505", algs: ["r U r U' r' U r'", "U' M2 U' r U r", "U' R2 U' r2 U' r U r"] },
    { id: "dfdb-506", algs: ["r2 U' r' U r2 U r'", "R' U M' U M U' M2", "R' U r U M U' r2"] },
    { id: "dfdb-507", algs: ["M' U r' U r2", "R' U r2 U' r U' r'", "r U r' R' U r2"] },
    {
      id: "dfdb-508",
      algs: ["r U' r2 R U' r U' r2", "r U' r2 U' r R U' r2", "r2 U r' U r2 R' U M"],
    },
    {
      id: "dfdb-509",
      algs: ["r U r' U' r' R' U M", "r U r' U' r' R' U r'", "r U r' R' U' r' U r'"],
    },
    { id: "dfdb-510", algs: ["r U r' U r' U2 r", "r U r' U M U2 r", "r U r' U M U2 M'"] },
    { id: "dfdb-511", algs: ["r2 U R' U r U' r", "r2 R' U R' U r U' r", "r U' r U R' U M2"] },
    { id: "dfdb-512", algs: ["r' U' r R U r2", "M U' r U r2", "r' U' r R U r M'"] },
    { id: "dfdb-513", algs: ["R2 U' r2 U' r U r2", "M2 U' r U r2", "R2 U' r2 U' r U r M'"] },
    { id: "dfdb-514", algs: ["R U2 r2 U' r2 U r", "r2 R' U M2 U' r", "r2 R' U M2 U' M'"] },
    { id: "dfdb-515", algs: ["r U r2 U' r' U r'", "r U2 r' U2 r2 U r'", "R2 U2 r2 U' r2 U r"] },
    {
      id: "dfdb-516",
      algs: ["r' U' r2 U r U' r'", "U2 R U' r2 U' r U r2", "U2 R U' r2 U' r U r M'"],
    },
    { id: "dfdb-517", algs: ["R' U' r U r U' r'", "R' U' r U M' U' r'", "R' U' r U M' U' M"] },
    { id: "dfdb-518", algs: ["r' M U M2 U' r", "R' U2 r2 U' r2 U r", "r' U2 r' U' r2 U r"] },
    { id: "dfdb-519", algs: ["r U' r U r2 R U' r2", "r U' r R U r2 U' r2", "r U' r U r' M U' r2"] },
    { id: "dfdb-520", algs: ["r U r U' r' U' r'", "R' U' r U r U' r2", "R' U2 r U r U' r2"] },
    { id: "dfdb-521", algs: ["r U r U' r' R2 U r'", "R' U r U M' U' r2", "M' R' U M U r' U2 r"] },
    { id: "dfdb-522", algs: ["r U r U' r' U2 r'", "r U' r U' R' U M2", "r U' r U' R' U r2"] },
    { id: "dfdb-523", algs: ["r' U M U' M' U r", "r' U M U' r U r", "r2 U r' R' U' r2 U' r"] },
    { id: "dfdb-524", algs: ["r R U r' U r' U2 r", "r U r R U' r' U r'", "M2 U' M' U r2 U r'"] },
    { id: "dfdb-525", algs: ["R2 U' r U r U' r'", "r U r R2 U' r2 U' r", "R2 U' r U M' U' r'"] },
    {
      id: "dfdb-526",
      algs: ["r2 U' r' U r2 R' U M", "r2 U' r' U r2 R' U r'", "r U' r2 R U' r U r2"],
    },
    { id: "dfdb-527", algs: ["R U' r2 U' r U r", "R U' r2 U' r U M'", "R U r2 U' r U r"] },
  ],
});
