// EO Pair — algorithm case data for @moishy/algsets.
//
// Transformed from old/eoPair.ts via scripts/transform_old_algsets.ts.
// Every source alg is kept as an interchangeable variant; recognition is
// derived from the primary (first) alg of each case. See /DESIGN.md.
//
// Source flagged usesMccLookahead: true (a method-runner concern, step 8).

import { type AlgSet, defineAlgSet } from "../define.ts";

export const eoPair: AlgSet = defineAlgSet({
  id: "EOPair",
  name: "EO Pair",
  cases: [
    { id: "or-1", subset: "or", algs: ["R' U' F' U F R'"] },
    {
      id: "or-2",
      subset: "or",
      algs: ["R' U R' F' U2 F", "R' U2 R2' F R F'", "R' U R' U' F' U' F"],
    },
    { id: "or-3", subset: "or", algs: ["R2 f' U' f", "U F R' F' R2", "S' R' U' R S R2"] },
    { id: "or-4", subset: "or", algs: ["R' B' R2 B R", "U F R' F' R U R U' R"] },
    {
      id: "or-5",
      subset: "or",
      algs: ["R2 U f' U' f", "R' U R' f' U' f", "f R S' R' F' R2", "U' R' U' R f R f' R2"],
    },
    { id: "or-6", subset: "or", algs: ["R' U R' F' U' F"] },
    { id: "or-7", subset: "or", algs: ["F R F' U' R2'", "R2' F R' F' R"] },
    { id: "or-8", subset: "or", algs: ["R F R F'", "R2 U' F' U F"] },
    { id: "or-9", subset: "or", algs: ["R' f R f' R'", "U' R' F R2 F' R"] },
    { id: "or-10", subset: "or", algs: ["R2 F' U' F"] },
    { id: "or-11", subset: "or", algs: ["f' U' f R'", "R2 S' R U' R' S"] },
    { id: "or-12", subset: "or", algs: ["R2 F' U2 F", "U f R' f' R2"] },
    { id: "or-13", subset: "or", algs: ["R F' U' R' U R F", "R U' F' R' U R F"] },
    {
      id: "or-14",
      subset: "or",
      algs: ["S' R' U2 R S R2", "R' U' R' f' U' f", "R U2 R' f R' f' U' R"],
    },
    { id: "or-15", subset: "or", algs: ["R2 F' U F"] },
    { id: "or-16", subset: "or", algs: ["R2 U2 S' U' S"] },
    { id: "or-17", subset: "or", algs: ["S' U S R2"] },
    { id: "or-18", subset: "or", algs: ["S R U' R' U R S'"] },
    { id: "or-19", subset: "or", algs: ["S' U' S U' R2"] },
    { id: "or-20", subset: "or", algs: ["R2 F' U' r U' r' F2", "R U2 R' U S R S' U R"] },
    { id: "or-21", subset: "or", algs: ["S' U' S R2"] },
    { id: "or-22", subset: "or", algs: ["f R U R' U' R' f' R2", "U f R' f' R2 f' U' f"] },
    { id: "or-23", subset: "or", algs: ["R2 S' U' S"] },
    { id: "or-24", subset: "or", algs: ["R U R' S R S' U' R"] },
    { id: "or-25", subset: "or", algs: ["R D' r U' r' D R"] },
    { id: "or-26", subset: "or", algs: ["D r' U' r D' R2"] },
    {
      id: "or-27",
      subset: "or",
      algs: ["R' U' R U S' U' S R2", "R U' R2 S R S' U R", "U f R' S' R S R' f' R2"],
    },
    { id: "or-28", subset: "or", algs: ["R' U2 R U S' U' S R2", "R' u' R u R2 u' R' u R'"] },
    { id: "or-29", subset: "or", algs: ["R' U R' S' U' S", "f R' S' R F' R2"] },
    { id: "or-30", subset: "or", algs: ["R' S R S' R U' R2"] },
    { id: "or-31", subset: "or", algs: ["f R' f' R2 S' U' S", "U D r' U' r D' F R' F' R2"] },
    {
      id: "dbr-solved-eo-(1)-UF/UR",
      subset: "dbr-solved-eo-(1)",
      algs: ["F R' F' R", "U' f' U f"],
    },
    {
      id: "dbr-solved-eo-(1)-UF/UB",
      subset: "dbr-solved-eo-(1)",
      algs: [
        "f' L' U L f",
        "F R U R' U' F'",
        "f U R U' R' f'",
        "U R' F' U' F U R",
        "r u' r' U r u r'",
      ],
    },
    {
      id: "dbr-solved-eo-(1)-UF/FR",
      subset: "dbr-solved-eo-(1)",
      algs: ["R' F R F'", "U F' U' F", "U' F' U F", "U2 f' U2' f"],
    },
    {
      id: "dbr-solved-eo-(1)-UF/DR",
      subset: "dbr-solved-eo-(1)",
      algs: ["f' U' f", "r' U' R' U r"],
    },
    {
      id: "dbr-solved-eo-(1)-FR/DR",
      subset: "dbr-solved-eo-(1)",
      algs: ["S' R U R' U' S", "R U' R' f' U' f", "R u' R' U R u R'"],
    },
    {
      id: "dbr-solved-eo-(1)-UF/UL/UB/UR",
      subset: "dbr-solved-eo-(1)",
      algs: [
        "r U r' U2 M' U M",
        "R U' R' S R' U' R U R S'",
        "F R' F' R2 U2 R2' F R F'",
        "r U2' r' U2 r U' r' U2 r U2' r'",
      ],
    },
    {
      id: "dbr-solved-eo-(1)-UB/UR/UF/FR",
      subset: "dbr-solved-eo-(1)",
      algs: ["S R' U' R U R S'", "R' D' r U' r' D R", "U' r U' r' U2 r U r'"],
    },
    {
      id: "dbr-solved-eo-(1)-UB/UR/UF/DR",
      subset: "dbr-solved-eo-(1)",
      algs: ["S' U' S", "S' U S"],
    },
    {
      id: "dbr-solved-eo-(1)-UF/UR/FR/DR",
      subset: "dbr-solved-eo-(1)",
      algs: [
        "S' U R U2' R' S",
        "R U' R' U S' U' S",
        "U R U2' R' U S' U' S",
        "U' R U' R' U2 S' U' S",
        "U2 R U R' U2 S' U' S",
      ],
    },
    {
      id: "dbr-solved-eo-(1)-UL/UR/FR/DR",
      subset: "dbr-solved-eo-(1)",
      algs: ["R U R' S' U' S", "R U' R' S' U' S"],
    },
    {
      id: "dbr-solved-eo-(1)-UF/UL/UB/UR/FR/DR",
      subset: "dbr-solved-eo-(1)",
      algs: ["S' U' S F' U' F", "F R' F' R U S' U' S"],
    },
    { id: "ou-1", subset: "ou", algs: ["S' R' U R S", "F R' F' U R"] },
    { id: "ou-2", subset: "ou", algs: ["R U f' U f", "R U2 F R' F' R"] },
    { id: "ou-3", subset: "ou", algs: ["F R2 U R' U' F'", "R2 U' R' F' U' F"] },
    { id: "ou-4", subset: "ou", algs: ["F' U F R", "U R F R' F' R", "U' R' U2 F R F'"] },
    { id: "ou-5", subset: "ou", algs: ["F R F'"] },
    { id: "ou-6", subset: "ou", algs: ["f R f' U2 R", "U2 S U R U' S'", "U2 R' F' U F R"] },
    {
      id: "ou-7",
      subset: "ou",
      algs: ["R S' R' U' R S", "U' F' U' F U R", "U2 R' F U R U' F'", "U2 R' F R F' U R"],
    },
    { id: "ou-8", subset: "ou", algs: ["R F' U' F", "U S' U2 R' U R S", "R U' R' F R F'"] },
    { id: "ou-9", subset: "ou", algs: ["f R' f' U' R", "U F R2 F' U R", "U R' F U R2 U' R' F'"] },
    { id: "ou-10", subset: "ou", algs: ["R f' U f", "M U' R U r", "U' R' U R F' U2 F"] },
    { id: "ou-11", subset: "ou", algs: ["R f' U2 f", "M U' R2 U r", "R U2 R' F R F'"] },
    { id: "ou-12", subset: "ou", algs: ["S U' R U S'", "U' R f' U' f", "U' M U' R' U r"] },
    { id: "ou-13", subset: "ou", algs: ["U' R F' U F", "U' R U R' F R F'"] },
    { id: "ou-14", subset: "ou", algs: ["R2 F' U F R", "S' R' U R U' S", "R' f R U R U' f'"] },
    { id: "ou-15", subset: "ou", algs: ["R U' f' U' f", "U' R' U F R F'"] },
    {
      id: "ou-16",
      subset: "ou",
      algs: ["R' U' R S R' S' U' R", "U S R U' R2 U S' U R", "R' U' R S R S' R2 U' R"],
    },
    { id: "ou-17", subset: "ou", algs: ["R' U2 R S' U' S", "R' U2 R S' U S"] },
    { id: "ou-18", subset: "ou", algs: ["R U2 S' U' S", "R U2 S' U S", "U2 R U' R' S R S' U' R"] },
    { id: "ou-19", subset: "ou", algs: ["F' U F2 R F'", "R U R U' S' U S", "U D' r U' r' D R"] },
    { id: "ou-20", subset: "ou", algs: ["S' U' R' U2 R S"] },
    { id: "ou-21", subset: "ou", algs: ["R U' S' U' S", "R U' S' U S"] },
    {
      id: "ou-22",
      subset: "ou",
      algs: ["S' U R U2 R' S R2", "U R U2 R U S' U' S", "U' R' f' U' f2 R f' R'"],
    },
    { id: "ou-23", subset: "ou", algs: ["S' U R' U2 R S", "U R' U2 R U S' U' S"] },
    { id: "ou-24", subset: "ou", algs: ["R U S' U' S", "R U S' U S"] },
    { id: "ou-25", subset: "ou", algs: ["R S R' S' U' R", "U2 R S R' S' U R", "U2 R U R S' U S"] },
    { id: "ou-26", subset: "ou", algs: ["R' S R S' U R", "R' U R S' U S"] },
    { id: "ou-27", subset: "ou", algs: ["R S' U' S", "U' S R S' U R"] },
    {
      id: "ou-28",
      subset: "ou",
      algs: ["U' R S' U' R U2 R' S", "R' U' R U' R S R S' R'", "U2 S R S' R2 F' U F R"],
    },
    { id: "ou-29", subset: "ou", algs: ["R2 U' R' S' U' S", "R2 U' R' S' U S"] },
    { id: "ou-30", subset: "ou", algs: ["R2 S R S' U R"] },
    { id: "ou-31", subset: "ou", algs: ["R F' U F S' U' S", "U' S R S' R' F R U R U' F'"] },
    { id: "dfr-UF/UR", subset: "dfr", algs: ["F R' F'"] },
    { id: "dfr-UL/UR", subset: "dfr", algs: ["F R U R' U' F'"] },
    { id: "dfr-UF/BR", subset: "dfr", algs: ["f R f'"] },
    { id: "dfr-UF/DR", subset: "dfr", algs: ["F R F'"] },
    {
      id: "dfr-BR/DR",
      subset: "dfr",
      algs: ["S' R' U' R U S", "S' R' U' R U' S"],
    },
    {
      id: "dfr-UF/UL/UB/UR",
      subset: "dfr",
      algs: ["r' U' r U2 M U' M'", "R' F' U' r U' r' F2 R"],
    },
    {
      id: "dfr-UB/UR/UF/BR",
      subset: "dfr",
      algs: ["f U R2 U' f'", "U r' U r U2 r' U' r"],
    },
    { id: "dfr-UR/UF/UL/DR", subset: "dfr", algs: ["S' U' S", "U' S' U S"] },
    { id: "dfr-UF/UL/BR/DR", subset: "dfr", algs: ["S' U R' U2 R S"] },
    { id: "dfr-UF/UB/BR/DR", subset: "dfr", algs: ["R' U' R S' U' S"] },
    {
      id: "dfr-UF/UL/UB/UR/FR/DR",
      subset: "dfr",
      algs: ["f R' f' S' U' S"],
    },
    { id: "mu-1", subset: "mu", algs: ["U R' F' U' F R", "U' R' F' U' F R2"] },
    { id: "mu-2", subset: "mu", algs: ["R F R2 F'", "U' f U R' U' f'", "U' R' U' F' U' F R"] },
    {
      id: "mu-3",
      subset: "mu",
      algs: ["f' U f R'", "r' U' R U M'", "U' S U R' U' R S'", "U' f U R' U' R f'"],
    },
    {
      id: "mu-4",
      subset: "mu",
      algs: ["f' U2 f R2", "U' F' U' F R2", "r' U' R2 U M' R'", "U2 R' F R F' R"],
    },
    { id: "mu-5", subset: "mu", algs: ["F R F' R", "R' f R2 f'", "R' F R2 F'", "U R' U' F R2 F'"] },
    { id: "mu-6", subset: "mu", algs: ["f R' f'", "U F R2 F'"] },
    {
      id: "mu-7",
      subset: "mu",
      algs: ["R U2 R U R' S R' S'", "U2 R' U2 R2 U R' S R' S'", "F R2 U R' U' S R f'"],
    },
    { id: "mu-8", subset: "mu", algs: ["R' U2 R U S R S'", "U' R' D' r U r' U' D R"] },
    { id: "mu-9", subset: "mu", algs: ["F R2 f' U' S", "S' U S U R' U' R", "R U2 R' S' U' S R"] },
    {
      id: "mu-10",
      subset: "mu",
      algs: ["f R' U R' U' f'", "U' S R U R' U' R' S'", "U' R D r' U' r D' R'"],
    },
    {
      id: "mu-11",
      subset: "mu",
      algs: [
        "R' F' U' F2 R F'",
        "U R' U2 R' U' S R S'",
        "U2 R2 D r' U r D' R'",
        "R' U' R U S R' F R2 f'",
      ],
    },
    { id: "mu-12", subset: "mu", algs: ["R' U' S R S'"] },
    {
      id: "mu-13",
      subset: "mu",
      algs: [
        "R U2 R' U' S R S'",
        "U S U' R U2 R' U' R S'",
        "U' R' U' R2 U R' S R' S'",
        "U R D r' U r D' R'",
      ],
    },
    {
      id: "mu-14",
      subset: "mu",
      algs: [
        "S R U R2 U' S' R",
        "U' f U R' U' F' R S'",
        "U2 R' F' U' F2 R F' R",
        "U' R' U2 R U S R S' R",
      ],
    },
    { id: "mu-15", subset: "mu", algs: ["S' U' S R' U' R", "R U S R S' R"] },
    { id: "mu-16", subset: "mu", algs: ["R U R' S R' S'"] },
    { id: "mu-17", subset: "mu", algs: ["R U R' S' U' S R", "U' R' f' U' f2 R2 f'"] },
    {
      id: "mu-18",
      subset: "mu",
      algs: ["f' U' f2 R2 f'", "U R' U2 S R S' U R2", "U2 R' U' f R U R U' R' f'"],
    },
    {
      id: "mu-19",
      subset: "mu",
      algs: ["R' S' U' S R", "S R' S' U' S R S'", "U S R S' U R' U' R'"],
    },
    {
      id: "mu-20",
      subset: "mu",
      algs: [
        "R' f' U R' U2 R f",
        "U2 D' r U r' U' D R",
        "U S' U R U R' U' S R",
        "U S' U R U2 R' S U' R",
      ],
    },
    {
      id: "mu-21",
      subset: "mu",
      algs: [
        "f' R' U2 R U' f",
        "U R' S R F R2 f'",
        "S' U' R' U' R U' S",
        "U' R' U' f R2 U R' U' f'",
      ],
    },
    { id: "mu-22", subset: "mu", algs: ["f' R' U2 R f", "f' U R' U R f", "U S R' F R F' R S'"] },
    { id: "mu-23", subset: "mu", algs: ["R' U' R2 U2 S R' S'", "S' U' R U R' U' S R"] },
    {
      id: "mu-24",
      subset: "mu",
      algs: [
        "r' S U' R U S' M'",
        "U' D r' U r D' R'",
        "U R' S R F R2 f' R",
        "U S' U' R' U' R2 U' R' S",
      ],
    },
    { id: "mu-25", subset: "mu", algs: ["U2 S R' F R2 f'", "U' R U R' U' S R S'"] },
    { id: "mu-26", subset: "mu", algs: ["R2 U R' S' U' S R"] },
    {
      id: "mu-27",
      subset: "mu",
      algs: ["S' U' S R' U' F R F'", "U2 R' U' S R S' R' f R2 f'", "U' D' r U' r' D r' U' R U M'"],
    },
    {
      id: "mu-28",
      subset: "mu",
      algs: [
        "f R' S' f' U' S",
        "U' S' R S' R2 U' S R U' S",
        "S R' S' R2 S' U S R2",
        "U2 D r' U r D' R2 F R F'",
        "U2 R U' R2 S R S' R' F R2 F'",
      ],
    },
    {
      id: "mu-29",
      subset: "mu",
      algs: [
        "R' S R S' R' U' S R S'",
        "R S R' S' R' U' S R S'",
        "U2 S R' F R2 U R U' R' f'",
        "U R D r' U' r D' R2 F R F'",
      ],
    },
    {
      id: "mu-30",
      subset: "mu",
      algs: [
        "R' S R' S' R U' S R S'",
        "R' U' S R S' U2 S' U' S",
        "U R' f' U' f R2 S R' S'",
        "D r' U' r D' R F R' F'",
        "D' r U' r' D U f R' f'",
      ],
    },
    {
      id: "mu-31",
      subset: "mu",
      algs: [
        "R' U' S R S' f' U' f",
        "U R S R S' R2 F R' F'",
        "U' R' U2 R S R S' R2 F R' F'",
        "U D' r U' r' D R U R' f R' f'",
      ],
    },
    {
      id: "mu-32",
      subset: "mu",
      algs: [
        "S R' S' F R F' R",
        "S R S' R' f R2 f'",
        "U2 F' U' F D r' U r D' R'",
        "U2 D r' U' r U D' R F R' F'",
        "U R' F R F' D r' U r D' R'",
      ],
    },
    {
      id: "mr-1",
      subset: "mr",
      algs: ["F R2 F' U' R", "R2 U' R f R' f'", "U' S' R' U2 R S R", "U f R f' R' U' R2"],
    },
    { id: "mr-2", subset: "mr", algs: ["R2 F' U' F R"] },
    { id: "mr-3", subset: "mr", algs: ["f R f' R' U2 R2"] },
    {
      id: "mr-4",
      subset: "mr",
      algs: ["f R' f' U2 R", "f R' f' R U2 R", "R' U2 F' U' F R2", "U f U R U' f' R"],
    },
    { id: "mr-5", subset: "mr", algs: ["R' U R' F R2 F'"] },
    { id: "mr-6", subset: "mr", algs: ["R' f R' f'"] },
    { id: "mr-7", subset: "mr", algs: ["S R U' R' U R S' R"] },
    { id: "mr-8", subset: "mr", algs: ["R U2 R' U S R S' R"] },
    { id: "mr-9", subset: "mr", algs: ["R2 U' R S R' S'"] },
    { id: "mr-10", subset: "mr", algs: ["R U' R' S R S' R' U R2"] },
    { id: "mr-11", subset: "mr", algs: ["R U' R' U S R S' R"] },
    { id: "mr-12", subset: "mr", algs: ["R D' r U' r' D R2"] },
    { id: "mr-13", subset: "mr", algs: ["R2 U' R2 S R S' R", "U2 R U' R' U' S R S' R"] },
    { id: "mr-14", subset: "mr", algs: ["D r' U' r D' R'", "R' S R U R' U' R' S'"] },
    { id: "mr-15", subset: "mr", algs: ["S R' f' U2 F R", "U R2 U R2 S R S' R"] },
    { id: "mr-16", subset: "mr", algs: ["R' f' R' U2 R f"] },
    { id: "mr-17", subset: "mr", algs: ["f' R' U2 R f R"] },
    {
      id: "mr-18",
      subset: "mr",
      algs: ["S' U' R' U2 R S R", "R U R2 S R S' U R2", "R U R2 f R2 F' R S'"],
    },
    { id: "mr-19", subset: "mr", algs: ["S R S' R' U R2", "U2 S R S' R' U' R2"] },
    { id: "mr-20", subset: "mr", algs: ["R' S R S' U R2", "U2 R' S R S' U' R2"] },
    { id: "mr-21", subset: "mr", algs: ["S R S' R"] },
    { id: "mr-22", subset: "mr", algs: ["R' S R' S'"] },
    { id: "mr-23", subset: "mr", algs: ["R D' U r U' r' D R2"] },
    { id: "mr-24", subset: "mr", algs: ["R' f R S' R F' R", "U2 S R S' R' f R' f' R2"] },
    { id: "mr-25", subset: "mr", algs: ["U R' U2 R2 S R S'"] },
    {
      id: "mr-26",
      subset: "mr",
      algs: ["R U2 R2 S R S' U R2", "R U' R2 f' R' U2 R f", "R U2 R2 f R2 F' R S'"],
    },
    { id: "mr-27", subset: "mr", algs: ["R' S R S' R2 S' U' S", "U F R' F' R2 D r' U r D'"] },
    { id: "mr-28", subset: "mr", algs: ["f R' f' R U2 R S' U' S", "D r' U' r D' R2 F R F'"] },
    { id: "mr-29", subset: "mr", algs: ["S R S' R2 F R' F'"] },
    {
      id: "mr-30",
      subset: "mr",
      algs: [
        "y F' R U' R' M' U' M y'",
        "R' S R S' U2 S' U' S R2",
        "U' R' D' r U r' D f R' f'",
        "U' R' D' r U r' U D F R2 F'",
      ],
    },
    { id: "mr-31", subset: "mr", algs: ["R' B' R2 B R' S R S' R"] },
    {
      id: "mr-32",
      subset: "mr",
      algs: ["S R S' F R F'", "R S' U' S2 R' S' U R", "S R S' r U R U' r'"],
    },
  ],
});
