// Last X-Slot (LXS) — algorithm case data for @moishy/algsets.
//
// Transformed from old/lxs.ts via scripts/transform_old_algsets.ts.
// Every source alg is kept as an interchangeable variant; recognition is
// derived from the primary (first) alg of each case. See /DESIGN.md.
//
// Source flagged usesMccLookahead: true (a method-runner concern, step 8).

import { type AlgSet, defineAlgSet } from "../define.ts";

export const lxs: AlgSet = defineAlgSet({
  id: "lxs",
  name: "Last X-Slot (LXS)",
  cases: [
    {
      id: "lxs-1",
      algs: [
        "R U R'",
        "R U2 R' U R U2 R'",
        "R U' R' U' R U' R'",
        "U2 R U' R2 D' R U' R' D R",
        "R U' R D R' U2 R D' R2",
        "R U' R' U' R U R' U' R U' R'",
        "U' R' U2 R U R' U R2 U' R'",
        "R U' R D R' U' R D' R' U' R'",
        "U' R U R D R' U R D' R2",
        "R U R2 U2 R U R' U R",
      ],
    },
    {
      id: "lxs-2",
      algs: [
        "S' U2 S",
        "U2 S R2 S' R2",
        "R2 S R2 S'",
        "U R' U' R U R U R U' R'",
        "R U R2 U' R2 U R",
        "U' R U' R' S R2 S' R' U R'",
        "R' U' R2 U R2 U' R'",
        "U2 R' U2 R U2 R U R U' R'",
        "U R U R' S R2 S' R' U' R'",
        "U2 R U D' R U R' U2 D R'",
      ],
    },
    {
      id: "lxs-3",
      algs: [
        "R U' R'",
        "U R U2 R'",
        "U R U' R' U R U2 R'",
        "R U R' U' R U' R'",
        "R2 D R' U' R D' R2",
        "U R' U' R2 U' R2 U2 R",
        "R' U' R S R2 S' R' U R",
        "U R' U' R2 U' R' U R' U R",
        "R' U' R2 U R' S R2 S'",
        "U R2 D R' U2 R D' R2",
      ],
    },
    {
      id: "lxs-4",
      algs: [
        "R' U2 R U R U R",
        "U S R2 S' R' U R'",
        "U' S' U2 S R U R'",
        "U R U R' U S' U2 S",
        "U R U' D' R U' R' U' D R'",
        "U R U' R2 U' R U R2 U2 R'",
        "U R U R' U' S R2 S' R2",
        "U R U' R2 U' R U R U' R U' R'",
        "R' U2 R U R2 U' R' U2 R",
        "U R U' R' U' R' U' R2 U R",
      ],
    },
    {
      id: "lxs-5",
      algs: [
        "R U R' S' U2 S",
        "U2 R' U2 R U2 R2 U' R'",
        "R U2 R2 U' R2 U R",
        "R U R S R2 S'",
        "U2 R' U2 R U2 R U R U2 R'",
        "R U' R2 U2 R2 U2 R",
        "U' R2 U' R2 U R2 U R' U R'",
        "R U2 R' U R' U' R U R2 U2 R'",
        "R U R' U2 S R2 S' R2",
        "R U2 R' U R' U' R U R U' R U' R'",
      ],
    },
    {
      id: "lxs-6",
      algs: [
        "R U R' U' R U R'",
        "U' R U2 R' U2 R U R'",
        "U' R U R2 D' R U' R' D R",
        "U' R U' R' U2 R U R' U R U' R'",
        "U' R2 U R' U R U2 R' U2 R'",
        "U2 R U R' U R U' R' U' R U R'",
        "R U2 R' U R U R' U R U R'",
        "U2 R U2 R' U R' D' R U R' D R",
        "U2 R U2 R' U R U2 R' U R U R'",
        "U' R' D R2 U' R' U R2 D' R' U R'",
      ],
    },
    {
      id: "lxs-7",
      algs: [
        "R D' R U' R' U D R'",
        "R' U' R U D' R U' R' D R",
        "U S R2 S' R2 U' R U R'",
        "U' R' U' R U R U' R2 S R2 S'",
        "R2 U' R' U D R' U2 R D' R'",
        "U' S' U2 S U' R U R'",
        "U' R' U' R U' D R' U R U D' R",
        "U2 R U' R' S R2 S' R2 U' R U R'",
        "U' R U' R' U R D' R U' R' U D R'",
        "U' R' U' R U2 R S R2 S' R U' R",
      ],
    },
    {
      id: "lxs-8",
      algs: [
        "S R2 S' R' U2 R'",
        "U2 S' U2 S R U2 R'",
        "U' R' U' R U R2 U' R' U R U R'",
        "U2 S' U2 S U' R U' R'",
        "U2 R' U' R2 U' R U R' U R2 U' R'",
        "U' R U' D' R U R' U R U' R' D R'",
        "U' R D' R U' R' D R' U R U R'",
        "U' R' U' R2 S2 U R U' S2",
        "S R2 S' R2 U' R U' R'",
        "U' R U' R' U R U' D' R U R' U D R'",
      ],
    },
    {
      id: "lxs-9",
      algs: [
        "R' U' R U R2 U' R' U' R U R'",
        "U' R U R' S' U2 S R U R'",
        "U' R U R' U R' U2 R U R U R",
        "U2 R2 U' R' U2 R' U' R U' R U R2",
        "U' R2 U' R' D R' U' R D' R U R2",
        "R U R2 U' R U' R U2 R",
        "R U' R2 U' R' U R2 U R'",
        "R2 U' R' U D R' U2 R U D' R'",
        "R2 U' R' U R U R' U2 R U R2",
        "U' R U R' U2 S R2 S' R' U R'",
      ],
    },
    {
      id: "lxs-10",
      algs: [
        "R U R' U' S' U2 S",
        "R U2 R' S R2 S' R' U' R'",
        "R U' R' U' S R2 S' R' U' R'",
        "U2 R' U' R U R U R' U' R U R",
        "U R2 D' R U' R' U D R",
        "R U' R' U2 R' U' R U R2 U' R'",
        "R U' R' U S' U2 S R U' R'",
        "R U R' U S R2 S' R2",
        "R U R2 U' R U R U R U' R'",
        "R U R' U' R2 S R2 S'",
      ],
    },
    {
      id: "lxs-11",
      algs: [
        "R' U2 R2 U2 R",
        "R U' R2 U' R2 U R",
        "U' R U' R' S R2 S' R2",
        "R U2 R' S' U2 S",
        "U2 R' U2 R U2 R2 U2 R'",
        "U' S2 R U' R' S2",
        "U2 R' U2 R U2 R U' R U' R'",
        "U' R D' R U R' U2 D R'",
        "R U2 R S R2 S'",
        "R' U2 R2 U R U' R' U2 R",
      ],
    },
    {
      id: "lxs-12",
      algs: [
        "R U2 R' U R U R'",
        "U2 R U R' U2 R U R'",
        "R' D' R U R' D R",
        "U2 R' D' R U' R' D R",
        "U' R' D' R U2 R' D R",
        "U R2 D R' U' R D' R' U R'",
        "R U' R D R' U R D' R2",
        "U' R U' R' U R U' R' U' R U R'",
        "U2 R U' R' U R U R' U' R U R'",
        "U D R' U R U R' U2 R U' D'",
      ],
    },
    {
      id: "lxs-13",
      algs: [
        "R U2 R' U' R U R'",
        "R U' R' U R U R' U R U R'",
        "U' R U' R' U2 R U2 R' U R U' R'",
        "U' R U2 R' U R U' R' U2 R U R'",
        "U2 R U R' U' R U R' U2 R U' R'",
        "U' R U2 R' U' R U R' U R U' R'",
        "U' R U' R' U2 R U2 R' U2 R U2 R'",
        "U2 R U' R' U' R U2 R' U' R U R'",
        "U2 R U R' U' R U R' U' R U2 R'",
        "U2 R2 D R' U R D' R2 U' R U2 R'",
      ],
    },
    {
      id: "lxs-14",
      algs: [
        "R U2 R' U R' U' R U R",
        "U2 R U' R' U R' U2 R U2 R",
        "U2 R U R' U2 R' U' R U R",
        "R' U' R2 U R U' R U R'",
        "U2 R U' R' U R' U2 R2 U R' U R",
        "U' R U2 R' U R U' R2 U' R U R",
        "R D' R2 D R D' R D R",
        "U2 R U2 R' U R U R2 U' R U R",
        "R U2 R' U R' U' R2 U' R' U2 R",
        "R U2 R' U R' U' R U' R U R' U R",
      ],
    },
    {
      id: "lxs-15",
      algs: [
        "R U R' U2 R U' R'",
        "R U R' U' R U2 R'",
        "U' R U' R' U2 R U' R' U2 R U' R'",
        "U' R U R' U' R U R' U R U R'",
        "R U R' U' R U' R' U R U2 R'",
        "U' R U' R U R' U R U2 R' U R'",
        "U2 R U' R2 S2 R U2 R' S2 R",
        "U' R U2 R2 S2 R U' R' S2 R",
        "U' R U R D R' U R D' R' U R'",
        "U' R U R' U2 R U' R' U' R U R'",
      ],
    },
    {
      id: "lxs-16",
      algs: [
        "R' U' R2 U R",
        "R U' R' S' U2 S",
        "U R' U' R U R2 U2 R'",
        "U R' U' R U R U' R U' R'",
        "R U' R S R2 S'",
        "U R D' R U' R' U' D R'",
        "U R U2 R' U S' U2 S",
        "U R U R' S R2 S' R' U R'",
        "R' U' R D' R U R' D R2",
        "R' U' R2 U' R U R' U R",
      ],
    },
    {
      id: "lxs-17",
      algs: [
        "R' U' R U R2 U' R'",
        "U S R2 S' R' U' R'",
        "U R U' R' U' S' U2 S",
        "R' U' R U R U R U2 R'",
        "U2 R U' R' S R2 S' R' U' R'",
        "U' S' U2 S R U' R'",
        "U R U' R' U S R2 S' R2",
        "U2 R U2 R' U S R2 S' R2",
        "U R U' R2 U' R U R U R U' R'",
        "U' S' U2 S U R U2 R'",
      ],
    },
    {
      id: "lxs-18",
      algs: [
        "R' U2 R2 U R' U R2 U R'",
        "U R U2 R2 U' R U R2 U' R'",
        "U2 R U R' S' U2 S R U2 R'",
        "U R U2 R' U S R2 S' R' U' R'",
        "U R U' R U' R2 U2 R2 U R' U R'",
        "U' R U' R' U R U D' R U' R' U2 D R'",
        "U2 R U R' S' U2 S U' R U' R'",
        "U R U' R2 U' R2 U' R U2 R",
        "U' R U D' R U' R' U2 R U R' D R'",
        "U2 R' U' R2 U R' U2 R2 U' R2 U' R2",
      ],
    },
    {
      id: "lxs-19",
      algs: [
        "R U' R' U' S R2 S' R' U R'",
        "U R U R2 U2 R U R U R",
        "U' R' U' R' U R2 U R'",
        "R U' R' U2 R' U2 R U R U R",
        "R U' R' U S' U2 S R U R'",
        "U2 R' U2 R U2 R U R' U' R U R",
        "R U' R' S' U2 S R' U' R U R",
        "U R U R' U S R2 S' R' U R'",
        "U' R U2 R2 U' R U' R U2 R",
        "R U' R' U' R U R' U S' U2 S",
      ],
    },
    {
      id: "lxs-20",
      algs: [
        "R' U' R S' U2 S U' R",
        "U R D' R U2 R' U D R'",
        "U R2 U2 R' U D R' U' R D' R'",
        "U' R U' R' S' U2 S U R U R'",
        "U R' U2 R U2 R U2 R U R'",
        "U R' U2 R2 U R' U R U R U' R'",
        "R' S2 U2 R U R U S2 R",
        "U R U' R' U R' U' R' U' R U2 R",
        "R' U' R U2 S R2 S' R2 U' R",
        "R D' R U' R' U D R' U' R U R'",
      ],
    },
    {
      id: "lxs-21",
      algs: [
        "R' U' R U R U' R' U' R U R",
        "U2 R2 U' R2 U' R2 U R' U2 R'",
        "U2 R U2 R' S' U2 S R U R'",
        "R' U2 R' U R2 U R",
        "U2 R U2 R' U R' U2 R U R U R",
        "U' R' U' R U D R' U' R U D' R U' R",
        "U R U R2 U' R' U R2 U R'",
        "U2 R U2 R' U2 S R2 S' R' U R'",
        "R' U' D' R U' R' D R2 U2 R",
        "R U' R' U2 R D' R U R' D R'",
      ],
    },
    {
      id: "lxs-22",
      algs: [
        "R U R' S R2 S' R2",
        "R U' R' U2 R' U' R' U R",
        "U2 R U2 D' R U' R' U2 D R'",
        "R U2 D' R U R' U2 D R'",
        "U2 R U2 R2 U' R U R2 U R'",
        "R U2 R' U R' U2 R2 U2 R",
        "R U' R' U R U D' R U' R' D R'",
        "R U R' U2 S' U2 S",
        "S2 R U R' S2",
        "R U' R2 U' R' U R2 U2 R'",
      ],
    },
    {
      id: "lxs-23",
      algs: [
        "R' U2 R' U2 R2 U' R'",
        "R' U' S R2 S' R' U R2 U R'",
        "U2 R' U' R U R2 U R' S' U2 S",
        "U' R U R' U' R U R' S' U2 S",
        "U' R U R' U R' U2 R U2 R2 U' R'",
        "U2 R U2 R2 U2 R U2 R2 U' R'",
        "R' U2 R' U2 R U R U2 R'",
        "R D' R U' R' U R U' R' U D R'",
        "U2 R U2 R' U2 R U R' S' U2 S",
        "U2 R D' R U' R' U' R U R' U2 D R'",
      ],
    },
    {
      id: "lxs-24",
      algs: [
        "R U2 R2 U' R U R",
        "R D' R U R' U' D R'",
        "U R U' R' S' U2 S U R U' R'",
        "R U R2 U' R' U R2 U' R'",
        "U' R' U' R' U' R U2 R2 U' R'",
        "R' U' R U R U R2 S R2 S'",
        "R U2 R2 U' R2 U' R' U2 R",
        "R U' D' R U2 R' U2 D R'",
        "R U2 R2 U' R U' R U R' U R",
        "R U R2 U' S R2 S' R' U R",
      ],
    },
    {
      id: "lxs-25",
      algs: [
        "R U2 R' U2 R U' R'",
        "R U2 R' U' R U2 R'",
        "U2 R' S2 R2 U' R2 S2 R",
        "U R U R' U R U' R' U R U' R'",
        "U' R' S2 R U' R U' R2 S2 R",
        "U' R U R' U' R U' R' U R U R'",
        "U2 R U R' U R U' R' U2 R U' R'",
        "U' R U' R' U2 R U R' U2 R U' R'",
        "R U2 R' U2 R U R' U' R U' R'",
        "U R U' R' U' R U2 R' U R U' R'",
      ],
    },
    {
      id: "lxs-26",
      algs: [
        "R U' R' U' R U R'",
        "U R U R' U R U R'",
        "U2 R2 D R' U R D' R' U R'",
        "U R U' R2 D' R U R' D R",
        "U2 R' D' R U R' D R2 U R'",
        "U2 R U' R' U R U R' U2 R U' R'",
        "R' U' R U' R U R2 U R",
        "U' R U' R' U2 R U R' U' R U R'",
        "U' R U R2 D' R U2 R' D R",
        "U' R U R' U R' D' R U R' D R",
      ],
    },
    {
      id: "lxs-27",
      algs: [
        "R' U2 R2 U R' U R2 U' R'",
        "U' R' U' R2 U' R' U2 R2 U R'",
        "U2 S' U2 S U R U R'",
        "U' R U2 R' U2 R' U' R U R2 U R'",
        "U R U2 R' U S R2 S' R' U2 R'",
        "R' U2 R U2 R U R U R'",
        "U R' U' R U R U2 R' U' R U R",
        "R' U2 R2 U R' U R U R U2 R'",
        "U2 R2 U' R2 U' R2 U R2 U' R U R'",
        "R U' R2 U' R S' U2 S U' R",
      ],
    },
    {
      id: "lxs-28",
      algs: [
        "R U' D' R U' R' U2 D R'",
        "U' R' U' R U R U' R U R'",
        "R U' R2 U' R U R2 U R'",
        "U' R2 U' R' U R' D' R U' R' U' D",
        "U' R2 U' R' U R' D' R U' R' U2 D",
        "U' R2 U' R' U R' D' R U' R' U D",
        "U' R2 U' R' U R' D' R U' R' D",
        "R' U' R2 U' R' U R2 U R",
        "R' U2 R U2 R2 U' R' U R U' R'",
        "U' R2 U' R' U R' U D' R U2 R' U' D",
      ],
    },
    {
      id: "lxs-29",
      algs: [
        "R U' R' U R U' R' U R U' R'",
        "U R2 U2 R2 U' R2 U' R2",
        "U R U' R' U R U R' U R U' R'",
        "U R' U2 D' R U R' U D R",
        "U2 R U R' U' R U R' U R U' R'",
        "R U' R' U R U' R' U2 R U2 R'",
        "U R U2 R' U2 R U' R' U R U' R'",
        "U' R U R' U' R U R' U' R U R'",
        "U R U' R' U R U R' U2 R U2 R'",
        "U2 R U R' U R U' R' U2 R U R'",
      ],
    },
    {
      id: "lxs-30",
      algs: [
        "R' U2 R D' R U R' U D R",
        "R U' R' U R U' R2 U' R U R",
        "U R2 U' R' U' R U R' U R U R2",
        "R U' R' U' R U R' U R' U' R U R",
        "R U' R2 U' R D' R U' R' U2 D R",
        "U' R U2 R' U R U' R' U R' U' R U R",
        "U R U' R' U' R U R2 U2 R U2 R",
        "R U2 R' U2 R U R2 U' R U R",
        "U R' U2 R U R S R2 S' R U R",
        "U2 R U2 R' U R U R2 U2 R U2 R",
      ],
    },
    {
      id: "lxs-31",
      algs: [
        "R U' R' U R' U' R U R",
        "R' U' R2 U' R' U R' U' R U2 R",
        "U R' U' R U R2 U' R' U2 R U' R'",
        "R U' R U' R2 U' R2 U R' U R'",
        "R U' R' U R' U' R2 U' R' U2 R",
        "U R' U2 R D R' U R U D' R",
        "R U2 R' U2 R U' R2 U' R U R",
        "R U D' R2 D R D' R D R",
        "U R' U' D R2 D' R' D R' U D' R",
        "U2 R2 U2 R' U D R' U' R U2 D' R'",
      ],
    },
    {
      id: "lxs-32",
      algs: [
        "R U D' R U' R' U D R'",
        "S2 R U2 R' S2",
        "U2 R U2 R2 U2 R U2 R",
        "U2 D' R U' R' D R' U R U' R",
        "U' R U2 R' U' R' U' R U R",
        "U2 R' U' R2 U' R2 U R U R",
        "U2 S R2 S' R U' R' U R",
        "U2 R U' R' U' R' U2 R U2 R",
        "U2 R' U R' U' R D' R U R' U' D",
        "U2 R' U R' U' R D' R U R' U2 D",
      ],
    },
    {
      id: "lxs-33",
      algs: [
        "S' R U R' U R U R' S",
        "U' R U' R' U' R U R' S R2 S' R2",
        "U2 R U' R' U R' U2 R U2 R2 U R'",
        "U R U2 R' U2 R D' R U' R' D R'",
        "R U R' U R U R' S R2 S' R2",
        "U R' U2 R U R D' R U' R' U2 D R",
        "R U' R' U R' U' R U R U' R U R'",
        "U' S2 R U' R' S2 U' R U R'",
        "U2 R' U2 R U2 R U R U' R' U R U' R'",
        "U R' U' R2 U' R' U R U' R' U2 R2 U' R'",
      ],
    },
    {
      id: "lxs-34",
      algs: [
        "R U R' U R U' R'",
        "U2 R U' R' U2 R U R'",
        "R U R' U2 R U2 R'",
        "U' R U' R' U2 R U' R' U R U' R'",
        "R U R' U R U R' U' R U' R'",
        "U2 R2 U R2 U' R S R2 S' R'",
        "U R' U2 R U R' U R U' R U R'",
        "U2 R U R' U R U R' U' R U R'",
        "U2 R U2 R2 D' R U' R' D R",
        "U' R' U' R U R U R' U2 R' U2 R",
      ],
    },
    {
      id: "lxs-35",
      algs: [
        "S' U2 S U R U' R'",
        "U' R U2 D' R U' R' U D R'",
        "U2 R' S2 U2 R' U2 S2 R",
        "R U' R' U R U R' U' R' U' R U R",
        "R2 S R2 S' R U2 R'",
        "U R2 U' D' R2 D R D' R U D R'",
        "S2 R U2 R' S U2 S",
        "R' U' R U R U R' U' R' U' R U2 R",
        "R2 S R2 S' U' R U' R'",
        "U R U R' U' R U R' U' R' U' R U R",
      ],
    },
    {
      id: "lxs-36",
      algs: [
        "R' U' R U' R U R U R",
        "U R' S2 R U' R' U' R2 U S2 R",
        "U2 R U2 R' U R U' D' R U R' D R'",
        "U2 S R2 S' R' U R' U' R U2 R'",
        "U2 R U2 R' U R' U' R2 U' R' U R U R",
        "R' U' R U' R U R2 U' R' U2 R",
        "U2 R' U2 R U2 R2 U R' U2 R U' R'",
        "U' R U2 R' U R U R' U R' U' R2 U R",
        "U R2 U' R' U' R U2 R' U R U R2",
        "U2 R' U' R U' R U R U' R' U2 R2 U2 R'",
      ],
    },
    {
      id: "lxs-37",
      algs: [
        "R U R' U R' U' R U R2 U' R'",
        "R U R' S' U2 S R U' R'",
        "U2 R2 U2 R' U D R' U' R U D' R'",
        "R U R' S' U2 S U R U2 R'",
        "U R' U' R S' U2 S U' R2 U' R'",
        "R U R' U2 S R2 S' R' U' R'",
        "R U R' U R' U' R U R U R U2 R'",
        "R2 U' R2 U' R2 U R' U R' U' R U R'",
        "U' R U R' U R' U' R' U R2 U R'",
        "U R' S2 U' R U R2 U' R2 S2 R",
      ],
    },
    {
      id: "lxs-38",
      algs: [
        "R U' D' R U R' U D R'",
        "U R U2 R' S R2 S' R' U2 R'",
        "R' U' S2 U R U' S2",
        "U' R D' R U R' U R U' R' D R'",
        "U2 R U' R U' R' U2 R' U' R U' R U R2",
        "U' R' U' R' U R U R U R'",
        "U' R U' R' U S' U2 S U R U R'",
        "U' S2 R U2 R' S2 R U2 R'",
        "R' U' S R2 S' R' U R U R U' R'",
        "U2 R D R' U2 R U' D' R U R' U R'",
      ],
    },
    {
      id: "lxs-39",
      algs: [
        "R' U' R U R2 U R' U R U' R'",
        "U' R U2 R' S' U2 S R U2 R'",
        "U R' U2 R U R U' R' U2 R2 U' R'",
        "R' U' R U R2 U R' U2 R U2 R'",
        "U2 R U R2 U2 R' U2 R2 U' R'",
        "U' R U2 R' S' U2 S U' R U' R'",
        "U2 R U D' R U' R' U R U' R' U D R'",
        "U' R U2 R' U2 S R2 S' R' U2 R'",
        "R U' R' U R U R2 U' R U R2 U' R'",
        "U R U R' U' R U R' U R' U' R2 U R",
      ],
    },
    {
      id: "lxs-40",
      algs: [
        "R U2 R' U R U' R'",
        "R U2 R' U2 R U2 R'",
        "U2 R U' R' U' R U R' U R U' R'",
        "U' R U' R' U R U' R' U R U R'",
        "U R U2 R' U R U' R' U R U' R'",
        "U' R U' R U R' U R U2 R2",
        "U2 R U' R' U R U' R' U2 R U R'",
        "R U2 R' U R U R' U' R U' R'",
        "U2 R U' R' U' R U R' U2 R U2 R'",
        "U' R U2 R' U2 R U' R' U R U R'",
      ],
    },
    {
      id: "lxs-41",
      algs: [
        "R' U' R2 U' R' U2 R2 U' R'",
        "U2 R U2 R' U S R2 S' R' U R'",
        "U2 R U2 R2 U2 R U R U R",
        "R U R2 U2 R U2 R2 U' R'",
        "R' U' R D' R U' R' U2 D R2 U' R'",
        "R' U' R2 U' R' U2 R U R U2 R'",
        "R U R' U2 R U R' S' U2 S",
        "R' U2 R U R2 U' R' U2 R2 U2 R'",
        "R' U2 R U R2 U' R' U2 R U' R U' R'",
        "U' R2 S' R' S U S' R S2 R2 S'",
      ],
    },
    {
      id: "lxs-42",
      algs: [
        "R U R' U R' U' R2 U R",
        "U2 R U' R' S' U2 S R U R'",
        "U' R' U' R U R U' R U2 R'",
        "U' R' U' R U R U2 R U' R'",
        "U2 R U' R' U R' U2 R U R U R",
        "U2 R U' R' U2 S R2 S' R' U R'",
        "R U R' U R U' R' S' U2 S",
        "U' R' U' R U R U' R U' R' U R U2 R'",
        "R' U' R2 U2 R' U R' U' R2 U' R",
        "R U R' U2 R' U' R U R2 U2 R'",
      ],
    },
    {
      id: "lxs-43",
      algs: [
        "R U' R' U R U R'",
        "R2 D R' U R D' R2",
        "U' R2 U R' U R U2 R2",
        "R2 D R' U' R D' R' U2 R'",
        "R2 D R' U2 R D' R' U' R'",
        "U R' D' R U' R' D R2 U R'",
        "R U R2 D' R U R' D R",
        "U' R U' R' U2 R U' R' U R U R'",
        "U2 R U R' U R U' R' U R U R'",
        "U R U' R' U R U2 R' U2 R U' R'",
      ],
    },
    {
      id: "lxs-44",
      algs: [
        "R' U2 R' U2 R",
        "U' R U D' R U' R' D R'",
        "R' U' R' U R",
        "U2 R U2 R' S R2 S' R2",
        "U R U' R' U S' U2 S",
        "U R U' R' U' S R2 S' R2",
        "U R U2 R' S R2 S' R' U R'",
        "U R U D' R U' R' U' D R'",
        "U R U R' U' R' U' R2 U R",
        "U2 R U' D' R U R' U2 D R'",
      ],
    },
    {
      id: "lxs-45",
      algs: [
        "R' U2 R U2 R2 U R'",
        "U2 R' U' R2 U D' R U' R' D R",
        "R D' R U2 R' U' D R'",
        "U' R' U' R D R' U' R U D' R U R",
        "R2 U2 R' U D R' U' R U' D' R'",
        "U R U R D' R U' R' U D R",
        "U2 R U R' S' U2 S U R U R'",
        "U R2 U' R' U2 R' U' R U' R U R' U R'",
        "U' R' U2 R U R U D' R U' R' D R",
        "U' R' U' R U D' R U R' D R2 U R'",
      ],
    },
    {
      id: "lxs-46",
      algs: [
        "R U R2 U' R U R",
        "U' R U' R' U2 R' U' R U R",
        "R' U' S R2 S' R' U R",
        "U' R U R' U R' U2 R U2 R",
        "R U' D' R U R' U' D R'",
        "R' U' S R2 S' U' R' U2 R",
        "R U R2 U' R2 U' R' U2 R",
        "R' U' R U R' S R2 S'",
        "R' U' R' U R2 U' R'",
        "U R' U' R U' R U R2 U' R U2 R",
      ],
    },
    {
      id: "lxs-47",
      algs: [
        "R U2 R' U R' U' R U R2 U' R'",
        "R U2 R' S' U2 S R U' R'",
        "R U2 R' S' U2 S U R U2 R'",
        "R U2 R' U2 S R2 S' R' U' R'",
        "U' R D' R U R' U D R' U' R U R'",
        "U R U' D' R U2 R' U R U' R' D R'",
        "R U2 R' U R' U' R U R U R U2 R'",
        "U R U D R' U' R U2 D' R U R2",
        "U2 R' U2 R U2 R2 U2 R' U2 R U R'",
        "U R' U2 R2 U R U' R' U R' U' R U2 R",
      ],
    },
    {
      id: "lxs-48",
      algs: [
        "R' U2 R' U R U R",
        "U' R U2 R' U R' U' R U R2 U R'",
        "U2 R U' D' R U2 R' U' D R'",
        "U' R' U' R2 U R U2 R U R'",
        "R U2 R' U R U R' S' U2 S",
        "U2 R U' R2 U2 R U2 R2 U R'",
        "U R' U2 R U2 R2 U' R' U' R U R'",
        "R' U' R U' R U R2 U' R U R U R",
        "R' U2 S R2 S' U' R' U2 R U' R",
        "R' S2 U' R U S2 R",
      ],
    },
    {
      id: "lxs-49",
      algs: [
        "R2 U R' U2 D R' U' R U D' R'",
        "R U2 R' U R' U2 R U2 R2 U' R'",
        "U' R D' R U' R' U2 R U R' D R'",
        "R D' R U R' U2 D R' U' R U R'",
        "U' R U2 R' U R U D' R U' R' U2 D R'",
        "U' R' U' R2 U R S R2 S' R' U R'",
        "R U2 R' U' R U R' S' U2 S",
        "R U' R' S' U2 S U' R' U' R U R",
        "R U2 R' U' R U R S R2 S'",
        "U R' U2 R U R' U' R2 U R' U R2 U' R'",
      ],
    },
    {
      id: "lxs-50",
      algs: [
        "R U2 R' U R U2 R2 U' R U R",
        "U' R U2 R' U R U2 R2 U' R U R",
        "U2 R U2 R' U R U2 R2 U' R U R",
        "U R U2 R' U R U2 R2 U' R U R",
        "R U2 R' U R D' R U R' U' D R'",
        "U' R U2 R' U R D' R U R' U' D R'",
        "U2 R U2 R' U R D' R U R' U' D R'",
        "U R U2 R' U R D' R U R' U' D R'",
        "R U R' U2 R U2 R2 U' R U R",
        "U' R U R' U2 R U2 R2 U' R U R",
      ],
    },
    {
      id: "lxs-51",
      algs: [
        "R U' R2 U' R U R",
        "U2 R U R' U R' U' R U R",
        "U' R' U' R D' R U' R' U2 D R",
        "R' U' R D R' U' R U2 D' R",
        "R U D' R U R' U' D R'",
        "R' U' R U R S R2 S' R2",
        "U' R' U' R U D' R U2 R' D R",
        "R U' R2 U' R2 U' R' U2 R",
        "U2 R U R' U R' U' R2 U' R' U2 R",
        "U' R U' R' U2 R U R2 U' R U R",
      ],
    },
    {
      id: "lxs-52",
      algs: [
        "R' D' R2 U R U' R2 U' D",
        "R' D' R2 U R U' R2 U2 D",
        "R' D' R2 U R U' R2 U D",
        "R' D' R2 U R U' R2 D",
        "U' R U' R' U' S R2 S' R' U2 R'",
        "U2 R U' R' U2 R D' R U' R' D R'",
        "U' R' U2 R2 U R' U' R U2 R",
        "U R' U2 D R' U' R D' R' U' R",
        "U' R U' R' U S' U2 S R U2 R'",
        "U R U R' U R U' D' R U' R' D R'",
      ],
    },
    {
      id: "lxs-53",
      algs: [
        "R D' R U R' U D R'",
        "U2 R' U' R U R U2 R U R'",
        "U R U' R' U R' U' R U R2 U R'",
        "U2 R D' R U' R' D R' U' R U R'",
        "U2 R U' R D' R U' R' U D R",
        "U2 R' U' R U' R U R' U R U R U' R'",
        "U' R U R' U R U R' S' U2 S",
        "U R U' R' U R D' R U' R' U2 D R'",
        "S2 R U' R' S2 R U2 R'",
        "S2 R U' R' S2 U' R U' R'",
      ],
    },
    {
      id: "lxs-54",
      algs: [
        "R U' R' U R U R' S R2 S' R2",
        "U R2 U' D' R2 D R D' R D R'",
        "U2 R' U' R2 U' R' U R U' R' U R U R",
        "U2 R' U2 R U2 R U' R U' R' U R U' R'",
        "D' R2 U D R2 U' R D' R D R'",
        "U' R U D' R U' R' U R U' R' U2 D R'",
        "U2 R U' R U' R' U2 R' D' R U2 R' U' D",
        "U2 R U' R U' R' U2 R' D' R U2 R' U2 D",
        "U2 R U' R U' R' U2 R' D' R U2 R' U D",
        "U2 R U' R U' R' U2 R' D' R U2 R' D",
      ],
    },
    {
      id: "lxs-55",
      algs: [
        "R2 U2 R' U' R U' R2",
        "U' R2 U2 R' U' R U' R' U R'",
        "U2 R U' R2 D' R U2 R' D R",
        "R' U2 R U R' U R2 U R'",
        "U2 R U' R' U R' D' R U R' D R",
        "U2 R U' R' U R U2 R' U R U R'",
        "U2 R U2 R' U R U' R' U' R U R'",
        "U2 R U' R' U' R U R' U2 R U R'",
        "R U R' U' R U' R' U2 R U' R'",
        "U R' U' R U' R' U2 R2 U' R'",
      ],
    },
    {
      id: "lxs-56",
      algs: [
        "R' U' R U R2 U R'",
        "R D' R U' R' U2 D R'",
        "U R U R' U' S R2 S' R' U R'",
        "U2 R U' R U' R2 U2 R2 U R2",
        "R2 U' R' U2 D R' U R D' R'",
        "R D' R U' R' D R' U' R U' R'",
        "U' R' U2 R U2 R U' R' U' R U R",
        "R' U' R U R2 U2 R' U R U2 R'",
        "R' U' R U R2 U' R' U' R U' R'",
        "R' U' R D' R U' R' U2 D R2 U R'",
      ],
    },
    {
      id: "lxs-57",
      algs: [
        "R2 D R' U2 R D' R' U R'",
        "R' S2 R2 U R2 S2 R",
        "U R U' R' U' R U R' U' R U R'",
        "R U' R' U R U' R' U2 R U' R'",
        "R' D R' U' R U D' R U' R",
        "R' U2 R2 U R2 U R",
        "U2 R' U' R U' R' U2 R2 U R'",
        "R' D' R U2 R' D R2 U R'",
        "R' U2 R2 U R' U' R' U2 R",
        "R U' R' U R U' R' U' R U2 R'",
      ],
    },
    {
      id: "lxs-58",
      algs: [
        "R2 U' R2 U2 R2 U R2",
        "U' R' U' R U R2 U R' U' R U R'",
        "U2 R U' R U' R' U R' U' R U2 R U' R2",
        "R' U2 R U2 R2 U R' U R U' R'",
        "R U R' U2 R' U' R U R2 U R'",
        "U' D' R2 D R2 U' R2 D' R2 U' D",
        "U' D' R2 D R2 U' R2 D' R2 U2 D",
        "U' D' R2 D R2 U' R2 D' R2 U D",
        "U' D' R2 D R2 U' R2 D' R2 D",
        "R' U' S R2 S' R' U' R U2 R",
      ],
    },
    {
      id: "lxs-59",
      algs: [
        "R U' R' U' R U R' U2 R U' R'",
        "U' R U' R' U' R U R' U2 R U' R'",
        "U2 R U' R' U' R U R' U2 R U' R'",
        "U R U' R' U' R U R' U2 R U' R'",
        "R2 U2 R' U' R U' R' U2 R'",
        "U' R2 U2 R' U' R U' R' U2 R'",
        "U2 R2 U2 R' U' R U' R' U2 R'",
        "U R2 U2 R' U' R U' R' U2 R'",
        "R U' R' U' R U R' U' R U2 R'",
        "U' R U' R' U' R U R' U' R U2 R'",
      ],
    },
    {
      id: "lxs-60",
      algs: [
        "R U R U' R2 U' R2 U R2",
        "U R U R' U' R' U' R U R2 U R'",
        "U R U2 R' U' S R2 S' R' U R'",
        "U2 R' U2 R U S' U2 S U' R",
        "R' U' R2 U R2 U R'",
        "R U R' U' R D' R U R' D R'",
        "U R U2 R' U2 R' U2 R U R U R",
        "U R U2 R' U S' U2 S R U R'",
        "U R D' R U' R' U2 D R' U' R U R'",
        "U R U2 R' S' U2 S R' U' R U R",
      ],
    },
    {
      id: "lxs-61",
      algs: [
        "R' U' R U' D' R U R' U D R",
        "U' R' U2 R U D R' U' R U2 D' R",
        "U' R' U2 R U2 R S R2 S' R2",
        "R U' D' R U' R' U R U' R' D R'",
        "U2 R U' R' U R U2 R2 U' R U R",
        "U' R U' R' U R U R2 U2 R U2 R",
        "U R U R' U R U' R' U R' U' R U R",
        "R' U2 R U R2 U' R' U2 R2 U' R'",
        "U R D' R U' R' U R U2 R' D R'",
        "U2 R U' R' U R D' R U R' U' D R'",
      ],
    },
    {
      id: "lxs-62",
      algs: [
        "R' U2 R2 U R2 U' R U2 R",
        "U R U' R' U R U' R' U R' U' R U R",
        "U' R D' R U' R' U R U' R' D R'",
        "U' R' U2 R U2 R' S R2 S'",
        "U' R' U2 R' U2 R2 U2 R'",
        "U' R' U' R2 U R2 U' R2 U' R' U R",
        "U2 R U2 R' S R2 S' R2 U' R U R'",
        "U' R' U' S2 U' R U2 R U' S2",
        "U2 R U' R' U2 R D' R U' R' U D R'",
        "U' R' U2 R' U2 R U' R U' R'",
      ],
    },
    {
      id: "lxs-63",
      algs: [
        "R' U' R U R",
        "R' U' R2 U' R' U2 R",
        "R' U' R U' R U R' U R",
        "R' U' D' R U R' D R2",
        "U' R2 U' R2 U' R2 U R' U R'",
        "U2 R U2 R' U R' U2 R U2 R",
        "U' R' D' R U R' U' D R U R",
        "U R' U2 R U D' R U' R' U2 D R",
        "R U2 D' R U R' U' D R'",
        "U2 R' D' R U2 R' U' D R U R",
      ],
    },
    {
      id: "lxs-64",
      algs: [
        "R U R' U' R' U' R U R",
        "U' R' U' R U' R' U R U R",
        "U' R U R' S' U2 S U R U' R'",
        "U2 R U' R' U2 R U' R' U R' U' R U R",
        "R U' R' U R U D' R U' R' U D R'",
        "U R2 U' R2 U2 R2 U R' U2 R'",
        "U' R' U' D' R U' R' U D R U R",
        "U R' U2 R U2 R2 U' R' U2 R U' R'",
        "U R U' R' U' S' U2 S U R U' R'",
        "U' R U R S R2 S' R U2 R'",
      ],
    },
    {
      id: "lxs-65",
      algs: [
        "R U R' U2 R' U' R2 U R",
        "R U R' U' R' U' R U R2 U2 R'",
        "U' R U' R2 S2 U' R2 U S2 R",
        "R U R' U' R' U' R U R U' R U' R'",
        "U' R2 U' R' U R' U' R U2 R U' R' U R'",
        "R D' R U R' U R U R' D R'",
        "R U R' U2 R U' R' S' U2 S",
        "R U R' S R2 S' R2 U' R U2 R'",
        "R U R' U' R D' R U' R' U' D R'",
        "U' R U' R2 U' S R2 S' U R",
      ],
    },
    {
      id: "lxs-66",
      algs: [
        "R U' R' U2 R U' R'",
        "R U' R' U' R U2 R'",
        "U2 R2 U R' U R U2 R' U R'",
        "U' D R' U' R U2 R' U' R U' D'",
        "U' D R' U' R U2 R' U' R U2 D'",
        "U' D R' U' R U2 R' U' R U D'",
        "U' D R' U' R U2 R' U' R D'",
        "U2 D' R' D R U' R' D' R U' D",
        "U2 D' R' D R U' R' D' R U2 D",
        "U2 D' R' D R U' R' D' R U D",
      ],
    },
    {
      id: "lxs-67",
      algs: [
        "R U' D' R U' R' D R'",
        "R U2 R' U R' U' R' U R",
        "U2 R U R' U R D' R U' R' D R'",
        "R U2 R' U R' U2 R' U2 R",
        "R U' R2 U' R U R2 U' R' U R U' R'",
        "U R U R' U R U' R' U R' U' R2 U R",
        "R U' D' R U' R' U2 D R' U' R U' R'",
        "U2 R' U2 R2 U2 R2 U R'",
        "R' U2 R U2 R2 U2 R' U2 R U' R'",
        "U2 R' U' R2 U2 R2 S R2 S' U' R",
      ],
    },
    {
      id: "lxs-68",
      algs: [
        "R U R' U2 R D' R U' R' D R'",
        "U R U2 R' U R U' D' R U' R' D R'",
        "U2 R' U' R2 U' R' U R' U' R U2 R2 U' R'",
        "U' R' U' R D' R U' R' U2 D R U R U' R'",
        "U' R' U' R2 U' R' U2 R2 U' R' U' R U R'",
        "U' R' D R' U' R D' R' U' R U R U' R",
        "U2 R' S2 R2 U R2 U' R2 U S2 R",
        "R U' R' U' S' R U R' U R U R' S",
        "U2 R U' R' U R' U' R2 U' R' U2 R2 U' R'",
        "U S' R U' R' U' R' U' R S U R",
      ],
    },
    {
      id: "lxs-69",
      algs: [
        "R U D' R U' R' U2 D R'",
        "U2 R U R2 U' R U R2 U' R'",
        "R U R2 U' R U R2 U R'",
        "U' R' U' R' U R U' R U R'",
        "R U D' R U' R' D R' U' R U' R'",
        "U2 R U R2 U' R U R U R U2 R'",
        "R U' R' U2 R U R' S R2 S' R2",
        "U2 R U R' U' S' U2 S R U' R'",
        "U2 R U2 R2 U' R2 U' R U2 R",
        "U' R' U' R U R2 U2 R' U R' U' R U R",
      ],
    },
    {
      id: "lxs-70",
      algs: [
        "R' U2 R U R' U' R U2 R",
        "R' U2 R U R' U' R2 U R' U R",
        "U' S2 R U' R' S2 R U' R'",
        "U' R U R' U' R U R2 U' R U R",
        "R U R2 U2 R U R' U' R U2 R",
        "U2 R U' R' U R U' D' R U' R' U D R'",
        "R U' R2 U2 R U R' U' R U2 R",
        "U2 R U2 R' U' R U R2 U' R U R",
        "U R U R' U' R U R2 U2 R U2 R",
        "R' U2 R U R' U' R U R U' R' U2 R",
      ],
    },
    {
      id: "lxs-71",
      algs: [
        "R U2 R' U R U R' U R U' R'",
        "U R' S2 R2 U' R' U' R' S2 R",
        "R U R' U2 R U' R' U R U' R'",
        "R' U' R2 U' R' U R' U R2 U' R'",
        "U R U2 R' U R' D' R U' R' D R",
        "U2 R U R' U R' D' R U' R' D R",
        "U2 R U R D R' U' R D' R' U R'",
        "R' D' R U' R' D R U R U' R'",
        "U R U2 R' U R U R' U2 R U R'",
        "U2 R2 U R' U R' U' R2 U' R' U R'",
      ],
    },
    {
      id: "lxs-72",
      algs: [
        "R U2 D' R U' R' D R'",
        "R U R' U R' U' R' U R",
        "U' R U D' R U R' U D R'",
        "U2 R U R' S R2 S' R' U2 R'",
        "U2 R' U' R U R2 U R' U R U R'",
        "R U R' U R' U2 R' U2 R",
        "U R' D' R U R' U' D R U R2 U' R'",
        "U R' U' R2 U R' D R' U R D' R2",
        "U2 R' U' R U R U' R U' R' U' R U R'",
        "R2 U' R' U2 R' U' R U' R U R' U2 R'",
      ],
    },
    {
      id: "lxs-73",
      algs: [
        "R' U' R' U' R U2 R",
        "U2 R' S2 U' R2 U S2 R",
        "U' R U D' R U2 R' U D R'",
        "U2 R' U' S R2 S' U R",
        "R' U' R' U' R2 U R' U R",
        "U2 R' U' S R2 S' R U' R' U2 R",
        "R U R' U' S R2 S' R' U2 R'",
        "U R' U' S R2 S' U' R' U R U R",
        "R U' R' U R' U2 R U2 R2 U2 R'",
        "U2 R' U' R U' R2 U R U R",
      ],
    },
    {
      id: "lxs-74",
      algs: [
        "R' U' R U' R U2 R",
        "R' U' R U' R2 U R' U R",
        "R' U' R U' R U R U' R' U2 R",
        "R' U' R S' U2 S U R U2 R",
        "R' U' R U' D' R U2 R' D R2",
        "R' U' R U' D' R U R' D R U R",
        "U2 R' U' R2 U R' U2 R' U' R U' R2",
        "R' U' R S R2 S' R2 U' R U2 R",
        "R U2 R2 U' R' U R2 U R'",
        "R U' R U' R' U D R' U2 R U D' R'",
      ],
    },
    {
      id: "lxs-75",
      algs: [
        "R U' R2 U' R' U R",
        "R' U' R2 U' R' U2 R2 U2 R'",
        "R' U' R2 U' R' U2 R U' R U' R'",
        "U' R U' R' S' U2 S R U2 R'",
        "R U' R2 U2 R' U2 R",
        "U' R U' R' S' U2 S U' R U' R'",
        "R U' R' U R U' R' U S' U2 S",
        "U' R U' R' U2 S R2 S' R' U2 R'",
        "U R' U2 R U R U' R' U2 R2 U2 R'",
        "U R' U2 R U R U' R' U2 R U' R U' R'",
      ],
    },
    {
      id: "lxs-76",
      algs: [
        "R' U2 R U R U' R' U R U R",
        "U R U' R' U R U R' S' U2 S",
        "U R U' R U' R2 U R2 U R' U R'",
        "U R U R2 U2 R' U R U R",
        "U' R' U' R U R U2 R' U2 R U2 R",
        "U' R' U2 R2 U R U' R U2 R",
        "R' U R2 U R U' R U' R",
        "R' U R U' R' U R U R2 U' R",
        "R' U2 R U D' R U' R' U D R U R",
        "U R U' R' U R U2 R2 U' R2 U R",
      ],
    },
    {
      id: "lxs-77",
      algs: [
        "R U' R' S R2 S' R' U2 R'",
        "U' R U' R' U S R2 S' R' U R'",
        "U' R U' R2 U2 R U R U R",
        "U' R U' R' U' S' U2 S R U R'",
        "U' R' U2 R U2 R2 U' R' U R U R'",
        "U2 R' U' R U R U R U' R' U R U R'",
        "U' R U' R' U R U R' U S' U2 S",
        "U2 R' U R U' R2 U2 R U R2",
        "R U' R' S R2 S' R2 U' R U' R'",
        "D' R2 U R2 U' R2 D R' U R'",
      ],
    },
    {
      id: "lxs-78",
      algs: [
        "R D' R U R' D R'",
        "U R2 U' R2 U' R2 U R2",
        "U' R D' R U2 R' D R'",
        "R2 U' R2 U R2 U R2",
        "U2 R' U' R U R2 U2 R' U R U' R'",
        "U R' U' R2 U' R2 U R2 U R",
        "R2 U R' U2 D R' U' R U' D' R'",
        "D' R' D R2 U R2 D' R U' D",
        "D' R' D R2 U R2 D' R U2 D",
        "D' R' D R2 U R2 D' R U D",
      ],
    },
    {
      id: "lxs-79",
      algs: [
        "S2 R' U' R S2 U R",
        "U R U' R' U R U' D' R U' R' D R'",
        "U' R' U R U R2 U2 R' U R2",
        "U' R2 U2 R U R U' R' U R2",
        "R' U' R S R2 S' R2 U R",
        "R' U' R U2 S' U2 S U R",
        "R U' R' U R U R' U' S' U2 S",
        "R' U' R S R2 S' R' U' R' U2 R",
        "U' R' U' R2 U R' U R' U R U2 R2",
        "U R2 U2 R' U R' U D' R U' R' U' D",
      ],
    },
    {
      id: "lxs-80",
      algs: [
        "R' U' R U' R U R' U R2 U' R'",
        "R' U' R U R U R U R'",
        "U' R' U' R2 U D' R U R' D R",
        "R' U' R U' R U R' U R U R U2 R'",
        "R' U' R U' D' R U R' U D R2 U' R'",
        "U2 R U R' U R U' D' R U R' D R'",
        "U2 R U R' U R' U' R2 U' R' U R U R",
        "U2 R U' R' S R2 S' R' U R' U' R U2 R'",
        "R D' R U' R' U D R' U R U R'",
        "U R U' R2 U' R U R U R U R'",
      ],
    },
    {
      id: "lxs-81",
      algs: [
        "R' U' R U' R U R' U' R U2 R",
        "R' U' R U' R U R' U' R2 U R' U R",
        "U R D' R U R' U' R U R' U D R'",
        "R' U' R U' D' R U R' U' D R U2 R",
        "U' S2 R U2 R' S2 U' R U R'",
        "U2 R U' R' U2 R U2 R' U R' U' R2 U R",
        "U R' U2 R U2 R2 U R' U R' U' R U R",
        "U R U' R U' R' U2 R U' R' U' R U R' U R'",
        "U' R2 D' R U' R' U R U' R' D R",
        "U' R U2 R' U' R U R' S R2 S' R2",
      ],
    },
    {
      id: "lxs-82",
      algs: [
        "R U2 R' U2 R' U' R2 U R",
        "U R U2 D' R U2 R' D R'",
        "U R' D' R U R U R U' R2 U' D",
        "U R' D' R U R U R U' R2 U2 D",
        "U R' D' R U R U R U' R2 U D",
        "U R D' R U' R' U' R U R' D R'",
        "U R' D' R U R U R U' R2 D",
        "U R' U' R2 U' R U R U R",
        "U R U2 R' U R D' R U R' D R'",
        "R U2 R' U2 R U' R' S' U2 S",
      ],
    },
    {
      id: "lxs-83",
      algs: [
        "R U' D' R U' R' D R' U' R U R'",
        "U' R' U' R U R2 U2 R' U2 R U R'",
        "R U' R2 U' R U R U2 R U R'",
        "R U2 R D' R U' R' U D R",
        "U R2 U' R' U2 R U' R' U' R U R' U R'",
        "R U' R' U2 R D' R U R' U D R'",
        "U2 R U R' U' R U2 D' R U' R' D R'",
        "U R2 U' R' U2 R2 U R' U' R2 U R'",
        "U2 S' U2 S R U' R' U2 R U R'",
        "R U' R D R' U' R D2 R U' R' U D R",
      ],
    },
    {
      id: "lxs-84",
      algs: [
        "R U2 R' U2 R' U2 R2 U2 R",
        "R U2 R' U R U' R' S R2 S' R2",
        "U2 R U' R' U' R U R' U R' U' R2 U R",
        "U' R D' R U' R' U R U' R' U2 D R'",
        "R U2 R' U2 R U' R2 U' R2 U R",
        "R U2 R2 U2 R U2 R2 U2 R'",
        "R U2 R2 U2 R U2 R U' R U' R'",
        "U' R2 U2 R' S R2 S' U' R U' R2",
        "R U2 R' U2 R U2 R' S' U2 S",
        "U R D' R U2 R' U R U' R' D R'",
      ],
    },
    {
      id: "lxs-85",
      algs: [
        "R U' R' U' R U R' S' U2 S",
        "R U' R' U R' U2 R U2 R2 U' R'",
        "U2 R' U2 R U R' U' R U2 R2 U' R'",
        "U2 R U2 R2 S2 U' R2 U S2 R",
        "S' U2 S U' R' U' R U R",
        "U2 R U' R U' R' U R' U' R U2 R U' R' U R'",
        "R U' R' U' R U R S R2 S'",
        "U R U R' U R U R' U' S' U2 S",
        "U2 R U' R' U R U R' U2 R' U' R2 U R",
        "R U' R' U R' U2 R U2 R U R U2 R'",
      ],
    },
    {
      id: "lxs-86",
      algs: [
        "R' U2 R' U2 R2 U R'",
        "U' R U' R' U2 R' U' R U R2 U R'",
        "U2 R' U' R U R2 U R' U R' U' R U R",
        "U' R U' R' U2 R D' R U' R' U2 D R'",
        "U R U D' R U' R' U D R' U' R U R'",
        "R U R' U2 R D' R U R' D R'",
        "U R U R2 U' R S' U2 S U' R",
        "U R U R2 U2 R2 U R U R",
        "R' U' R2 U' R2 U R U R2 U R'",
        "U' R U' D' R U R' D R' U R U R'",
      ],
    },
    {
      id: "lxs-87",
      algs: [
        "R U' R' U R D' R U' R' D R'",
        "R' U2 R2 U2 R2 U' R'",
        "U R U' D' R U' R' U R U' R' U D R'",
        "R2 U' R' D R' U' R D' R U R' U' R'",
        "R U2 R' U2 R U' D' R U' R' D R'",
        "U2 R U2 R2 U2 R' U2 R2 U' R'",
        "R U' R' U R U' R' U R' U' R' U R",
        "U' R U' R2 U2 R2 U R' U R2 U' R'",
        "U R U' R2 U2 R' U2 R2 U' R'",
        "R U' R' U R' U' R U R2 U' R' U R U' R'",
      ],
    },
    {
      id: "lxs-88",
      algs: [
        "R2 U' R' U R' U' R U2 R U' R2",
        "U' R U' R2 U2 R U2 R2 U' R'",
        "U R2 U' R' U2 D R' U R U' D' R'",
        "U' R U' R' U2 R U R' S' U2 S",
        "U R U R2 U2 R U2 R2 U2 R'",
        "U R U R2 U2 R U2 R U' R U' R'",
        "U R U R' U2 R' U2 R2 U2 R",
        "U R U R' U R U' R' S R2 S' R2",
        "U' R' U2 R U2 R U' R' U2 R U2 R",
        "U R U R' U2 R U' R2 U' R2 U R",
      ],
    },
    {
      id: "lxs-89",
      algs: [
        "R' U' R U D' R U R' D R",
        "R' U' R U R2 U2 R' U R U R'",
        "U2 R U' R' U' R U R' U' R' U' R U R",
        "U R U' R2 U' R U D' R U R' D R",
        "U R U R' U' R U' R2 U' R U R",
        "R U2 R' U R U R' U R' U' R U R",
        "U R U R' U R U R' U R' U' R U R",
        "U S2 U' R U' R S R2 S",
        "U' R U R' U R U R2 U2 R U2 R",
        "U' R2 U' R2 U' R2 U R2 U' R U2 R'",
      ],
    },
    {
      id: "lxs-90",
      algs: [
        "R U' D' R U R' D R'",
        "R' U' R2 U' R' U R U R",
        "R U' R U' R2 U R2 U R2",
        "R' U' D' R2 U R' U' R2 U' D",
        "R' U' D' R2 U R' U' R2 U2 D",
        "R' U' D' R2 U R' U' R2 U D",
        "R' U' D' R2 U R' U' R2 D",
        "R' U' R D' R U' R' U D R U R",
        "R2 U' R' U' R2 U R U' R",
        "R' U' R2 U' R' U R2 U' R' U2 R",
      ],
    },
    {
      id: "lxs-91",
      algs: [
        "R' S2 R U' R' S2 R",
        "U R' S2 R U2 R' S2 R",
        "U2 R U' R D R' U' R D' R' U R'",
        "R U' R D R' U R D' R' U R'",
        "U' R' U' R' U' R U R U R",
        "R U' R' U' R U R' U R U R'",
        "U2 R U' R' U R' D' R U' R' D R",
        "U' R U' R D R' U2 R D' R' U R'",
        "R U' R' U2 R U' R' U' R U R'",
        "U' R2 U R' U R' U' R2 U' R2",
      ],
    },
    {
      id: "lxs-92",
      algs: [
        "R U2 R' U R' U' R2 U R",
        "R U2 R' U R U' R' S' U2 S",
        "U' R' U' R2 U R U' R U2 R'",
        "U' R' U' R2 U R U2 R U' R'",
        "R' U' R U R2 U2 R' U2 R U' R'",
        "R U2 R' U2 R' U' R U R2 U2 R'",
        "R U2 R' U2 R' U' R U R U' R U' R'",
        "U R U2 R' U R U' R' U R' U' R2 U R",
        "R U2 R' U R' U' R D' R U R' D R2",
        "R U2 R' U2 R D' R U' R' U' D R'",
      ],
    },
    {
      id: "lxs-93",
      algs: [
        "R' U2 R U2 R U' R U R'",
        "U2 R U2 R' S' U2 S U R U R'",
        "U' R U' R' U R U' R' U R' U' R2 U R",
        "U' R' U' R U' R' U R' U' R U2 R",
        "R U' R' U R U R' U R' U' R2 U R",
        "R U' R2 U' R U R U' R U2 R'",
        "R U' R2 U' R U R U2 R U' R'",
        "U R U' D' R U' R' U2 R U R' D R'",
        "U R2 U' R2 U' S2 R2 U R2 S2",
        "U' R' U' D' R U R' D R2 U R U' R'",
      ],
    },
    {
      id: "lxs-94",
      algs: [
        "R' U' R U R U' R U' R' U R U' R'",
        "R U' R' U R U' D' R U R' D R'",
        "R2 U2 R' U R' U R U' R U R2",
        "R' U' R U R U' R U' R' U2 R U2 R'",
        "U2 R U D R' U2 R U' D' R U R2",
        "U2 R U' D' R U R' U2 R U' R' D R'",
        "R U' R' U R' U' R2 U' R' U R U R",
        "U' R' U2 R2 U' R2 S R2 S' U' R",
        "U R U' R2 U' R U R2 U R' U R U' R'",
        "U2 R U R' U2 R U' D' R U R' D R'",
      ],
    },
    {
      id: "lxs-95",
      algs: [
        "R U R' U R' U' R U R2 U R'",
        "U R' U' R U R2 U R' U2 R U' R'",
        "U' R D' R U R' D R' U' R U R'",
        "R' U' D' R U R' D R U' R U R",
        "U' R U2 R' U R' U' R U' R U2 R",
        "U R' U' R2 U' R' U2 R U' R U R'",
        "R U' R' U R' U2 R' U R U R",
        "R U R' U R D' R U' R' U2 D R'",
        "R' U' R U R U' R U' R' U R' U' R U R",
        "R' U' R U' R' U R U R2 U2 R'",
      ],
    },
    {
      id: "lxs-96",
      algs: [
        "R U' R' U R U' R'",
        "R U' R' U2 R U2 R'",
        "R U' R' U R U R' U' R U' R'",
        "R' D' R U R' D R2 U' R'",
        "U2 R2 U2 R2 U' R2 U' R' U R'",
        "U2 R U R' U R U R' U R U' R'",
        "R U' R' U2 R U' R' U R U2 R'",
        "U2 R U R' U' R U' R' U2 R U R'",
        "R' D' R U2 R' D R U' R U' R'",
        "U R U' R' U' R U' R' U2 R U' R'",
      ],
    },
    {
      id: "lxs-97",
      algs: [
        "R U' R2 D' R2 U R U' R2 U' D",
        "R U' R2 D' R2 U R U' R2 U2 D",
        "R U' R2 D' R2 U R U' R2 U D",
        "R U' R2 D' R2 U R U' R2 D",
        "R' U' R' U' R U R' U' R U2 R",
        "R' U' R U R2 U2 R' U' R U R'",
        "R U' R2 D' R U R' U' D R' U R",
        "U2 R U' R' U' R U R' U2 R' U' R2 U R",
        "U' R U' R' U' R U R' U R' U' R' U R",
        "R U' R U' R' U2 R2 U R' U R U2 R",
      ],
    },
    {
      id: "lxs-98",
      algs: [
        "R U2 R2 U' R' U R",
        "U R U' D' R U2 R' D R'",
        "R U2 R2 U2 R' U2 R",
        "R' U2 R U R' U' R U R U R",
        "U R' U' R U R U' R' U2 R U2 R",
        "U R U' R' U R D' R U R' D R'",
        "U R2 U' R U2 R2 U' R' U' R",
        "R D R' U R U' D' R U2 R2",
        "U2 R U2 R U' R2 U' R2 U R2",
        "U R U D' R U' R' U' R U R' D R'",
      ],
    },
    {
      id: "lxs-99",
      algs: [
        "R U R2 U2 R U2 R",
        "R U R2 U2 R2 U R' U R",
        "U2 R U D' R U' R' U R U' R' D R'",
        "R U R2 U2 R U R U' R' U2 R",
        "R U' D' R U R' U' R U R' D R'",
        "R U D' R2 U2 R U2 R2 D R'",
        "R U' R' D' R U' R' D R' U R U' R",
        "U' S' U2 S R U' R' U R U' R'",
        "R U' R' U2 R U D' R U' R' U D R'",
        "U R' U' R S R2 S' R' U' R U2 R",
      ],
    },
    {
      id: "lxs-100",
      algs: [
        "R' U2 R U2 R",
        "R' U2 R2 U R' U R",
        "U R U' R2 U2 R U2 R",
        "R' U2 R U R U' R' U2 R",
        "U' R U2 R' U2 R' U' R U R",
        "U2 R U' R' U2 R' U2 R U2 R",
        "U' R U' R' U R U R2 U' R U R",
        "U2 R U2 R' U2 R' U2 R U2 R",
        "U2 R U R' U2 R' U2 R U2 R",
        "U R U' R2 U2 R2 U R' U R",
      ],
    },
    {
      id: "lxs-101",
      algs: [
        "R U R' U' R U' R' U R' U' R U R",
        "U' R U R' U' R U' R' U R' U' R U R",
        "U2 R U R' U' R U' R' U R' U' R U R",
        "U R U R' U' R U' R' U R' U' R U R",
        "R U D' R U' R' D R' U' R U2 R'",
        "U' R U D' R U' R' D R' U' R U2 R'",
        "U2 R U D' R U' R' D R' U' R U2 R'",
        "U R U D' R U' R' D R' U' R U2 R'",
        "R U2 R' U2 R U' R' U R' U' R U R",
        "U' R U2 R' U2 R U' R' U R' U' R U R",
      ],
    },
    {
      id: "lxs-102",
      algs: [
        "R U' D' R U' R' U D R'",
        "U R U' R' U' R' U' R U R",
        "U' R U' R' U' R U R2 U' R U R",
        "U2 R U2 R' S' U2 S U R U' R'",
        "R U' R2 U' R U D' R U' R' D R",
        "R U' R U' R' U D R' U2 R D' R'",
        "U' R' U' R U R U' R U' R' U2 R U' R'",
        "R' D' R U' R' U' R U R' D R2",
        "U R2 U R' U2 D R' U' R U2 D' R'",
        "R' D' R U' R' U' D R U R",
      ],
    },
    {
      id: "lxs-103",
      algs: [
        "R U R2 U' R' U R",
        "U' R U D' R U R' D R'",
        "R U R2 U2 R' U2 R",
        "R2 U' R' U2 R2 U R' U' R",
        "U R U' R U' R2 U' R2 U R2",
        "R2 S' R' U R2 U' R' S U R",
        "U2 R U D' R U2 R' U' D R'",
        "U2 R U R2 U2 R U2 R2 U R'",
        "R' U' R2 U R U' R' U2 R U2 R",
        "U' R U R U' R2 U R2 U R2",
      ],
    },
    {
      id: "lxs-104",
      algs: [
        "R U2 R' U R D' R U' R' D R'",
        "U R U' R' U R' U' R' U R2 U R'",
        "U R' U' S2 U R U' S U2 S",
        "R U R' U2 R U' D' R U' R' D R'",
        "U' R D' R U R' U D R' U' R U2 R'",
        "U' R U R' U' R U' D' R U R' D R'",
        "U R U' R' U' R U R2 U2 R U R U R",
        "U2 S2 U2 R' S R2 S R'",
        "U R' U' R U D' R U R' D R U R U' R'",
        "U2 R S2 R U2 R' S2 U2 R2",
      ],
    },
    {
      id: "lxs-105",
      algs: [
        "R U' R' U R' U' R U R2 U' R'",
        "R U' R' S' U2 S R U' R'",
        "U D' R' D R2 U' R2 D' R U' D",
        "U D' R' D R2 U' R2 D' R U2 D",
        "U D' R' D R2 U' R2 D' R U D",
        "U D' R' D R2 U' R2 D' R D",
        "R U' R' S' U2 S U R U2 R'",
        "R U' R' U2 S R2 S' R' U' R'",
        "U2 R' U' R U' R2 U R' U R2 U' R'",
        "R U' R' U R' U' R U R U R U2 R'",
      ],
    },
    {
      id: "lxs-106",
      algs: [
        "R U' R' U2 R' U' R2 U R",
        "U2 R U2 D' R U R' U D R'",
        "R U' R' U2 R U' R' S' U2 S",
        "U' R U' R' U S R2 S' R' U2 R'",
        "U2 R2 U' R' U2 D R' U R U D' R'",
        "R U' R' S R2 S' R2 U' R U2 R'",
        "U' R U' R' U' S' U2 S R U2 R'",
        "U' R' U2 R U2 R2 U2 R' U R U' R'",
        "U R2 U' R' U R' U R U2 R U R2",
        "D' R' D R2 U R' U R' D' R D",
      ],
    },
    {
      id: "lxs-107",
      algs: [
        "R U' R' U R' U' R2 U R",
        "R U' R' U R U' R' S' U2 S",
        "R U' R' U2 R' U' R U R2 U2 R'",
        "U R' U' R U R2 U' R' U R' U' R U R",
        "R U' R' U2 R' U' R U R U' R U' R'",
        "R' U' R2 U' R' U R' U' R2 U2 R",
        "R U' R D R' U R D' R U' R' U R",
        "R U' R' U R' U' R D' R U R' D R2",
        "U' R' U' R' U R U2 R U' R'",
        "U2 R' U2 R' U2 R U' R U R'",
      ],
    },
    {
      id: "lxs-108",
      algs: [
        "R' U' R U R U' R U' R' U R U R'",
        "R2 U' R' U2 R' D' R U2 R' U' D",
        "R2 U' R' U2 R' D' R U2 R' U2 D",
        "R2 U' R' U2 R' D' R U2 R' U D",
        "R2 U' R' U2 R' D' R U2 R' D",
        "R' U' R U D' R U' R' D R2 U R'",
        "U R' U2 R U2 R U' R U' R' U R U R'",
        "U' R U' R' U R U2 R' U R' U' R2 U R",
        "R U' D' R U' R' U R U' R' U2 D R'",
        "U R2 U2 R' U R U' R' U2 R U' R' U R'",
      ],
    },
    {
      id: "lxs-109",
      algs: [
        "R' U' R U' R U R' U R2 U R'",
        "U R' U' R U' R' U R2 U R",
        "U R' U' R2 U R U' R' U' R U R",
        "R U R' U' R D' R U' R' D R'",
        "U S' U2 S R' U2 R U2 R",
        "U R U' R' U R' U' R U' R U2 R",
        "U R D' R U' R' U' D R2 U' R' U R",
        "U R' U' D' R U' R' U D R2 U R",
        "U R U D' R U R' D R' U' R U R'",
        "R' U' R U R' U2 R' U' R U' R2",
      ],
    },
    {
      id: "lxs-110",
      algs: [
        "R' U' D R' U' R D' R' U2 R",
        "R U R' U R' U' R U' R U2 R",
        "R U' D' R U R' D R' U' R U R'",
        "U R U R' U R' U2 R U2 R2 U R'",
        "U R D' R U R' U R U' R' U2 D R'",
        "U2 R U2 R' U' R D' R U' R' D R'",
        "U' R2 U2 R2 S2 R U' R U' R2 S2",
        "R' U' D R' U' R U D' R' U R",
        "U R' U' D R2 D' R' D R' D' R U R",
        "U' R U' D' R U' R' U' R U' R' D R'",
      ],
    },
    {
      id: "lxs-111",
      algs: [
        "R U' R' U R U2 R' U R U' R'",
        "U' R U' R' U R U2 R' U R U' R'",
        "U2 R U' R' U R U2 R' U R U' R'",
        "U R U' R' U R U2 R' U R U' R'",
        "R U2 R' U R U' R' U R U R'",
        "U' R U2 R' U R U' R' U R U R'",
        "U2 R U2 R' U R U' R' U R U R'",
        "U R U2 R' U R U' R' U R U R'",
        "R U2 R U R' U R U2 R2",
        "U' R U2 R U R' U R U2 R2",
      ],
    },
    {
      id: "lxs-112",
      algs: [
        "R U2 D' R U R' D R'",
        "U2 R' D' R U R' U' D R2 U R",
        "R' U' R U R2 U' R' U2 R U R'",
        "U' R' U' R U R U R' U2 R U2 R",
        "U2 R U' R' U2 R' U2 R2 U2 R",
        "U2 R U' R' U R U' R' S R2 S' R2",
        "U2 R U' R' U2 R U' R2 U' R2 U R",
        "U2 R U' R2 U2 R U2 R2 U2 R'",
        "U2 R U' R' U2 R U2 R' S' U2 S",
        "R U' R2 U' R2 U' R' U R U R",
      ],
    },
    {
      id: "lxs-113",
      algs: [
        "R D' R U' R' D R'",
        "R U' R' U R' U' R' U R",
        "R' U' R U R2 U' R' U R U' R'",
        "R U' R' U R' U2 R' U2 R",
        "R' U' R U R2 U' R' U2 R U2 R'",
        "U' R' U' S2 U' R2 U S2 U R",
        "R' U' R U D' R U R' D R2 U' R'",
        "U R' S2 U' R' U S2 R",
        "D' R' D R2 U' R' U R' D' R U' D",
        "D' R' D R2 U' R' U R' D' R U2 D",
      ],
    },
    {
      id: "lxs-114",
      algs: [
        "R U' R2 U' R U R2 U' R'",
        "U' R U D' R U2 R' D R'",
        "R U' R' U S R2 S' R' U' R'",
        "R' U' R2 U' R U2 R",
        "R2 U' R2 U2 R2 U R' U R'",
        "R U' R2 U' R U R U R U2 R'",
        "R U' R' U' S' U2 S R U' R'",
        "U' R U' D' R U' R' U' R U R' D R'",
        "U R U' R' U' R D' R U' R' D R'",
        "U' R U R' U R D' R U R' D R'",
      ],
    },
    {
      id: "lxs-115",
      algs: [
        "R U' D' R U2 R' U D R'",
        "U' R U' R U' R' U R' D' R U' R' U' D",
        "U' R U' R U' R' U R' D' R U' R' U2 D",
        "U' R U' R U' R' U R' D' R U' R' U D",
        "U' R U' R U' R' U R' D' R U' R' D",
        "U' R U' R2 U' R U R U' R U R'",
        "U' R U' R U' R' U R' U D' R U2 R' D",
        "R D' R U R' D R' U' R U2 R'",
        "U' R D' R U R' U2 R U' R' D R'",
        "U' R U' R U' R' U R' U D' R U2 R' U' D",
      ],
    },
    {
      id: "lxs-116",
      algs: [
        "R U' R' U R U R' U R' U' R U R",
        "U' R U' R' U R U R' U R' U' R U R",
        "U2 R U' R' U R U R' U R' U' R U R",
        "U R U' R' U R U R' U R' U' R U R",
        "R U' R' U' R U' R2 U' R U R",
        "U' R U' R' U' R U' R2 U' R U R",
        "U2 R U' R' U' R U' R2 U' R U R",
        "U R U' R' U' R U' R2 U' R U R",
        "R U R2 U' R U D' R U R' D R",
        "U' R U R2 U' R U D' R U R' D R",
      ],
    },
  ],
});
