// BR Pair — algorithm case data for @moishy/algsets.
//
// Transformed from old/brPair.ts via scripts/transform_old_algsets.ts.
// Every source alg is kept as an interchangeable variant; recognition is
// derived from the primary (first) alg of each case. See /DESIGN.md.
//
// Region mask from the source (for a future signature projection; not yet
// wired — recognition currently uses the default full-facelet signature):
//   {
//     "CORNERS": {
//       "slots": [
//         5,
//         6,
//         7
//       ],
//       "pieces": [
//         5,
//         6,
//         7
//       ],
//       "orientation": [
//         0,
//         0,
//         0
//       ]
//     },
//     "EDGES": {
//       "slots": [
//         4,
//         6,
//         7,
//         9,
//         10,
//         11
//       ],
//       "pieces": [
//         4,
//         6,
//         7,
//         9,
//         10,
//         11
//       ],
//       "orientation": [
//         0,
//         0,
//         0,
//         0,
//         0,
//         0
//       ]
//     }
//   }
//
// Source flagged usesMccLookahead: true (a method-runner concern, step 8).

import { type AlgSet, defineAlgSet } from "../define.ts";

export const brPair: AlgSet = defineAlgSet({
  id: "brPair",
  name: "BR Pair",
  cases: [
    {
      id: "brPair-1",
      algs: [
        "R' U' F R2 F' R'",
        "U' R' U' F R2 F' R2",
        "U' R' U' f R2 f' R2",
        "R U R' U' R U' R",
        "R' U' F R2 F' U' R'",
        "U' R' U2 R U R' U' R",
        "R2 D R' U' R D'",
        "U' R' U' F R2 F' R' U R'",
        "R' U' F R2 F' U R'",
        "R' U' R U R2 U' R2",
      ],
    },
    {
      id: "brPair-2",
      algs: [
        "R' U2 R2",
        "U R U' R' U R2",
        "R U' R2 U' R2",
        "U' R U R' U2 R2",
        "U2 R' U2 F R2 F' R'",
        "R' U2 S R2 S'",
        "U2 R' S R2 S' R",
        "U2 R U R' U2 R U' R",
        "R' F R2 F' U2 R2",
        "U' R' U R' U2 R2",
      ],
    },
    {
      id: "brPair-3",
      algs: [
        "R' U' R2",
        "U R U' R' U' R2",
        "U2 R' f R2 f' R",
        "U R2 U' R' U' R2",
        "U2 R U2 R' U R2",
        "D R' U' R D' R",
        "R' U' R U' R U R",
        "R' U' S R2 S'",
        "U R F' U' F U' R",
        "U2 R' U' R' U' R",
      ],
    },
    {
      id: "brPair-4",
      algs: [
        "R U R' U R2",
        "U R U R' U R U' R",
        "U F U R U' F' R",
        "R U' R2 f R2 f' R",
        "R U' R' U2 R' U' R2",
        "D' R U R' U D R2",
        "U F R F' R2 U' R2",
        "U2 R U' R2 S R S' R'",
        "R' F R U R' U' R2 F'",
        "R' f R U R' U' R2 f'",
      ],
    },
    {
      id: "brPair-5",
      algs: [
        "R2 U' R2",
        "U R2 U2 R2",
        "U R U' R U' R2",
        "R2 U' R' U R'",
        "U' R' F R2 F' R'",
        "R2 U' R' U' R'",
        "U R2 U2 R' U R'",
        "U R U' R U' R' U R'",
        "R2 U' R' U2 R'",
        "U' R' F R2 F' U' R'",
      ],
    },
    {
      id: "brPair-6",
      algs: [
        "R U' R2",
        "U R U2 R2",
        "R U' R' U R'",
        "R U' R' U' R'",
        "U R U2 R' U R'",
        "R U' R' U2 R'",
        "U R' U' R2 U' R2",
        "R U' R U' R' U R",
        "U R U2 R' U2 R'",
        "R U' R2 F' U' F",
      ],
    },
    {
      id: "brPair-7",
      algs: [
        "R2",
        "R' U R'",
        "R U' R' U R",
        "R' U' R'",
        "U' R' F R2 F' R",
        "U2 R' U' R U' R2",
        "R' f R2 f' R'",
        "R' U2 R'",
        "U F R' F' R2",
        "U f R' f' R2",
      ],
    },
    {
      id: "brPair-8",
      algs: [
        "R2 U' R' U R2",
        "R U' R' U2 R2",
        "U' R' F R2 F' U R2",
        "U' R' f R2 f' U R2",
        "U R U' R U' R' U2 R2",
        "U' R' U' R U f R' f' R",
        "U R' U' R2 U' R' U R2",
        "U' f R f' R2 U' R",
        "U' R' U2 f' U f R",
        "D' R U' R' U2 D R2",
      ],
    },
    {
      id: "brPair-9",
      algs: [
        "R' U' R",
        "R' U' R2 U' R'",
        "R' U2 R U R",
        "R' U' R2 U R'",
        "U2 R' U' f R2 f' R",
        "R' U2 R2 U R",
        "R' U' R U' R U R'",
        "U R2 U2 R' U R2",
        "U f R2 f' R",
        "R' U' R U R U' R'",
      ],
    },
    {
      id: "brPair-10",
      algs: [
        "R U' R2 U' R",
        "R' U' R f R' f' R",
        "U R2 U R' U R2",
        "R2 U' R U' R",
        "U2 R U R' U R' U' R",
        "U' f U R' U' f' R",
        "U' R U R2 U' R U' R",
        "U2 R D' R U' R' D",
        "U2 R' U2 F R2 F' R2",
        "U2 R' U2 f R2 f' R2",
      ],
    },
    {
      id: "brPair-11",
      algs: [
        "R U2 R2 U' R",
        "U R U' R2 U2 R2",
        "U R U2 R2 U' R2",
        "R' U' R U' f R' f' R",
        "U2 R' U' R U2 R2 U' R2",
        "U' R' f R2 f' U R' U' R",
        "R2 U R' f R f' R2",
        "U2 R U' R U' R2 U2 R2",
        "R U2 R' S R' S' U' R",
        "U R2 U' R' U2 R2 U' R2",
      ],
    },
    {
      id: "brPair-12",
      algs: [
        "D' R U' R' D",
        "R U' F R' F'",
        "U R' U R' U' R",
        "U R F' U2 F R'",
        "R U' R U R2",
        "U R U2 F R' F'",
        "U R' f' U2 f R'",
        "U D' R U2 R' D",
        "U R' U2 f R2 f' R",
        "R U' F R2 F' R",
      ],
    },
    {
      id: "brPair-13",
      algs: [
        "R U R2",
        "F R' F'",
        "R U R' U R'",
        "R U R' U' R'",
        "R' U' R2 U R2",
        "R U R' U2 R'",
        "U2 R2 U R' U' R",
        "F R2 F' R",
        "F U R' U' F'",
        "U' F' U F R'",
      ],
    },
    {
      id: "brPair-14",
      algs: [
        "R' U' R U R2",
        "U R U R' U' R",
        "U R' U2 R U R2",
        "U2 R U R2 U' R",
        "R' U' F R2 F' R",
        "U2 F R' F' U' R2",
        "U2 f R' f' U' R2",
        "U2 F R2 F' R2",
        "U R' U2 F R2 F' R",
        "U2 f R2 f' R2",
      ],
    },
    {
      id: "brPair-15",
      algs: [
        "R",
        "R2 U' R'",
        "U2 R U2 R",
        "U2 R' U2 R",
        "U' R U R",
        "R2 U2 R'",
        "R U' R U' R'",
        "F R F'",
        "R2 U R'",
        "R F' U' F",
      ],
    },
    {
      id: "brPair-16",
      algs: [
        "R' U' R U' R",
        "R2 U' R2 U' R",
        "U2 R U2 R' U R U' R",
        "U' R f R' f' R",
        "F R F' U2 R",
        "D R' U' R U' D' R",
        "R' U' R U R U2 R",
        "R' U' R U R' U2 R",
        "U R' U2 R f R' f' R",
        "U' R D R' U' R D'",
      ],
    },
    {
      id: "brPair-17",
      algs: [
        "R U' R' U R U' R",
        "U' R' U2 R U' R",
        "U2 R2 U' R' f R' f' R",
        "U R U2 R' U2 R U' R",
        "U' R2 U2 R2 U' R",
        "U2 D R' U' R D' R U' R",
        "U2 R U' f R' f' R",
        "U' R' U2 R U R U2 R",
        "U' R' U2 R U R' U2 R",
        "U R2 U2 R' U2 R U' R",
      ],
    },
    {
      id: "brPair-18",
      algs: [
        "R U' R' U R' U' R",
        "U' R' U R' U' R2",
        "U2 R U R' U R' U' R2",
        "U R U2 R' U R' U' R2",
        "U' R D R' U R D'",
        "U' R2 U2 R' f R' f' R",
        "U R2 U2 R' U R' U' R2",
        "U2 R2 U R' U R' U' R2",
        "U' R2 U' R' U' f R' f' R",
        "U' R' F' U S' U' f R2",
      ],
    },
    {
      id: "brPair-19",
      algs: [
        "D' R U R' D",
        "R F' U F R'",
        "R' U R U' R",
        "R U F R' F'",
        "R F' U F U' R'",
        "U' R S R S' R'",
        "R U R U R2",
        "U' R2 U' R' S R S' R'",
        "R F' U F U2 R'",
        "R U' R2 f' U' f R2",
      ],
    },
    {
      id: "brPair-20",
      algs: [
        "R2 U R2 U' R",
        "U2 R f' U f R",
        "R F R2 F' R2",
        "U' S R2 S' R'",
        "U R2 U' R' U2 R U' R",
        "U' f R F' R S' R'",
        "U' f R2 S' R' F'",
        "U R' U' R U R U R2",
        "U S' U2 S R",
        "U' R U' R' S R2 S' R'",
      ],
    },
    {
      id: "brPair-21",
      algs: [
        "R' U2 R U2 R2",
        "U2 R2 U' R' U R U' R",
        "U2 R U' R' U2 R U' R",
        "U2 F R F' U R2",
        "U2 f R f' U R2",
        "R' U R U' R2",
        "U' R2 U2 R' U R U' R",
        "R' F' U' F R'",
        "U2 R' F R2 F' R' U R2",
        "U' f' U f R",
      ],
    },
    {
      id: "brPair-22",
      algs: [
        "R' U' R S R S' R",
        "U R F' U' F U' R2",
        "R2 U R' f R f'",
        "R' S' U' S R'",
        "F R F' R' U' R2",
        "R' U' S R S' R2",
        "U R U' R' S' U' S R'",
        "R2 U R' S R S'",
        "U F R' F' R f R f'",
        "U R F' U' F U' R' U R'",
      ],
    },
    {
      id: "brPair-23",
      algs: [
        "R' U' R f R f'",
        "U' R f R f'",
        "R' U' R S R S'",
        "U' R S R S'",
        "U R U R' f R' f'",
        "U' R' f R2 F' R' S'",
        "U' R U' R' U f R f'",
        "U' R' f R S' R F' R'",
        "U R U2 R' S R' S'",
        "R U' R f R f'",
      ],
    },
    {
      id: "brPair-24",
      algs: [
        "R U' R' S R' S'",
        "U' R2 U' R' f R f'",
        "R U2 R' f R' f'",
        "U' R2 U' R' S R S'",
        "U R U' R U' R' S R' S'",
        "R U' R' S R S' R2",
        "U' R' U' f R2 F' R' S'",
        "R U2 R2 F' U' F R",
        "U' R S' R U' R' S R",
        "R U' R' S R' f' U' F",
      ],
    },
    {
      id: "brPair-25",
      algs: [
        "R2 f' U' f R",
        "U F R' F' R2 U' R",
        "U2 R U2 R2 f' U' f R",
        "U' R U R2 f' U' f R",
        "U2 R2 U2 R2 f' U' f R",
        "R' U R f R f' R",
        "U' f R f' R2 U2 R2",
        "U' R2 U R2 f' U' f R",
        "R2 F' U' f R S'",
        "U' f R f' U' R2 U' R2",
      ],
    },
    {
      id: "brPair-26",
      algs: [
        "R' f R' f'",
        "U R' S R' S'",
        "U' R' U2 R f R f'",
        "R' f R2 F' R S'",
        "U S R S' R",
        "R' f R S' R F' R",
        "R' f' R' U2 R f",
        "U R' F' U F R2",
        "R' U' f' U f R'",
        "U' R' U2 R S R S'",
      ],
    },
    {
      id: "brPair-27",
      algs: [
        "R2 U2 R' f R f'",
        "U F R F' R' U' R",
        "U R' U' S R S' R",
        "R2 U2 R' S R S'",
        "U R' F R2 F' R2 U' R",
        "U R' f R2 f' R2 U' R",
        "U2 R' U2 S R S' R",
        "U2 R' f' R' U2 R f R",
        "U' R' U f R f' R",
        "U R' U2 F R2 F' U' R",
      ],
    },
    {
      id: "brPair-28",
      algs: [
        "R2 U' R' S R' S'",
        "R2 U2 R' f R' f'",
        "U R2 U R' f R' f'",
        "U R2 U2 R' S R' S'",
        "R F' U F U' R2",
        "R U' R' U S R' S'",
        "U R U' R2 U' R f R f'",
        "R2 U' R' S R S' R2",
        "R' F R F' R' U' R",
        "U R F' U F U R2",
      ],
    },
    {
      id: "brPair-29",
      algs: [
        "R' F R S R f'",
        "U R' U' F R S R f'",
        "F R S R f'",
        "U' R' U' R U f R f' R",
        "U' R' U2 f' U' f R",
        "U' R F U R2 U' F'",
        "R' F R2 F' R' f R f'",
        "U2 f R' f' R2 U' R2",
        "U' R F U R' U' R' F'",
        "U' R U R f R f'",
      ],
    },
    {
      id: "brPair-30",
      algs: [
        "R2 U' R' f R f' R",
        "U R U2 R' U f R' f'",
        "U F R' F' R U' R2",
        "R U' f R f' R",
        "R U' F R' S R' f'",
        "U R U' R' f' R' U' R f",
        "U2 R' U f' U' f R",
        "U2 R' U2 R U f R f' R",
        "U2 R F' U' F U2 R2",
        "R' U' f R2 F' R' S' R",
      ],
    },
    {
      id: "brPair-31",
      algs: [
        "R' U' R f R f' R",
        "U2 R' f' U' f R",
        "U' R f R f' R",
        "U' R F R' S R' f'",
        "U' R' f R2 F' R' S' R",
        "U R U R' U f R' f'",
        "R' F R U R' U' F' R",
        "U' f U R U' R2 f'",
        "R' F R U R' U' R F'",
        "R' f R U R' U' R f'",
      ],
    },
    {
      id: "brPair-32",
      algs: [
        "R' F R2 F'",
        "R' f R2 f'",
        "U' f R' f'",
        "F R F' R",
        "U R' U' F R2 F'",
        "U R' U' f R2 f'",
        "F R2 F'",
        "f R2 f'",
        "R F R2 F'",
        "U' R' U' R f R' f'",
      ],
    },
    {
      id: "brPair-33",
      algs: [
        "f R f' R",
        "U' R' U' f' U' f R",
        "U R U' R' f R f' R",
        "D f R f' D' R",
        "f R S' R F'",
        "U' R' U' F' U' f R S'",
        "F R' S R' f'",
        "R' f R2 f' R' f R f'",
        "f R f' U' R' U R",
        "U' R' U' f' U' f R2 U' R'",
      ],
    },
    {
      id: "brPair-34",
      algs: [
        "R' f R S' R F'",
        "R' f R f' R",
        "U R' U' f R S' R F'",
        "U R' U' f R f' R",
        "U2 F R F' R2 U' R",
        "U' R' f' R' U' R U' f R",
        "U R U F' R' U' R F",
        "U R U' R2 f R S' R F'",
        "R U2 F' R' U' R F",
        "U R' f R2 U R' U' f' R",
      ],
    },
    {
      id: "brPair-35",
      algs: [
        "f' R' U' R f",
        "R U' R' U f R' f'",
        "R' U' R S R' S' R",
        "U' R' f' U R' U' R f",
        "f' R' U' R U f",
        "f' R' U' R U' f",
        "F' R' U' R F",
        "R' U' f' U' f R U R",
        "R F R' F' R' U' R",
        "U2 R U' R' f' U' f R",
      ],
    },
    {
      id: "brPair-36",
      algs: [
        "R2 U2 R' U f R' f'",
        "R' U2 R S' U' S R",
        "R2 U' R' f' R' U' R f",
        "R F R' F' R U' R2",
        "R' U2 R U' f R f'",
        "R U' R U' f R f' R",
        "U' R' U2 R2 U R' f R' f'",
        "U' f R' f' R U' R U R2",
        "U' f R f' U R' f R f'",
        "U' f R D R2 D' f'",
      ],
    },
    {
      id: "brPair-37",
      algs: [
        "R U R' f R f'",
        "R U R' S R S'",
        "R2 U' R' S R' S' R",
        "U2 F R' f' U' S R",
        "f R f' R' f R f'",
        "U R2 U R' U f R' f'",
        "R U R' S R' S' R2",
        "R2 F R' F' R'",
        "f R S' R' S R f'",
        "F R' F' U' R U R2",
      ],
    },
    {
      id: "brPair-38",
      algs: [
        "f R f'",
        "S R S'",
        "U2 F R' F' U' R",
        "U S' U' S R",
        "U R F' U2 F R2",
        "U' R U f R f'",
        "U R U f R' f'",
        "U R U2 F R2 F'",
        "U R f' U f R'",
        "U' R' U f R f'",
      ],
    },
    {
      id: "brPair-39",
      algs: [
        "R U' R' f R f'",
        "R U' R' S R S'",
        "R U' R' S R' S' R2",
        "R2 U' R2 S R S'",
        "R U' F R' S R f'",
        "R' f R U' f R f2",
        "S' R U' R' S R",
        "U' R U R U' R' f R f'",
        "U R U2 F R' S R' f'",
        "R2 U' R2 f R f'",
      ],
    },
    {
      id: "brPair-40",
      algs: [
        "R' U' R U f R' f'",
        "U' R' U' R U' f R f'",
        "R' U2 S R S'",
        "U' R U2 R' f R f' R",
        "R' U2 f R f'",
        "U' R U' R' U' f R f' R",
        "U' R' U' R S' U' S R",
        "R U2 R' S R S' R",
        "U R U R' S R S' R",
        "U' R' U' R U' S R S'",
      ],
    },
    {
      id: "brPair-41",
      algs: [
        "R F' R' U' R F",
        "U' R' S R S' R",
        "U' R' F R2 F' R' U' R",
        "U' R' f R2 f' R' U' R",
        "U' R S R' S' R",
        "U' R' U' F R2 F' U' R",
        "U' R' U' f R2 f' U' R",
        "R2 U' R' U f R' f'",
        "R F' R' U' R U' F",
        "U R F' U F U2 R",
      ],
    },
    {
      id: "brPair-42",
      algs: [
        "R U2 R' f R f'",
        "R U2 R' S R S'",
        "U2 R F R' F' U' R",
        "f R F' R' S' R",
        "U2 R U R' U f R f'",
        "U R' F R F' R U' R",
        "U2 R' U2 R S R' S' R",
        "U2 R' U' R f' R' U' R f",
        "R U2 R' S R' S' R2",
        "R U2 F R' S R f'",
      ],
    },
    {
      id: "brPair-43",
      algs: [
        "f R' f' R",
        "D R' U' R D'",
        "U R U' R' f R' f' R",
        "U2 D R' U R D'",
        "U2 R2 U R' U' R2",
        "f R' S' R F'",
        "U' R' U' f' U f R",
        "U R2 U2 R' U2 R2",
        "U2 R U2 R' f R' f' R",
        "U D R' U2 R D'",
      ],
    },
    {
      id: "brPair-44",
      algs: [
        "S R S' R'",
        "f R S' R' F'",
        "R U' R' S R S' R'",
        "S R S' U' R'",
        "R U2 R' S R S' R'",
        "R U R' S R S' R'",
        "S R S' U R'",
        "R U' R' S R S' U' R'",
        "f R S' R2 F' R",
        "f R f' R U R2",
      ],
    },
    {
      id: "brPair-45",
      algs: [
        "R' f R2 S' R' F'",
        "R' S R2 S' R'",
        "R2 U R2 U' R2",
        "R U R' f R' f' R",
        "R F R2 F' R'",
        "R' f R2 f' R U R2",
        "R' f R2 S' R2 F' R",
        "R' S R2 S' U' R'",
        "R' U' F' U' F R U R2",
        "R U' R U R' U' R2",
      ],
    },
    {
      id: "brPair-46",
      algs: [
        "R2 U' R' U' R",
        "U2 R' U R2",
        "U2 f R f' U' R",
        "U' D' R U' R' D R2",
        "U2 R U' R2 U R2",
        "U2 R2 F R' F'",
        "U' R U R U' R' U' R",
        "R2 U' R' U R' U2 R",
        "U' D' R U R' U2 D R",
        "U R U' R U' R' U' R",
      ],
    },
    {
      id: "brPair-47",
      algs: [
        "R F' U F2 R' F'",
        "R' f' U' f U2 R2",
        "R2 U R' U' R U R2",
        "R F' U F R U R2",
        "R2 U2 R' U2 R U R2",
        "R2 U' F R2 F' R2",
        "R2 U' R' U' S R2 S' R'",
        "R2 U' f R2 f' R2",
        "R F R' F' R2 U R2",
        "R U' F' U F2 R' F'",
      ],
    },
    {
      id: "brPair-48",
      algs: [
        "R' U' R2 U2 R2",
        "R' U2 R2 U' R2",
        "R' U' R2 U2 R' U R'",
        "R' U2 R2 U' R' U R'",
        "R' U2 R U R U2 R2",
        "R' U' R U' R U' R2",
        "R' U2 R2 U' R' U' R'",
        "f R' f' U' R U2 R2",
        "R' U' R2 U2 R' U2 R'",
        "R' U2 R2 F R' F' R2",
      ],
    },
    {
      id: "brPair-49",
      algs: [
        "R' U' R U2 R2",
        "R' U2 R U' R2",
        "R2 U2 R' U R' U' R",
        "R U' R' U R' U R2",
        "R' U2 R f R' f' R2",
        "R' U' R U' f R' f' R2",
        "f' R' U R f R",
        "R' U' f' U f U R2",
        "R U2 R U' R' U' R",
        "F R' F' U R2",
      ],
    },
    {
      id: "brPair-50",
      algs: [
        "R2 U' R",
        "U R U' R U' R",
        "U' R' F R2 F' R2",
        "U' R' f R2 f' R2",
        "R2 U2 R' U R",
        "R' U' f' U' f R2",
        "U' R' F R2 F' R' U R'",
        "U' R' U' R U R' U' R",
        "U' R' f R2 f' R' U R'",
        "U2 R U2 R U' R",
      ],
    },
    {
      id: "brPair-51",
      algs: [
        "R2 U' R' U R U' R2",
        "F R F' U R U' R2",
        "R' F R2 F' U R U' R2",
        "R2 U' R' U2 R U2 R2",
        "R' f R f' R2 U' R",
        "R2 U' R2 F R F' R'",
        "R F' U2 F R U2 R2",
        "R' F R2 F2 U' F R'",
        "F R F' R' F R F' R'",
        "R' U R2 U' R' U R2",
      ],
    },
    {
      id: "brPair-52",
      algs: [
        "R2 U' R' U R' U' R2",
        "f R F' R' S' R'",
        "R' U' R U2 R U R2",
        "f R F' R' S' U R'",
        "f R F' R' S' U' R'",
        "R' U' D' R U2 R' D",
        "F R2 F' R' U' R2",
        "f R2 f' R U' R2",
        "f R f' U R U' R2",
        "R' U2 R U' R U R2",
      ],
    },
    {
      id: "brPair-53",
      algs: [
        "F R F' R2",
        "f R f' R2",
        "R U R U' R",
        "F R F' R' U R'",
        "R' F' U F R'",
        "f R f' R' U R'",
        "f R F' R2 S'",
        "F R F' R' U' R'",
        "f R f' R' U' R'",
        "R' U R U R2",
      ],
    },
    {
      id: "brPair-54",
      algs: [
        "R' f R f'",
        "R' S R S'",
        "U' R F R' F' R'",
        "D f R f' D'",
        "U2 D f R' f' D'",
        "R' U' R U f R f'",
        "R U' F R' F' R'",
        "U' R U' R U' R' f R' f'",
        "U' R U' R' S R' S' R",
        "R' f R S' R' F' R",
      ],
    },
    {
      id: "brPair-55",
      algs: [
        "D R' U' f' U' f R D'",
        "f D R2 D' R' f' R",
        "D R' S' U' S U' R D'",
        "R2 F' U' F2 R2 F' R'",
        "f R2 U R2 U' R f' R",
        "D R' U2 R f R f' D'",
        "R' f R2 S' R2 S R f'",
        "R2 U R2 U' S R S' R",
        "R' f R D R2 D' f'",
        "f D R2 D' R' S' R F'",
      ],
    },
    {
      id: "brPair-56",
      algs: [
        "R2 U' R2 f' U' f R",
        "f R' S' R S R' f' R",
        "R2 U' R2 F' U' f R S'",
        "R' S U' R U S' R",
        "f R' f' R S R' S' R",
        "F R F' R U' R' U2 R2",
        "R' f R S' D R D' F'",
        "f R2 f' R' f R f' R",
        "D R' D' S' D R D' S",
        "D' R' D S' D' R D S",
      ],
    },
    {
      id: "brPair-57",
      algs: [
        "R2 U' R' f R' f'",
        "R S R' S'",
        "R F' U F R2",
        "S R' S' R",
        "R F' U F R' U R'",
        "R' F R S R' f' R",
        "R U F R' F' R'",
        "F D R' D' F'",
        "R S R S' R2",
        "R' f' U' f U R",
      ],
    },
    {
      id: "brPair-58",
      algs: [
        "R' U R f R f'",
        "U' R2 U R' f R f' R",
        "R' F R S R f' U' R",
        "R' U R S R S'",
        "U' R' U' R2 U R' f R' f'",
        "U f R f' R' U R U' R",
        "U2 R f' U' f R",
        "U f R' U R2 U' f'",
        "U S R2 F R' f'",
        "U f R2 S' R' F' U' R",
      ],
    },
    {
      id: "brPair-59",
      algs: [
        "R' U2 R S R' S' U' R2",
        "D f R f' D' R' U R2",
        "R2 U R2 f R S' R F'",
        "f R D R' D' f' R",
        "R2 U' F' R' U' R F",
        "R' U2 R2 F' U' F U' R2",
        "R2 U R2 f R f' R",
        "R' U R2 U R' f R f'",
        "R' U2 S R S' R2 U' R2",
        "R' U2 F' U' F U' R2",
      ],
    },
    {
      id: "brPair-60",
      algs: [
        "R F' U' F R",
        "F R F' U' R",
        "R' F R2 F' U' R",
        "R' f R2 f' U' R",
        "R U' F' U' F R",
        "R U' R f R' f'",
        "R2 U' R' U' f R f'",
        "R U F' U' F R",
        "R F' U2 F U R",
        "R2 U' R' S' U' S R",
      ],
    },
    {
      id: "brPair-61",
      algs: [
        "R' f R S' R F' U' R",
        "F' U' F R' U R2",
        "R S' R U' R' S U' R",
        "R U' f' U' f R",
        "F' U' R' U R F R",
        "R' U2 F R F' R' U' R",
        "R U' f' U f R U R2",
        "F' U' F R2 F R' F'",
        "R U' F' U F f R' f'",
        "R U' f' U F f R' F'",
      ],
    },
    {
      id: "brPair-62",
      algs: [
        "R' U2 F R2 F'",
        "R' U2 f R2 f'",
        "U R' f' R' U' R f",
        "R' U' F' U' F R2",
        "R' U f R' f'",
        "R' f' U2 f R2",
        "U' R' U2 R f R f' R",
        "U R' f' R' U' R U f",
        "U R' f' R' U' R U' f",
        "U' R F' U' F U R2",
      ],
    },
    {
      id: "brPair-63",
      algs: [
        "R' f D R D' R' f'",
        "R' U2 F R S R f'",
        "S R S' U R U' R",
        "R' f R' f' R2 U' R2",
        "f' R' U R f U R2",
        "R U' F R F' R U' R",
        "f R S' U R U' F' R",
        "R' F' U2 F R f R f'",
        "R' f R2 f' R f R f'",
        "F' R' U R F U R2",
      ],
    },
    {
      id: "brPair-64",
      algs: [
        "R' U2 f R S' R F'",
        "R' U2 f R f' R",
        "R' U' F' U' f R S' R",
        "R' F' U2 f R S' R",
        "R' U R' U' f' U' f R",
        "R2 S' R' U' R S U' R",
        "R2 U' R U' R' f R f'",
        "R' f R f' U R2 U' R",
        "R' f' U2 f S R S' R",
        "R' U2 f R f' R2 U' R'",
      ],
    },
    {
      id: "brPair-65",
      algs: [
        "R F R' F' R U' R",
        "R U' R U' f R f'",
        "R U' R U' S R S'",
        "R' U' f' U R' U' R f",
        "R S' U' S R U' R",
        "R U' R2 f' U f R'",
        "R U' R2 U2 F R2 F'",
        "R U' R2 U2 f R2 f'",
        "R U' R U' S R' S' R2",
        "R U' R2 U' F' U' F R2",
      ],
    },
    {
      id: "brPair-66",
      algs: [
        "R U' R' U' R",
        "R F' U2 F R",
        "U' R2 U' R' U2 R2",
        "R U' R' U R' U2 R",
        "U2 R U2 R' U R' U' R",
        "R' F R2 F' U2 R",
        "U' D f R' f' D' R",
        "R F' R' U2 R F",
        "R U' R' U R U2 R",
        "U' R' U' R2 F R' F'",
      ],
    },
    {
      id: "brPair-67",
      algs: [
        "R2 U R2",
        "U' R F R' F'",
        "U' R2 U R' U R'",
        "U' R2 U R' U' R'",
        "U' R F R2 F' R",
        "U' R' f R2 f' U2 R",
        "U' R2 U R' U2 R'",
        "U' D R' U' R U D' R",
        "U' R U' F' U F R'",
        "U' R' f R f' U' R",
      ],
    },
    {
      id: "brPair-68",
      algs: [
        "R U' F R2 F' R2",
        "R U R' U' R U R2",
        "R U' F R' F' U' R2",
        "R U' R U R2 U' R",
        "R U2 R U R' U' R",
        "R U2 R' U2 R U R2",
        "F R' F' R F R' F'",
        "R U' R' U' S R2 S' R'",
        "R U' F R' S R' f' R2",
        "F R' F' R2 U R2",
      ],
    },
    {
      id: "brPair-69",
      algs: [
        "R2 U' R2 U2 R2",
        "R2 U2 R2 U' R2",
        "R' f' U R' U R f R",
        "R U' R2 U2 R U' R",
        "R2 U R' S' U2 S R'",
        "R' f' U2 f R' U R2",
        "R U' R U2 R2 U' R",
        "R2 U' R2 F R2 F' U2 R2",
        "R2 U' R2 f R2 f' U2 R2",
        "R F R U R2 U' R2 F'",
      ],
    },
    {
      id: "brPair-70",
      algs: [
        "R U' R",
        "U R' U' R2 U' R",
        "R U2 R' U R",
        "U' R' U' R U R U' R",
        "R U R' U2 R",
        "U f R' f' R U' R",
        "R U R2 U2 R",
        "R U' R' S R2 S'",
        "U' R' F R2 F' U' R2",
        "U' R' U2 R U R U' R",
      ],
    },
    {
      id: "brPair-71",
      algs: [
        "R' U' R U2 R U' R",
        "R' U R2 U' R",
        "R U' R' U R2 U' R2",
        "R U' R2 F R2 F' R'",
        "R' F R2 F' R U' R2",
        "R' U2 R U' R U' R",
        "R2 F R2 F' R2",
        "R2 f R2 f' R2",
        "R U' R2 F R2 F' U' R'",
        "R2 U' R' U2 R U R2",
      ],
    },
    {
      id: "brPair-72",
      algs: [
        "R U' R' U R U' R2",
        "R U' R' U2 R U2 R2",
        "R U2 f' U f R",
        "R U' R2 F R F' R'",
        "R U R' S' U2 S R",
        "R U' R' S R' S' R'",
        "R U' R' S R' S' U' R'",
        "D R' U' R D' R U2 R2",
        "R U f R f' U R2",
        "R U' F U R' U' F' R2",
      ],
    },
    {
      id: "brPair-73",
      algs: [
        "R U' R' U R' U' R2",
        "R2 U' R' U R' U' R",
        "R F' R' U' R F R",
        "R' F R2 F' R' U' R2",
        "R' f R2 f' R U' R2",
        "D R' U' R U2 D' R2",
        "D' R U R' D R U' R",
        "R U' R D R' U R D'",
        "R' U' F R2 F' R' U' R2",
        "R' U' f R2 f' R U' R2",
      ],
    },
    {
      id: "brPair-74",
      algs: [
        "R U R' U' R2",
        "U F R2 F' R'",
        "U R U R2 U' R2",
        "U' R U' R U' R' U R2",
        "U' R U2 R' U2 R2",
        "U2 R' F R S R' f'",
        "U2 R' f R' f' R",
        "U F R2 F' U' R'",
        "U' S R2 S' R",
        "U S' U2 S R'",
      ],
    },
    {
      id: "brPair-75",
      algs: [
        "F R F' R'",
        "R F' U' F R'",
        "R U R U' R2",
        "F R F' U' R'",
        "F R F' U R'",
        "f R F' R' S'",
        "R F' U' F U' R'",
        "F R F' U2 R'",
        "R U R U' R' U R'",
        "R F' U' F U R'",
      ],
    },
    {
      id: "brPair-76",
      algs: [
        "R'",
        "U' R' U' R U R'",
        "U' R' U' R U' R'",
        "U' R' U' F' U' F",
        "U' R' U' f' U' f",
        "U' R2 U' R' U R",
        "U' f R f' R'",
        "U' R' U' R U2 R'",
        "U' R' U2 R U R'",
        "U' R' F' U F",
      ],
    },
    {
      id: "brPair-77",
      algs: [
        "R' f R S' R' F'",
        "R' S R S' R'",
        "R' U' S R S' R'",
        "R' U' f R S' R' F'",
        "R2 U R' U R U' R",
        "D f R f' D' R2",
        "R' U2 S R S' R'",
        "R' S R S' U R'",
        "R' S R S' U' R'",
        "R' U' S R S' U R'",
      ],
    },
    {
      id: "brPair-78",
      algs: [
        "f' U' f R",
        "F' U' f R S'",
        "U R U f R f' R",
        "f' U' f R2 U' R'",
        "F R' F' f' U' f R",
        "U R U F R' S R' f'",
        "U' R' f R2 S' R' F' U' R",
        "R' F R f' U' S R",
        "U f R' F' R F R' f'",
        "U f R' f' R F R' F'",
      ],
    },
    {
      id: "brPair-79",
      algs: [
        "R U R' f R f' R",
        "R' U' R f' U' f R",
        "f' R' U' R U' f R",
        "R' U' R F' U' f R S'",
        "R U2 R' U' f R f' R",
        "R' U' F R f' U' S R",
        "R' U2 S R2 F R' f'",
        "R' U R' U R f R f'",
        "f R D R2 D' f' R",
        "f R' f' R U' R' U' R",
      ],
    },
    {
      id: "brPair-80",
      algs: [
        "R U' F' R' U' R F",
        "R' f R D R' D' f' R",
        "R U' F' R' U' R U F",
        "R F R' D R' D' F'",
        "R U' f' R' U' R f",
        "R U R2 f R S' R F'",
        "R2 U R' S' U' S R'",
        "R F R' F' S R' S' R",
        "R U R2 f R f' R",
        "R2 U R' U' S R' S'",
      ],
    },
    {
      id: "brPair-81",
      algs: [
        "R f R' f'",
        "F' U' F R",
        "R U' R' U' f R f'",
        "R U F R2 F'",
        "R' F R F' U' R",
        "R U R' U' f R' f'",
        "R U R2 F R2 F'",
        "R U R2 f R2 f'",
        "R U' R' S' U' S R",
        "R2 U R' S R' S'",
      ],
    },
    {
      id: "brPair-82",
      algs: [
        "F R' F' R U' R",
        "U' R U' f R f'",
        "U' R S' U' S R",
        "U' R U2 R' U f R f'",
        "U R' F R U R U' F' R",
        "R2 U2 R' f R f' R",
        "U' R2 U2 R2 F R2 F'",
        "U' R2 U2 R2 f R2 f'",
        "R2 U' R' U' f R f' R",
        "U R' F R2 F' R2 U' R2",
      ],
    },
    {
      id: "brPair-83",
      algs: [
        "R U' R' S R S' R",
        "F R2 F' R U' R",
        "R U' R2 S R S' R2",
        "R U' F R' S R f' R",
        "R' f R2 F' R' S' U' R2",
        "f R' f' U' R U' R",
        "R2 F' R' U' R F",
        "F R' f' U' S R U' R",
        "R' S' U' S R2 U' R",
        "R' U' R2 U' f R f'",
      ],
    },
    {
      id: "brPair-84",
      algs: [
        "f R' S' R F' R U' R",
        "F R F' R U' R",
        "S' U S R U' R",
        "R' S R S' U R U' R",
        "F R F' R U2 R' U R",
        "R S R' S' U R U' R",
        "F R f' R U' R' S R2",
        "R' f' R' U R f U R2",
        "R U' R U2 R' f R f'",
        "R U' f R F' R' S' R",
      ],
    },
    {
      id: "brPair-85",
      algs: [
        "R U' R U' R' f R f'",
        "R U' R U' R' S R S'",
        "R F' U F U2 R2",
        "R F' U F U2 R' U R'",
        "R S' R' U' R S U' R",
        "R F' U F U2 R' U2 R'",
        "F' U F R' U' R U' R",
        "R' U' R2 F' U F U2 R2",
        "R2 U2 f R S' R F'",
        "R S R F R2 f' R2",
      ],
    },
    {
      id: "brPair-86",
      algs: [
        "R U' R' f R' f'",
        "S R' S'",
        "R' U' R S R' S'",
        "U S' U' S R'",
        "R' U2 R S R' S'",
        "U F R' F' R'",
        "S R S' R2",
        "R S R S' R",
        "R U' R2 F' U' F R",
        "R' S R' S' R",
      ],
    },
    {
      id: "brPair-87",
      algs: [
        "R U' R' U f R f' R",
        "R' U' R U S R' S'",
        "R' U' R S' U S R'",
        "R' D f R' f' D'",
        "f R' F' R2 S' R",
        "F R' F' R S R S' R",
        "R' U' R U S R S' R2",
        "R' U2 R U2 S R' S'",
        "R' U' R S' U S U' R'",
        "R' U' R U2 S' U' S R'",
      ],
    },
    {
      id: "brPair-88",
      algs: [
        "F R F' R' f R' f' R",
        "R' f D R2 D' R' f' R",
        "R U' F' U' F R' U2 R2",
        "R U F' U' F R' U' R2",
        "R U R2 U' S R S' R",
        "F R' D R D' R' F' R2",
        "F R2 F' R' S R' S' R",
        "R U R2 U' R' S R' S'",
        "F R f' U S2 R' S'",
        "R U R2 U2 R' f R' f'",
      ],
    },
    {
      id: "brPair-89",
      algs: [
        "R U' R2 f' U' f R",
        "R U' R2 F' U' f R S'",
        "R2 U2 R' S' U' S U' R",
        "R U' F R2 f' U' S R",
        "R2 U2 R' U2 S R S'",
        "R2 U2 R' S' R' U2 R S",
        "R' F S' D R D' F' S",
        "R F R' F' R2 U' R",
        "R S R2 S' R' f R f'",
        "R2 U2 R' F R' F' U' R",
      ],
    },
  ],
});
